###############################################################
#  Generated by:      Cadence Encounter 13.10-p003_1
#  OS:                Linux i686(Host ID cadence)
#  Generated on:      Fri Sep  4 09:02:59 2026
#  Design:            top_module
#  Command:           saveFPlan ouput/ouput_final/top_module.fp
###############################################################

Version: 8

Head Box: 0.0000 0.0000 61.9000 59.4000
IO Box: 0.0000 0.0000 61.9000 59.4000
Core Box: 10.0000 10.0700 51.9000 49.4000
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: CoreSite 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 CoreSite 10.0000 10.0700 FS 209 1 0.2000 0.0000
DefRow: ROW_1 CoreSite 10.0000 11.7800 N 209 1 0.2000 0.0000
DefRow: ROW_2 CoreSite 10.0000 13.4900 FS 209 1 0.2000 0.0000
DefRow: ROW_3 CoreSite 10.0000 15.2000 N 209 1 0.2000 0.0000
DefRow: ROW_4 CoreSite 10.0000 16.9100 FS 209 1 0.2000 0.0000
DefRow: ROW_5 CoreSite 10.0000 18.6200 N 209 1 0.2000 0.0000
DefRow: ROW_6 CoreSite 10.0000 20.3300 FS 209 1 0.2000 0.0000
DefRow: ROW_7 CoreSite 10.0000 22.0400 N 209 1 0.2000 0.0000
DefRow: ROW_8 CoreSite 10.0000 23.7500 FS 209 1 0.2000 0.0000
DefRow: ROW_9 CoreSite 10.0000 25.4600 N 209 1 0.2000 0.0000
DefRow: ROW_10 CoreSite 10.0000 27.1700 FS 209 1 0.2000 0.0000
DefRow: ROW_11 CoreSite 10.0000 28.8800 N 209 1 0.2000 0.0000
DefRow: ROW_12 CoreSite 10.0000 30.5900 FS 209 1 0.2000 0.0000
DefRow: ROW_13 CoreSite 10.0000 32.3000 N 209 1 0.2000 0.0000
DefRow: ROW_14 CoreSite 10.0000 34.0100 FS 209 1 0.2000 0.0000
DefRow: ROW_15 CoreSite 10.0000 35.7200 N 209 1 0.2000 0.0000
DefRow: ROW_16 CoreSite 10.0000 37.4300 FS 209 1 0.2000 0.0000
DefRow: ROW_17 CoreSite 10.0000 39.1400 N 209 1 0.2000 0.0000
DefRow: ROW_18 CoreSite 10.0000 40.8500 FS 209 1 0.2000 0.0000
DefRow: ROW_19 CoreSite 10.0000 42.5600 N 209 1 0.2000 0.0000
DefRow: ROW_20 CoreSite 10.0000 44.2700 FS 209 1 0.2000 0.0000
DefRow: ROW_21 CoreSite 10.0000 45.9800 N 209 1 0.2000 0.0000
DefRow: ROW_22 CoreSite 10.0000 47.6900 FS 209 1 0.2000 0.0000

######################################################
#  Track: dir start number space layer_num layer1 ...#
######################################################
Track: X 0.1000 309 0.2000 1 9
Track: Y 0.4750 156 0.3800 1 9
Track: Y 0.3800 208 0.2850 1 8
Track: X 0.1000 309 0.2000 1 8
Track: X 0.1000 309 0.2000 1 7
Track: Y 0.3800 208 0.2850 1 7
Track: Y 0.0950 313 0.1900 1 6
Track: X 0.1000 309 0.2000 1 6
Track: X 0.1000 309 0.2000 1 5
Track: Y 0.0950 313 0.1900 1 5
Track: Y 0.0950 313 0.1900 1 4
Track: X 0.1000 309 0.2000 1 4
Track: X 0.1000 309 0.2000 1 3
Track: Y 0.0950 313 0.1900 1 3
Track: Y 0.0950 313 0.1900 1 2
Track: X 0.1000 309 0.2000 1 2
Track: X 0.1000 309 0.2000 1 1
Track: Y 0.0950 313 0.1900 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X -0.0050 2 3.0050
GCellGrid: X 6.0000 19 3.0000
GCellGrid: X 61.9050 1 1.9050
GCellGrid: Y -0.0050 20 3.0000
GCellGrid: Y 59.4050 1 2.4100

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: VDD -pwr
PhysicalNet: VSS -gnd

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val     #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val >#
#         <Net name="net_name" /> ...                                     #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d />               #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge edgeNumber=val />                                   #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr            #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val >#
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="top_module" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x1ff >
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes Metal8=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes Metal8=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################
Instance: clk_50mhz__L2_I0 R0 21.6000 32.3000
Instance: clk_50mhz__L1_I0 R0 10.0000 28.8800
Instance: u_clk/clk_1hz_reg MX 14.0000 23.7500
Instance: u_clk/cnt_reg[10] R0 26.2000 39.1400
Instance: u_clk/cnt_reg[5] R0 21.4000 28.8800
Instance: u_clk/cnt_reg[6] MX 26.2000 27.1700
Instance: u_clk/cnt_reg[7] R0 26.2000 28.8800
Instance: u_clk/cnt_reg[8] R0 25.2000 35.7200
Instance: u_clk/cnt_reg[9] R0 21.6000 39.1400
Instance: u_clk/cnt_reg[11] R0 28.0000 42.5600
Instance: u_clk/cnt_reg[12] MX 24.4000 40.8500
Instance: u_clk/cnt_reg[13] R0 29.8000 45.9800
Instance: u_clk/cnt_reg[14] R0 25.0000 45.9800
Instance: u_clk/cnt_reg[15] R0 20.2000 45.9800
Instance: u_clk/cnt_reg[16] R0 17.4000 42.5600
Instance: u_clk/cnt_reg[17] MX 14.6000 44.2700
Instance: u_clk/cnt_reg[18] R0 11.8000 45.9800
Instance: u_clk/cnt_reg[19] R0 10.2000 42.5600
Instance: u_clk/cnt_reg[1] MX 17.8000 40.8500
Instance: u_clk/cnt_reg[20] R0 14.0000 39.1400
Instance: u_clk/cnt_reg[21] R0 12.0000 35.7200
Instance: u_clk/cnt_reg[22] R0 12.4000 32.3000
Instance: u_clk/cnt_reg[23] MX 12.8000 30.5900
Instance: u_clk/cnt_reg[24] MX 10.2000 20.3300
Instance: u_clk/cnt_reg[25] R0 11.4000 22.0400
Instance: u_clk/cnt_reg[2] MX 18.6000 34.0100
Instance: u_clk/cnt_reg[3] R0 17.0000 32.3000
Instance: u_clk/cnt_reg[4] R0 12.8000 25.4600
Instance: u_clk/cnt_reg[0] MX 21.6000 37.4300

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

#################################################################
#  <PlacementBlockages>                                         #
#     <Blockage name="blk_name" type="hard|soft|partial">       #
#       <Attr density=1.2 inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </PlacementBlockages>                                        #
#################################################################
<PlacementBlockages>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=0.0000 lly=0.0000 urx=2.0000 ury=59.4700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=8.4000 lly=49.4000 urx=52.2000 ury=59.4700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=19.0000 lly=0.0000 urx=62.0000 ury=0.7600 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=11.0000 lly=0.0000 urx=20.2000 ury=0.7600 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=10.0000 lly=0.0000 urx=11.6000 ury=0.5700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=10.0000 lly=0.1900 urx=11.2000 ury=0.5700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=0.2000 lly=0.1900 urx=62.0000 ury=10.0700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=10.0000 lly=0.1900 urx=62.0000 ury=0.5700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=10.0000 lly=0.9500 urx=11.2000 ury=10.0700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=61.6000 lly=0.1900 urx=62.0000 ury=8.5500 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=52.0000 lly=8.3600 urx=62.0000 ury=59.4700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=10.2000 lly=0.1900 urx=61.8000 ury=10.0700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=0.0000 lly=0.0000 urx=10.2000 ury=0.9500 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=10.0000 lly=0.1900 urx=12.8000 ury=0.9500 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=0.2000 lly=0.1900 urx=10.0000 ury=59.4700 />
    </Blockage>
</PlacementBlockages>

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

###########################################################################
#  <RouteBlockages>                                                       #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">   #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes />   #
#       <Layer type="route|cut|masterslice" id=layerNo />                 #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                       #
#     </Blockage>                                                         #
#  </RouteBlockages>                                                      #
###########################################################################
<RouteBlockages>
    <Blockage type="User">
	<Layer type="route" id=3 />
	<Box llx=0.0000 lly=57.6900 urx=61.9000 ury=59.4000 />
    </Blockage>
    <Blockage type="User">
	<Layer type="route" id=3 />
	<Box llx=60.5600 lly=0.0000 urx=61.9000 ury=59.4000 />
    </Blockage>
    <Blockage type="User">
	<Layer type="route" id=3 />
	<Box llx=0.0000 lly=0.0000 urx=61.9000 ury=1.4750 />
    </Blockage>
    <Blockage type="User">
	<Layer type="route" id=3 />
	<Box llx=0.0000 lly=0.0000 urx=1.5500 ury=36.6700 />
    </Blockage>
    <Blockage type="User">
	<Layer type="route" id=3 />
	<Box llx=0.0000 lly=36.6700 urx=1.5500 ury=59.4000 />
    </Blockage>
</RouteBlockages>

######################################################
#  PrerouteAsObstruct: <layer_treated_as_obstruct>   #
######################################################
PrerouteAsObstruct: 0x3

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: top_module.fp.spr

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 />...                                  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="clk_50mhz" status="fixed" >
    <Port>
      <Pref x=0.0000 y=28.9750 side=W width=0.2000 depth=2.0000 orientation=R270 />
      <Layer id=3 >
        <Box llx=0.0000 lly=28.8750 urx=2.0000 ury=29.0750 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="rst" status="fixed" >
    <Port>
      <Pref x=0.0000 y=37.5250 side=W width=0.2000 depth=2.0000 orientation=R270 />
      <Layer id=3 >
        <Box llx=0.0000 lly=37.4250 urx=2.0000 ury=37.6250 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="LED_1[2]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=7.8850 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=7.7850 urx=61.9000 ury=7.9850 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="LED_1[1]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=9.4050 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=9.3050 urx=61.9000 ury=9.5050 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="LED_1[0]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=10.7350 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=10.6350 urx=61.9000 ury=10.8350 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="LED_2[2]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=3.5150 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=3.4150 urx=61.9000 ury=3.6150 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="LED_2[1]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=5.0350 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=4.9350 urx=61.9000 ury=5.1350 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="LED_2[0]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=6.5550 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=6.4550 urx=61.9000 ury=6.6550 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_ch[6]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=45.8850 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=45.7850 urx=61.9000 ury=45.9850 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_ch[5]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=47.4050 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=47.3050 urx=61.9000 ury=47.5050 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_ch[4]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=48.9250 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=48.8250 urx=61.9000 ury=49.0250 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_ch[3]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=50.4450 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=50.3450 urx=61.9000 ury=50.5450 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_ch[2]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=51.7750 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=51.6750 urx=61.9000 ury=51.8750 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_ch[1]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=53.2950 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=53.1950 urx=61.9000 ury=53.3950 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_ch[0]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=2.1850 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=2.0850 urx=61.9000 ury=2.2850 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_dv[6]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=36.1950 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=36.0950 urx=61.9000 ury=36.2950 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_dv[5]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=37.5250 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=37.4250 urx=61.9000 ury=37.6250 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_dv[4]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=38.6650 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=38.5650 urx=61.9000 ury=38.7650 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_dv[3]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=40.1850 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=40.0850 urx=61.9000 ury=40.2850 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_dv[2]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=41.7050 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=41.6050 urx=61.9000 ury=41.8050 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_dv[1]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=43.0350 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=42.9350 urx=61.9000 ury=43.1350 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_dv[0]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=44.5550 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=44.4550 urx=61.9000 ury=44.6550 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_ch[6]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=26.8850 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=26.7850 urx=61.9000 ury=26.9850 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_ch[5]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=28.2150 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=28.1150 urx=61.9000 ury=28.3150 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_ch[4]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=29.5450 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=29.4450 urx=61.9000 ury=29.6450 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_ch[3]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=30.8750 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=30.7750 urx=61.9000 ury=30.9750 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_ch[2]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=32.2050 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=32.1050 urx=61.9000 ury=32.3050 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_ch[1]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=33.5350 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=33.4350 urx=61.9000 ury=33.6350 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_ch[0]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=34.8650 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=34.7650 urx=61.9000 ury=34.9650 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_dv[6]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=18.1450 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=18.0450 urx=61.9000 ury=18.2450 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_dv[5]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=19.2850 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=19.1850 urx=61.9000 ury=19.3850 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_dv[4]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=20.4250 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=20.3250 urx=61.9000 ury=20.5250 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_dv[3]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=21.5650 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=21.4650 urx=61.9000 ury=21.6650 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_dv[2]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=22.8950 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=22.7950 urx=61.9000 ury=22.9950 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_dv[1]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=24.2250 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=24.1250 urx=61.9000 ury=24.3250 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_dv[0]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=25.5550 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=25.4550 urx=61.9000 ury=25.6550 />
      </Layer>
    </Port>
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="top_module">
	<prop name="TDRCAppName" type=String value="OPT_LA:1 GPS_LA:2 NRImport:3 NRTD:4 prLA:5 " />
	<prop name="optimization_trialRoute_guide_flow" type=Int value=1 />
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
