/*
###############################################################
#  Generated by:      Cadence Encounter 13.10-p003_1
#  OS:                Linux i686(Host ID cadence)
#  Generated on:      Fri Sep  4 09:25:38 2026
#  Design:            top_module
#  Command:           saveNetlist /home/buet/Desktop/Traffic_light/PnR/Desig...
###############################################################
*/
/*
###############################################################
#  Generated by:      Cadence Encounter 13.10-p003_1
#  OS:                Linux i686(Host ID cadence)
#  Generated on:      Fri Aug  7 08:14:03 2026
#  Design:            top_module
#  Command:           saveDesign ouput/top_module_routing.enc
###############################################################
*/
/*
###############################################################
#  Generated by:      Cadence Encounter 13.10-p003_1
#  OS:                Linux i686(Host ID cadence)
#  Generated on:      Fri Aug  7 07:41:35 2026
#  Design:            top_module
#  Command:           saveDesign ouput/top_module_floorplan.enc
###############################################################
*/
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1
// Verification Directory fv/top_module 
module increment_unsigned (
	A, 
	CI, 
	Z);
   input [25:0] A;
   input CI;
   output [25:0] Z;

   // Internal wires
   wire FE_PHN42_n_66;
   wire FE_PHN40_n_70;
   wire FE_PHN39_n_73;
   wire FE_PHN29_n_53;
   wire FE_PHN25_n_54;
   wire FE_PHN24_n_64;
   wire FE_PHN16_n_57;
   wire n_23;
   wire n_25;
   wire n_27;
   wire n_29;
   wire n_31;
   wire n_33;
   wire n_35;
   wire n_37;
   wire n_39;
   wire n_41;
   wire n_43;
   wire n_45;
   wire n_47;
   wire n_49;
   wire n_51;
   wire n_53;
   wire n_55;
   wire n_57;
   wire n_59;
   wire n_61;
   wire n_63;
   wire n_65;
   wire n_67;
   wire n_69;

   assign Z[0] = 1'b0 ;

   CLKBUFX2 FE_PHC42_n_66 (.Y(Z[9]),
	.A(FE_PHN42_n_66));
   CLKBUFX2 FE_PHC40_n_70 (.Y(Z[5]),
	.A(FE_PHN40_n_70));
   CLKBUFX2 FE_PHC39_n_73 (.Y(Z[2]),
	.A(FE_PHN39_n_73));
   DLY1X4 FE_PHC29_n_53 (.Y(Z[22]),
	.A(FE_PHN29_n_53));
   DLY1X4 FE_PHC25_n_54 (.Y(Z[21]),
	.A(FE_PHN25_n_54));
   DLY1X4 FE_PHC24_n_64 (.Y(Z[11]),
	.A(FE_PHN24_n_64));
   DLY1X4 FE_PHC16_n_57 (.Y(Z[18]),
	.A(FE_PHN16_n_57));
   CLKXOR2X1 g175 (.Y(Z[25]),
	.B(n_69),
	.A(A[25]));
   ADDHXL g176 (.S(Z[24]),
	.CO(n_69),
	.B(n_67),
	.A(A[24]));
   ADDHXL g177 (.S(Z[23]),
	.CO(n_67),
	.B(n_65),
	.A(A[23]));
   ADDHXL g178 (.S(FE_PHN29_n_53),
	.CO(n_65),
	.B(n_63),
	.A(A[22]));
   ADDHXL g179 (.S(FE_PHN25_n_54),
	.CO(n_63),
	.B(n_61),
	.A(A[21]));
   ADDHXL g180 (.S(Z[20]),
	.CO(n_61),
	.B(n_59),
	.A(A[20]));
   ADDHXL g181 (.S(Z[19]),
	.CO(n_59),
	.B(n_57),
	.A(A[19]));
   ADDHXL g182 (.S(FE_PHN16_n_57),
	.CO(n_57),
	.B(n_55),
	.A(A[18]));
   ADDHXL g183 (.S(Z[17]),
	.CO(n_55),
	.B(n_53),
	.A(A[17]));
   ADDHXL g184 (.S(Z[16]),
	.CO(n_53),
	.B(n_51),
	.A(A[16]));
   ADDHXL g185 (.S(Z[15]),
	.CO(n_51),
	.B(n_49),
	.A(A[15]));
   ADDHXL g186 (.S(Z[14]),
	.CO(n_49),
	.B(n_47),
	.A(A[14]));
   ADDHXL g187 (.S(Z[13]),
	.CO(n_47),
	.B(n_45),
	.A(A[13]));
   ADDHXL g188 (.S(Z[12]),
	.CO(n_45),
	.B(n_43),
	.A(A[12]));
   ADDHXL g189 (.S(FE_PHN24_n_64),
	.CO(n_43),
	.B(n_41),
	.A(A[11]));
   ADDHXL g190 (.S(Z[10]),
	.CO(n_41),
	.B(n_39),
	.A(A[10]));
   ADDHXL g191 (.S(FE_PHN42_n_66),
	.CO(n_39),
	.B(n_37),
	.A(A[9]));
   ADDHXL g192 (.S(Z[8]),
	.CO(n_37),
	.B(n_35),
	.A(A[8]));
   ADDHXL g193 (.S(Z[7]),
	.CO(n_35),
	.B(n_33),
	.A(A[7]));
   ADDHXL g194 (.S(Z[6]),
	.CO(n_33),
	.B(n_31),
	.A(A[6]));
   ADDHXL g195 (.S(FE_PHN40_n_70),
	.CO(n_31),
	.B(n_29),
	.A(A[5]));
   ADDHXL g196 (.S(Z[4]),
	.CO(n_29),
	.B(n_27),
	.A(A[4]));
   ADDHXL g197 (.S(Z[3]),
	.CO(n_27),
	.B(n_25),
	.A(A[3]));
   ADDHXL g198 (.S(FE_PHN39_n_73),
	.CO(n_25),
	.B(n_23),
	.A(A[2]));
   ADDHXL g199 (.S(Z[1]),
	.CO(n_23),
	.B(A[1]),
	.A(A[0]));
endmodule

module clk_1hz (
	clk_50mhz, 
	rst, 
	clk_1hz);
   input clk_50mhz;
   input rst;
   output clk_1hz;

   // Internal wires
   wire FE_PHN45_n_63;
   wire FE_PHN44_n_55;
   wire FE_PHN43_n_57;
   wire FE_PHN41_n_68;
   wire FE_PHN38_n_69;
   wire FE_PHN37_n_74;
   wire FE_PHN36_n_72;
   wire FE_PHN35_n_71;
   wire FE_PHN34_n_65;
   wire FE_PHN33_n_1;
   wire FE_PHN32_n_43;
   wire FE_PHN31_n_41;
   wire FE_PHN30_n_50;
   wire FE_PHN28_n_59;
   wire FE_PHN27_n_58;
   wire FE_PHN26_n_61;
   wire FE_PHN23_n_62;
   wire FE_PHN22_n_56;
   wire FE_PHN21_n_52;
   wire FE_PHN20_n_55;
   wire FE_PHN19_cnt_8_;
   wire FE_PHN18_n_51;
   wire FE_PHN17_n_63;
   wire FE_PHN15_cnt_6_;
   wire FE_PHN14_n_60;
   wire FE_PHN13_cnt_5_;
   wire FE_PHN12_cnt_7_;
   wire FE_PHN11_cnt_9_;
   wire FE_PHN10_clk_1hz;
   wire FE_PHN9_cnt_4_;
   wire FE_PHN8_cnt_2_;
   wire FE_PHN7_cnt_1_;
   wire FE_PHN6_cnt_3_;
   wire FE_PHN5_cnt_0_;
   wire FE_OFN1_n_46;
   wire FE_OFN0_n_19;
   wire [25:0] cnt;
   wire UNCONNECTED;
   wire n_1;
   wire n_2;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_78;
   wire n_79;

   CLKBUFX2 FE_PHC45_n_63 (.Y(FE_PHN45_n_63),
	.A(FE_PHN17_n_63));
   CLKBUFX2 FE_PHC44_n_55 (.Y(FE_PHN20_n_55),
	.A(FE_PHN44_n_55));
   CLKBUFX2 FE_PHC43_n_57 (.Y(FE_PHN43_n_57),
	.A(n_57));
   CLKBUFX2 FE_PHC41_n_68 (.Y(FE_PHN41_n_68),
	.A(n_68));
   CLKBUFX2 FE_PHC38_n_69 (.Y(FE_PHN38_n_69),
	.A(n_69));
   CLKBUFX2 FE_PHC37_n_74 (.Y(FE_PHN37_n_74),
	.A(n_74));
   CLKBUFX2 FE_PHC36_n_72 (.Y(FE_PHN36_n_72),
	.A(n_72));
   CLKBUFX2 FE_PHC35_n_71 (.Y(FE_PHN35_n_71),
	.A(n_71));
   CLKBUFX2 FE_PHC34_n_65 (.Y(FE_PHN34_n_65),
	.A(n_65));
   DLY2X1 FE_PHC33_n_1 (.Y(FE_PHN33_n_1),
	.A(n_1));
   DLY1X4 FE_PHC32_n_43 (.Y(n_43),
	.A(FE_PHN32_n_43));
   DLY1X1 FE_PHC31_n_41 (.Y(n_41),
	.A(FE_PHN31_n_41));
   DLY1X4 FE_PHC30_n_50 (.Y(FE_PHN30_n_50),
	.A(n_50));
   DLY1X4 FE_PHC28_n_59 (.Y(FE_PHN28_n_59),
	.A(n_59));
   DLY1X4 FE_PHC27_n_58 (.Y(FE_PHN27_n_58),
	.A(n_58));
   DLY1X4 FE_PHC26_n_61 (.Y(FE_PHN26_n_61),
	.A(n_61));
   DLY2X1 FE_PHC23_n_62 (.Y(FE_PHN23_n_62),
	.A(n_62));
   DLY1X4 FE_PHC22_n_56 (.Y(FE_PHN22_n_56),
	.A(n_56));
   DLY1X4 FE_PHC21_n_52 (.Y(FE_PHN21_n_52),
	.A(n_52));
   DLY1X4 FE_PHC20_n_55 (.Y(FE_PHN44_n_55),
	.A(n_55));
   DLY1X1 FE_PHC19_cnt_8_ (.Y(FE_PHN19_cnt_8_),
	.A(cnt[8]));
   DLY1X4 FE_PHC18_n_51 (.Y(FE_PHN18_n_51),
	.A(n_51));
   DLY1X4 FE_PHC17_n_63 (.Y(FE_PHN17_n_63),
	.A(n_63));
   DLY1X1 FE_PHC15_cnt_6_ (.Y(FE_PHN15_cnt_6_),
	.A(cnt[6]));
   DLY1X4 FE_PHC14_n_60 (.Y(FE_PHN14_n_60),
	.A(n_60));
   DLY1X1 FE_PHC13_cnt_5_ (.Y(FE_PHN13_cnt_5_),
	.A(cnt[5]));
   DLY1X1 FE_PHC12_cnt_7_ (.Y(FE_PHN12_cnt_7_),
	.A(cnt[7]));
   DLY1X1 FE_PHC11_cnt_9_ (.Y(FE_PHN11_cnt_9_),
	.A(cnt[9]));
   DLY2X1 FE_PHC10_clk_1hz (.Y(FE_PHN10_clk_1hz),
	.A(clk_1hz));
   DLY1X1 FE_PHC9_cnt_4_ (.Y(FE_PHN9_cnt_4_),
	.A(cnt[4]));
   DLY1X4 FE_PHC8_cnt_2_ (.Y(FE_PHN8_cnt_2_),
	.A(cnt[2]));
   DLY2X1 FE_PHC7_cnt_1_ (.Y(FE_PHN7_cnt_1_),
	.A(cnt[1]));
   DLY1X1 FE_PHC6_cnt_3_ (.Y(FE_PHN6_cnt_3_),
	.A(cnt[3]));
   DLY1X1 FE_PHC5_cnt_0_ (.Y(FE_PHN5_cnt_0_),
	.A(cnt[0]));
   CLKBUFX3 FE_OFC1_n_46 (.Y(FE_OFN1_n_46),
	.A(n_46));
   CLKBUFX2 FE_OFC0_n_19 (.Y(FE_OFN0_n_19),
	.A(n_19));
   increment_unsigned inc_add_27_24_1 (.A({ cnt[25],
		cnt[24],
		cnt[23],
		cnt[22],
		cnt[21],
		cnt[20],
		cnt[19],
		cnt[18],
		cnt[17],
		cnt[16],
		cnt[15],
		cnt[14],
		cnt[13],
		cnt[12],
		cnt[11],
		cnt[10],
		FE_PHN11_cnt_9_,
		FE_PHN19_cnt_8_,
		FE_PHN12_cnt_7_,
		FE_PHN15_cnt_6_,
		FE_PHN13_cnt_5_,
		FE_PHN9_cnt_4_,
		FE_PHN6_cnt_3_,
		FE_PHN8_cnt_2_,
		FE_PHN7_cnt_1_,
		FE_PHN5_cnt_0_ }),
	.CI(1'b1),
	.Z({ n_50,
		n_51,
		n_52,
		n_53,
		n_54,
		n_55,
		n_56,
		n_57,
		n_58,
		n_59,
		n_60,
		n_61,
		n_62,
		n_63,
		n_64,
		n_65,
		n_66,
		n_67,
		n_68,
		n_69,
		n_70,
		n_71,
		n_72,
		n_73,
		n_74,
		UNCONNECTED }));
   INVX3 g72 (.Y(n_46),
	.A(rst));
   SDFFRHQX1 clk_1hz_reg (.SI(FE_OFN0_n_19),
	.SE(FE_PHN10_clk_1hz),
	.RN(n_46),
	.Q(clk_1hz),
	.D(n_18),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[10]  (.RN(FE_OFN1_n_46),
	.Q(cnt[10]),
	.D(n_41),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[5]  (.RN(n_46),
	.Q(cnt[5]),
	.D(n_33),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[6]  (.RN(n_46),
	.Q(cnt[6]),
	.D(n_42),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[7]  (.RN(n_46),
	.Q(cnt[7]),
	.D(n_44),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[8]  (.RN(FE_OFN1_n_46),
	.Q(cnt[8]),
	.D(n_43),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[9]  (.RN(FE_OFN1_n_46),
	.Q(cnt[9]),
	.D(n_45),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[11]  (.RN(FE_OFN1_n_46),
	.Q(cnt[11]),
	.D(n_40),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[12]  (.RN(FE_OFN1_n_46),
	.Q(cnt[12]),
	.D(n_38),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[13]  (.RN(FE_OFN1_n_46),
	.Q(cnt[13]),
	.D(n_37),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[14]  (.RN(FE_OFN1_n_46),
	.Q(cnt[14]),
	.D(n_36),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[15]  (.RN(FE_OFN1_n_46),
	.Q(cnt[15]),
	.D(n_35),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[16]  (.RN(FE_OFN1_n_46),
	.Q(cnt[16]),
	.D(n_34),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[17]  (.RN(FE_OFN1_n_46),
	.Q(cnt[17]),
	.D(n_32),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[18]  (.RN(FE_OFN1_n_46),
	.Q(cnt[18]),
	.D(n_39),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[19]  (.RN(FE_OFN1_n_46),
	.Q(cnt[19]),
	.D(n_31),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[1]  (.RN(FE_OFN1_n_46),
	.Q(cnt[1]),
	.D(n_30),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[20]  (.RN(n_46),
	.Q(cnt[20]),
	.D(n_28),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[21]  (.RN(n_46),
	.Q(cnt[21]),
	.D(n_27),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[22]  (.RN(n_46),
	.Q(cnt[22]),
	.D(n_26),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[23]  (.RN(n_46),
	.Q(cnt[23]),
	.D(n_25),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[24]  (.RN(n_46),
	.Q(cnt[24]),
	.D(n_24),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[25]  (.RN(n_46),
	.Q(cnt[25]),
	.D(n_23),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[2]  (.RN(n_46),
	.Q(cnt[2]),
	.D(n_22),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[3]  (.RN(n_46),
	.Q(cnt[3]),
	.D(n_29),
	.CK(clk_50mhz));
   DFFRHQX2 \cnt_reg[4]  (.RN(n_46),
	.Q(cnt[4]),
	.D(n_21),
	.CK(clk_50mhz));
   NOR2BX1 g1045 (.Y(n_45),
	.B(n_18),
	.AN(n_66));
   NOR2BX1 g1046 (.Y(n_44),
	.B(n_18),
	.AN(FE_PHN41_n_68));
   NOR2BX1 g1047 (.Y(FE_PHN32_n_43),
	.B(n_18),
	.AN(n_67));
   NOR2BX1 g1048 (.Y(n_42),
	.B(n_18),
	.AN(FE_PHN38_n_69));
   NOR2BX1 g1049 (.Y(FE_PHN31_n_41),
	.B(n_18),
	.AN(FE_PHN34_n_65));
   AND2X1 g1050 (.Y(n_40),
	.B(FE_OFN0_n_19),
	.A(n_64));
   AND2X1 g1051 (.Y(n_39),
	.B(FE_PHN43_n_57),
	.A(FE_OFN0_n_19));
   AND2X1 g1052 (.Y(n_38),
	.B(FE_OFN0_n_19),
	.A(FE_PHN45_n_63));
   AND2X1 g1053 (.Y(n_37),
	.B(FE_PHN23_n_62),
	.A(FE_OFN0_n_19));
   AND2X1 g1054 (.Y(n_36),
	.B(FE_PHN26_n_61),
	.A(FE_OFN0_n_19));
   AND2X1 g1055 (.Y(n_35),
	.B(FE_PHN14_n_60),
	.A(FE_OFN0_n_19));
   AND2X1 g1056 (.Y(n_34),
	.B(FE_PHN28_n_59),
	.A(FE_OFN0_n_19));
   NOR2BX1 g1057 (.Y(n_33),
	.B(n_18),
	.AN(n_70));
   AND2X1 g1058 (.Y(n_32),
	.B(FE_PHN27_n_58),
	.A(FE_OFN0_n_19));
   AND2X1 g1059 (.Y(n_31),
	.B(FE_PHN22_n_56),
	.A(FE_OFN0_n_19));
   NOR2BX1 g1060 (.Y(n_30),
	.B(n_18),
	.AN(FE_PHN37_n_74));
   NOR2BX1 g1061 (.Y(n_29),
	.B(n_18),
	.AN(FE_PHN36_n_72));
   AND2X1 g1062 (.Y(n_28),
	.B(FE_PHN20_n_55),
	.A(FE_OFN0_n_19));
   AND2X1 g1063 (.Y(n_27),
	.B(n_54),
	.A(FE_OFN0_n_19));
   AND2X1 g1064 (.Y(n_26),
	.B(n_53),
	.A(FE_OFN0_n_19));
   AND2X1 g1065 (.Y(n_25),
	.B(FE_PHN21_n_52),
	.A(FE_OFN0_n_19));
   AND2X1 g1066 (.Y(n_24),
	.B(FE_PHN18_n_51),
	.A(FE_OFN0_n_19));
   AND2X1 g1067 (.Y(n_23),
	.B(FE_PHN30_n_50),
	.A(FE_OFN0_n_19));
   NOR2BX1 g1068 (.Y(n_22),
	.B(n_18),
	.AN(n_73));
   NOR2BX1 g1069 (.Y(n_21),
	.B(n_18),
	.AN(FE_PHN35_n_71));
   OR3X1 g1072 (.Y(n_19),
	.C(n_17),
	.B(FE_PHN11_cnt_9_),
	.A(FE_PHN33_n_1));
   OR4X1 g1073 (.Y(n_17),
	.D(n_16),
	.C(FE_PHN19_cnt_8_),
	.B(FE_PHN12_cnt_7_),
	.A(FE_PHN15_cnt_6_));
   NAND2X1 g1074 (.Y(n_16),
	.B(n_15),
	.A(FE_PHN13_cnt_5_));
   AND4XL g1075 (.Y(n_15),
	.D(n_14),
	.C(cnt[4]),
	.B(cnt[3]),
	.A(cnt[2]));
   NOR2XL g1076 (.Y(n_14),
	.B(n_13),
	.A(cnt[25]));
   NAND2X1 g1077 (.Y(n_13),
	.B(n_12),
	.A(cnt[24]));
   NOR2XL g1078 (.Y(n_12),
	.B(n_78),
	.A(cnt[23]));
   NAND2X1 g1081 (.Y(n_9),
	.B(n_8),
	.A(cnt[20]));
   AND4XL g1082 (.Y(n_8),
	.D(n_7),
	.C(cnt[19]),
	.B(cnt[18]),
	.A(cnt[1]));
   NOR2XL g1083 (.Y(n_7),
	.B(n_6),
	.A(cnt[17]));
   NAND2X1 g1084 (.Y(n_6),
	.B(n_5),
	.A(cnt[16]));
   NOR2XL g1085 (.Y(n_5),
	.B(n_79),
	.A(cnt[15]));
   NAND3BXL g1088 (.Y(n_2),
	.C(cnt[12]),
	.B(cnt[11]),
	.AN(cnt[10]));
   INVX2 drc1091 (.Y(n_18),
	.A(n_19));
   DFFRX2 \cnt_reg[0]  (.RN(FE_OFN1_n_46),
	.QN(n_1),
	.Q(cnt[0]),
	.D(FE_PHN33_n_1),
	.CK(clk_50mhz));
   NAND3BX1 g2 (.Y(n_78),
	.C(cnt[22]),
	.B(cnt[21]),
	.AN(n_9));
   NAND3BXL g1099 (.Y(n_79),
	.C(cnt[14]),
	.B(cnt[13]),
	.AN(n_2));
endmodule

module seg7dec (
	in, 
	out_hex);
   input [3:0] in;
   output [6:0] out_hex;

   // Internal wires
   wire FE_OFN4_seg1_ch_0_;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_17;
   wire n_18;

   BUFX6 FE_OFC4_seg1_ch_0_ (.Y(out_hex[0]),
	.A(FE_OFN4_seg1_ch_0_));
   OR2X6 g201 (.Y(out_hex[3]),
	.B(out_hex[0]),
	.A(n_10));
   OR2XL g202 (.Y(FE_OFN4_seg1_ch_0_),
	.B(n_17),
	.A(n_9));
   OR2X6 g203 (.Y(out_hex[1]),
	.B(n_13),
	.A(n_9));
   OR3X6 g204 (.Y(out_hex[6]),
	.C(n_10),
	.B(n_9),
	.A(n_12));
   AO21X1 g205 (.Y(n_18),
	.B0(n_14),
	.A1(n_4),
	.A0(in[1]));
   AO21X1 g206 (.Y(n_17),
	.B0(n_11),
	.A1(in[0]),
	.A0(n_12));
   OR2X6 g207 (.Y(out_hex[4]),
	.B(in[0]),
	.A(n_7));
   OR2X6 g208 (.Y(out_hex[2]),
	.B(n_8),
	.A(n_9));
   AO22XL g209 (.Y(n_14),
	.B1(in[2]),
	.B0(in[3]),
	.A1(in[0]),
	.A0(n_6));
   MXI2X1 g210 (.Y(n_13),
	.S0(in[1]),
	.B(n_4),
	.A(n_5));
   AND2X1 g211 (.Y(n_12),
	.B(n_3),
	.A(n_6));
   NOR2XL g212 (.Y(n_11),
	.B(n_4),
	.A(in[1]));
   NOR2X1 g213 (.Y(n_10),
	.B(n_5),
	.A(n_3));
   OA21X1 g214 (.Y(n_9),
	.B0(in[3]),
	.A1(in[1]),
	.A0(in[2]));
   NOR3X1 g215 (.Y(n_8),
	.C(in[0]),
	.B(n_3),
	.A(in[2]));
   MX2XL g216 (.Y(n_7),
	.S0(in[1]),
	.B(in[3]),
	.A(in[2]));
   NOR2XL g217 (.Y(n_6),
	.B(in[2]),
	.A(in[3]));
   NAND2X1 g218 (.Y(n_5),
	.B(in[0]),
	.A(in[2]));
   NAND2BX1 g219 (.Y(n_4),
	.B(in[2]),
	.AN(in[0]));
   INVX1 g220 (.Y(n_3),
	.A(in[1]));
   BUFX6 drc (.Y(out_hex[5]),
	.A(n_18));
endmodule

module seg7dec_31 (
	in, 
	out_hex);
   input [3:0] in;
   output [6:0] out_hex;

   // Internal wires
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_15;
   wire n_16;

   OR2X6 g201 (.Y(out_hex[3]),
	.B(out_hex[0]),
	.A(n_8));
   OR2X6 g202 (.Y(out_hex[0]),
	.B(n_15),
	.A(n_7));
   OR2X6 g203 (.Y(out_hex[1]),
	.B(n_11),
	.A(n_7));
   OR3X6 g204 (.Y(out_hex[6]),
	.C(n_10),
	.B(n_7),
	.A(n_8));
   AO21X1 g205 (.Y(n_16),
	.B0(n_12),
	.A1(n_2),
	.A0(in[1]));
   AO21X1 g206 (.Y(n_15),
	.B0(n_9),
	.A1(n_10),
	.A0(in[0]));
   OR2X6 g207 (.Y(out_hex[4]),
	.B(n_5),
	.A(in[0]));
   OR2X6 g208 (.Y(out_hex[2]),
	.B(n_7),
	.A(n_6));
   AO22XL g209 (.Y(n_12),
	.B1(in[2]),
	.B0(in[3]),
	.A1(n_4),
	.A0(in[0]));
   MXI2X1 g210 (.Y(n_11),
	.S0(in[1]),
	.B(n_2),
	.A(n_3));
   AND2X1 g211 (.Y(n_10),
	.B(n_4),
	.A(n_1));
   NOR2XL g212 (.Y(n_9),
	.B(n_2),
	.A(in[1]));
   NOR2X1 g213 (.Y(n_8),
	.B(n_3),
	.A(n_1));
   OA21X1 g214 (.Y(n_7),
	.B0(in[3]),
	.A1(in[1]),
	.A0(in[2]));
   NOR3X1 g215 (.Y(n_6),
	.C(n_1),
	.B(in[2]),
	.A(in[0]));
   MX2XL g216 (.Y(n_5),
	.S0(in[1]),
	.B(in[3]),
	.A(in[2]));
   NOR2XL g217 (.Y(n_4),
	.B(in[2]),
	.A(in[3]));
   NAND2X1 g218 (.Y(n_3),
	.B(in[2]),
	.A(in[0]));
   NAND2BX1 g219 (.Y(n_2),
	.B(in[2]),
	.AN(in[0]));
   INVX1 g220 (.Y(n_1),
	.A(in[1]));
   BUFX6 drc (.Y(out_hex[5]),
	.A(n_16));
endmodule

module sep2 (
	in, 
	ch, 
	dv);
   input [7:0] in;
   output [3:0] ch;
   output [3:0] dv;

   // Internal wires
   wire n_4;
   wire n_6;
   wire n_7;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;

   assign dv[0] = 1'b0 ;
   assign ch[3] = 1'b0 ;

   OR2X1 g1153 (.Y(dv[1]),
	.B(n_6),
	.A(n_7));
   OR3X1 g1154 (.Y(dv[2]),
	.C(n_54),
	.B(n_45),
	.A(n_44));
   OR2X1 g1155 (.Y(dv[3]),
	.B(n_48),
	.A(n_53));
   OAI22XL g1156 (.Y(n_7),
	.B1(n_30),
	.B0(n_29),
	.A1(n_52),
	.A0(in[1]));
   AO22XL g1157 (.Y(n_54),
	.B1(in[6]),
	.B0(n_22),
	.A1(n_51),
	.A0(in[1]));
   OAI2BB1X1 g1159 (.Y(n_53),
	.B0(n_50),
	.A1N(in[6]),
	.A0N(n_33));
   NOR2XL g1161 (.Y(n_52),
	.B(n_46),
	.A(in[6]));
   NAND2BX1 g1162 (.Y(n_51),
	.B(n_34),
	.AN(n_47));
   AOI22X1 g1163 (.Y(n_50),
	.B1(n_36),
	.B0(n_22),
	.A1(n_42),
	.A0(n_20));
   AO21X1 g1164 (.Y(ch[1]),
	.B0(n_37),
	.A1(n_35),
	.A0(n_15));
   AND4XL g1165 (.Y(n_6),
	.D(n_32),
	.C(n_16),
	.B(n_15),
	.A(in[1]));
   OAI22XL g1166 (.Y(n_48),
	.B1(n_40),
	.B0(in[1]),
	.A1(n_38),
	.A0(n_29));
   AO22XL g1167 (.Y(n_47),
	.B1(n_20),
	.B0(n_25),
	.A1(n_37),
	.A0(n_13));
   AO21X1 g1168 (.Y(n_46),
	.B0(n_41),
	.A1(n_20),
	.A0(n_16));
   AOI21XL g1169 (.Y(n_45),
	.B0(n_16),
	.A1(n_30),
	.A0(n_28));
   AND4XL g1170 (.Y(n_44),
	.D(n_18),
	.C(n_19),
	.B(n_15),
	.A(n_14));
   OAI22XL g1171 (.Y(n_43),
	.B1(n_29),
	.B0(in[3]),
	.A1(n_27),
	.A0(n_14));
   AO22XL g1172 (.Y(n_42),
	.B1(n_19),
	.B0(in[1]),
	.A1(n_31),
	.A0(n_15));
   AO22XL g1173 (.Y(n_41),
	.B1(n_17),
	.B0(n_19),
	.A1(n_32),
	.A0(n_4));
   NAND2BX1 g1174 (.Y(n_40),
	.B(n_25),
	.AN(n_30));
   AND2X1 g1175 (.Y(ch[2]),
	.B(n_26),
	.A(n_15));
   AOI2BB1X1 g1176 (.Y(n_38),
	.B0(n_24),
	.A1N(n_23),
	.A0N(in[6]));
   AND3XL g1177 (.Y(n_37),
	.C(n_20),
	.B(n_15),
	.A(n_12));
   AO22XL g1178 (.Y(n_36),
	.B1(in[6]),
	.B0(in[3]),
	.A1(n_17),
	.A0(n_12));
   AO22XL g1179 (.Y(n_35),
	.B1(n_17),
	.B0(in[4]),
	.A1(n_21),
	.A0(n_25));
   AOI22X1 g1180 (.Y(n_34),
	.B1(in[6]),
	.B0(in[2]),
	.A1(n_21),
	.A0(n_19));
   NOR2XL g1181 (.Y(n_33),
	.B(in[3]),
	.A(n_22));
   NAND2BX1 g1182 (.Y(n_32),
	.B(n_23),
	.AN(n_24));
   NOR2XL g1183 (.Y(n_31),
	.B(n_16),
	.A(in[1]));
   OR2X1 g1184 (.Y(n_30),
	.B(n_18),
	.A(in[6]));
   OR2X1 g1185 (.Y(n_29),
	.B(n_16),
	.A(n_14));
   NAND2X1 g1186 (.Y(n_28),
	.B(n_21),
	.A(n_14));
   NAND2X1 g1187 (.Y(n_27),
	.B(n_17),
	.A(n_16));
   OAI2BB1X1 g1188 (.Y(n_26),
	.B0(n_23),
	.A1N(in[5]),
	.A0N(in[4]));
   AND2X1 g1189 (.Y(n_25),
	.B(in[4]),
	.A(in[2]));
   NOR2XL g1190 (.Y(n_24),
	.B(in[5]),
	.A(in[3]));
   NAND2X1 g1191 (.Y(n_23),
	.B(in[5]),
	.A(in[3]));
   AND2X1 g1192 (.Y(n_22),
	.B(n_14),
	.A(n_13));
   INVX1 g1193 (.Y(n_20),
	.A(n_21));
   OR2X1 g1194 (.Y(n_21),
	.B(n_11),
	.A(in[3]));
   AND2X1 g1195 (.Y(n_19),
	.B(n_12),
	.A(in[2]));
   NAND2X1 g1197 (.Y(n_18),
	.B(n_11),
	.A(in[3]));
   OR2X1 g1199 (.Y(n_16),
	.B(n_12),
	.A(in[2]));
   INVX1 g1200 (.Y(n_15),
	.A(in[6]));
   INVX1 g1201 (.Y(n_14),
	.A(in[1]));
   INVX1 g1202 (.Y(n_13),
	.A(in[2]));
   INVX1 g1203 (.Y(n_12),
	.A(in[4]));
   INVX1 g1204 (.Y(n_11),
	.A(in[5]));
   INVX1 drc1218 (.Y(n_17),
	.A(n_18));
   INVX1 drc1232 (.Y(n_4),
	.A(n_16));
   NAND2BX1 g2 (.Y(ch[0]),
	.B(n_52),
	.AN(n_43));
endmodule

module display_2digit (
	in, 
	seg_ch, 
	seg_dv);
   input [7:0] in;
   output [6:0] seg_ch;
   output [6:0] seg_dv;

   // Internal wires
   wire FE_OFN2_t_ch_0_;
   wire [3:0] t_ch;
   wire [3:0] t_dv;
   wire UNCONNECTED0;
   wire UNCONNECTED1;

   CLKBUFX2 FE_OFC2_t_ch_0_ (.Y(FE_OFN2_t_ch_0_),
	.A(t_ch[0]));
   seg7dec u_ch (.in({ in[6],
		t_ch[2],
		t_ch[1],
		FE_OFN2_t_ch_0_ }),
	.out_hex(seg_ch));
   seg7dec_31 u_dv (.in({ t_dv[3],
		t_dv[2],
		t_dv[1],
		in[0] }),
	.out_hex(seg_dv));
   sep2 u_sep2 (.in({ 1'b0,
		in[6],
		in[5],
		in[4],
		in[3],
		in[2],
		in[1],
		1'b0 }),
	.ch({ UNCONNECTED0,
		t_ch[2],
		t_ch[1],
		t_ch[0] }),
	.dv({ t_dv[3],
		t_dv[2],
		t_dv[1],
		UNCONNECTED1 }));
endmodule

module seg7dec_30 (
	in, 
	out_hex);
   input [3:0] in;
   output [6:0] out_hex;

   // Internal wires
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_17;
   wire n_18;

   OR2X6 g201 (.Y(out_hex[3]),
	.B(out_hex[0]),
	.A(n_10));
   OR2X6 g202 (.Y(out_hex[0]),
	.B(n_17),
	.A(n_9));
   OR2X6 g203 (.Y(out_hex[1]),
	.B(n_13),
	.A(n_9));
   OR3X6 g204 (.Y(out_hex[6]),
	.C(n_10),
	.B(n_9),
	.A(n_12));
   AO21X1 g205 (.Y(n_18),
	.B0(n_14),
	.A1(n_4),
	.A0(in[1]));
   AO21X1 g206 (.Y(n_17),
	.B0(n_11),
	.A1(in[0]),
	.A0(n_12));
   OR2X6 g207 (.Y(out_hex[4]),
	.B(in[0]),
	.A(n_7));
   OR2X6 g208 (.Y(out_hex[2]),
	.B(n_8),
	.A(n_9));
   AO22XL g209 (.Y(n_14),
	.B1(in[2]),
	.B0(in[3]),
	.A1(in[0]),
	.A0(n_6));
   MXI2X1 g210 (.Y(n_13),
	.S0(in[1]),
	.B(n_4),
	.A(n_5));
   AND2X1 g211 (.Y(n_12),
	.B(n_3),
	.A(n_6));
   NOR2XL g212 (.Y(n_11),
	.B(n_4),
	.A(in[1]));
   NOR2X1 g213 (.Y(n_10),
	.B(n_5),
	.A(n_3));
   OA21X1 g214 (.Y(n_9),
	.B0(in[3]),
	.A1(in[1]),
	.A0(in[2]));
   NOR3X1 g215 (.Y(n_8),
	.C(in[0]),
	.B(n_3),
	.A(in[2]));
   MX2XL g216 (.Y(n_7),
	.S0(in[1]),
	.B(in[3]),
	.A(in[2]));
   NOR2XL g217 (.Y(n_6),
	.B(in[2]),
	.A(in[3]));
   NAND2X1 g218 (.Y(n_5),
	.B(in[0]),
	.A(in[2]));
   NAND2BX1 g219 (.Y(n_4),
	.B(in[2]),
	.AN(in[0]));
   INVX1 g220 (.Y(n_3),
	.A(in[1]));
   BUFX6 drc (.Y(out_hex[5]),
	.A(n_18));
endmodule

module seg7dec_29 (
	in, 
	out_hex);
   input [3:0] in;
   output [6:0] out_hex;

   // Internal wires
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_15;
   wire n_16;

   OR2X6 g201 (.Y(out_hex[3]),
	.B(out_hex[0]),
	.A(n_8));
   OR2X6 g202 (.Y(out_hex[0]),
	.B(n_15),
	.A(n_7));
   OR2X6 g203 (.Y(out_hex[1]),
	.B(n_11),
	.A(n_7));
   OR3X6 g204 (.Y(out_hex[6]),
	.C(n_10),
	.B(n_7),
	.A(n_8));
   AO21X1 g205 (.Y(n_16),
	.B0(n_12),
	.A1(n_2),
	.A0(in[1]));
   AO21X1 g206 (.Y(n_15),
	.B0(n_9),
	.A1(n_10),
	.A0(in[0]));
   OR2X6 g207 (.Y(out_hex[4]),
	.B(n_5),
	.A(in[0]));
   OR2X6 g208 (.Y(out_hex[2]),
	.B(n_7),
	.A(n_6));
   AO22XL g209 (.Y(n_12),
	.B1(in[2]),
	.B0(in[3]),
	.A1(n_4),
	.A0(in[0]));
   MXI2X1 g210 (.Y(n_11),
	.S0(in[1]),
	.B(n_2),
	.A(n_3));
   AND2X1 g211 (.Y(n_10),
	.B(n_4),
	.A(n_1));
   NOR2XL g212 (.Y(n_9),
	.B(n_2),
	.A(in[1]));
   NOR2X1 g213 (.Y(n_8),
	.B(n_3),
	.A(n_1));
   OA21X1 g214 (.Y(n_7),
	.B0(in[3]),
	.A1(in[1]),
	.A0(in[2]));
   NOR3X1 g215 (.Y(n_6),
	.C(n_1),
	.B(in[2]),
	.A(in[0]));
   MX2XL g216 (.Y(n_5),
	.S0(in[1]),
	.B(in[3]),
	.A(in[2]));
   NOR2XL g217 (.Y(n_4),
	.B(in[2]),
	.A(in[3]));
   NAND2X1 g218 (.Y(n_3),
	.B(in[2]),
	.A(in[0]));
   NAND2BX1 g219 (.Y(n_2),
	.B(in[2]),
	.AN(in[0]));
   INVX1 g220 (.Y(n_1),
	.A(in[1]));
   BUFX6 drc (.Y(out_hex[5]),
	.A(n_16));
endmodule

module sep2_32 (
	in, 
	ch, 
	dv);
   input [7:0] in;
   output [3:0] ch;
   output [3:0] dv;

   // Internal wires
   wire n_4;
   wire n_6;
   wire n_7;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;

   assign dv[0] = 1'b0 ;
   assign ch[3] = 1'b0 ;

   OR2X1 g1153 (.Y(dv[1]),
	.B(n_6),
	.A(n_7));
   OR3X1 g1154 (.Y(dv[2]),
	.C(n_54),
	.B(n_45),
	.A(n_44));
   OR2X1 g1155 (.Y(dv[3]),
	.B(n_48),
	.A(n_53));
   OAI22XL g1156 (.Y(n_7),
	.B1(n_30),
	.B0(n_29),
	.A1(n_52),
	.A0(in[1]));
   AO22XL g1157 (.Y(n_54),
	.B1(in[6]),
	.B0(n_22),
	.A1(n_51),
	.A0(in[1]));
   OAI2BB1X1 g1159 (.Y(n_53),
	.B0(n_50),
	.A1N(in[6]),
	.A0N(n_33));
   NOR2XL g1161 (.Y(n_52),
	.B(n_46),
	.A(in[6]));
   NAND2BX1 g1162 (.Y(n_51),
	.B(n_34),
	.AN(n_47));
   AOI22X1 g1163 (.Y(n_50),
	.B1(n_36),
	.B0(n_22),
	.A1(n_42),
	.A0(n_20));
   AO21X1 g1164 (.Y(ch[1]),
	.B0(n_37),
	.A1(n_35),
	.A0(n_15));
   AND4XL g1165 (.Y(n_6),
	.D(n_32),
	.C(n_16),
	.B(n_15),
	.A(in[1]));
   OAI22XL g1166 (.Y(n_48),
	.B1(n_40),
	.B0(in[1]),
	.A1(n_38),
	.A0(n_29));
   AO22XL g1167 (.Y(n_47),
	.B1(n_20),
	.B0(n_25),
	.A1(n_37),
	.A0(n_13));
   AO21X1 g1168 (.Y(n_46),
	.B0(n_41),
	.A1(n_20),
	.A0(n_16));
   AOI21XL g1169 (.Y(n_45),
	.B0(n_16),
	.A1(n_30),
	.A0(n_28));
   AND4XL g1170 (.Y(n_44),
	.D(n_18),
	.C(n_19),
	.B(n_15),
	.A(n_14));
   OAI22XL g1171 (.Y(n_43),
	.B1(n_29),
	.B0(in[3]),
	.A1(n_27),
	.A0(n_14));
   AO22XL g1172 (.Y(n_42),
	.B1(n_19),
	.B0(in[1]),
	.A1(n_31),
	.A0(n_15));
   AO22XL g1173 (.Y(n_41),
	.B1(n_17),
	.B0(n_19),
	.A1(n_32),
	.A0(n_4));
   NAND2BX1 g1174 (.Y(n_40),
	.B(n_25),
	.AN(n_30));
   AND2X1 g1175 (.Y(ch[2]),
	.B(n_26),
	.A(n_15));
   AOI2BB1X1 g1176 (.Y(n_38),
	.B0(n_24),
	.A1N(n_23),
	.A0N(in[6]));
   AND3XL g1177 (.Y(n_37),
	.C(n_20),
	.B(n_15),
	.A(n_12));
   AO22XL g1178 (.Y(n_36),
	.B1(in[6]),
	.B0(in[3]),
	.A1(n_17),
	.A0(n_12));
   AO22XL g1179 (.Y(n_35),
	.B1(n_17),
	.B0(in[4]),
	.A1(n_21),
	.A0(n_25));
   AOI22X1 g1180 (.Y(n_34),
	.B1(in[6]),
	.B0(in[2]),
	.A1(n_21),
	.A0(n_19));
   NOR2XL g1181 (.Y(n_33),
	.B(in[3]),
	.A(n_22));
   NAND2BX1 g1182 (.Y(n_32),
	.B(n_23),
	.AN(n_24));
   NOR2XL g1183 (.Y(n_31),
	.B(n_16),
	.A(in[1]));
   OR2X1 g1184 (.Y(n_30),
	.B(n_18),
	.A(in[6]));
   OR2X1 g1185 (.Y(n_29),
	.B(n_16),
	.A(n_14));
   NAND2X1 g1186 (.Y(n_28),
	.B(n_21),
	.A(n_14));
   NAND2X1 g1187 (.Y(n_27),
	.B(n_17),
	.A(n_16));
   OAI2BB1X1 g1188 (.Y(n_26),
	.B0(n_23),
	.A1N(in[5]),
	.A0N(in[4]));
   AND2X1 g1189 (.Y(n_25),
	.B(in[4]),
	.A(in[2]));
   NOR2XL g1190 (.Y(n_24),
	.B(in[5]),
	.A(in[3]));
   NAND2X1 g1191 (.Y(n_23),
	.B(in[5]),
	.A(in[3]));
   AND2X1 g1192 (.Y(n_22),
	.B(n_14),
	.A(n_13));
   INVX1 g1193 (.Y(n_20),
	.A(n_21));
   OR2X1 g1194 (.Y(n_21),
	.B(n_11),
	.A(in[3]));
   AND2X1 g1195 (.Y(n_19),
	.B(n_12),
	.A(in[2]));
   NAND2X1 g1197 (.Y(n_18),
	.B(n_11),
	.A(in[3]));
   OR2X1 g1199 (.Y(n_16),
	.B(n_12),
	.A(in[2]));
   INVX1 g1200 (.Y(n_15),
	.A(in[6]));
   INVX1 g1201 (.Y(n_14),
	.A(in[1]));
   INVX1 g1202 (.Y(n_13),
	.A(in[2]));
   INVX1 g1203 (.Y(n_12),
	.A(in[4]));
   INVX1 g1204 (.Y(n_11),
	.A(in[5]));
   INVX1 drc1218 (.Y(n_17),
	.A(n_18));
   INVX1 drc1232 (.Y(n_4),
	.A(n_16));
   NAND2BX1 g2 (.Y(ch[0]),
	.B(n_52),
	.AN(n_43));
endmodule

module display_2digit_14 (
	in, 
	seg_ch, 
	seg_dv);
   input [7:0] in;
   output [6:0] seg_ch;
   output [6:0] seg_dv;

   // Internal wires
   wire FE_OFN3_t_ch_0_;
   wire [3:0] t_ch;
   wire [3:0] t_dv;
   wire UNCONNECTED2;
   wire UNCONNECTED3;

   CLKBUFX2 FE_OFC3_t_ch_0_ (.Y(FE_OFN3_t_ch_0_),
	.A(t_ch[0]));
   seg7dec_30 u_ch (.in({ in[6],
		t_ch[2],
		t_ch[1],
		FE_OFN3_t_ch_0_ }),
	.out_hex(seg_ch));
   seg7dec_29 u_dv (.in({ t_dv[3],
		t_dv[2],
		t_dv[1],
		in[0] }),
	.out_hex(seg_dv));
   sep2_32 u_sep2 (.in({ 1'b0,
		in[6],
		in[5],
		in[4],
		in[3],
		in[2],
		in[1],
		1'b0 }),
	.ch({ UNCONNECTED2,
		t_ch[2],
		t_ch[1],
		t_ch[0] }),
	.dv({ t_dv[3],
		t_dv[2],
		t_dv[1],
		UNCONNECTED3 }));
endmodule

module display_2digit_cross (
	in_A, 
	in_B, 
	seg_ch_A, 
	seg_dv_A, 
	seg_ch_B, 
	seg_dv_B);
   input [7:0] in_A;
   input [7:0] in_B;
   output [6:0] seg_ch_A;
   output [6:0] seg_dv_A;
   output [6:0] seg_ch_B;
   output [6:0] seg_dv_B;

   display_2digit u_A (.in({ 1'b0,
		in_A[6],
		in_A[5],
		in_A[4],
		in_A[3],
		in_A[2],
		in_A[1],
		in_A[0] }),
	.seg_ch(seg_ch_A),
	.seg_dv(seg_dv_A));
   display_2digit_14 u_B (.in({ 1'b0,
		in_B[6],
		in_B[5],
		in_B[4],
		in_B[3],
		in_B[2],
		in_B[1],
		in_B[0] }),
	.seg_ch(seg_ch_B),
	.seg_dv(seg_dv_B));
endmodule

module fsm (
	clk, 
	rst, 
	LED_1, 
	LED_2, 
	time1, 
	time2, 
	FE_PT1_LED_2_2_);
   input clk;
   input rst;
   output [2:0] LED_1;
   output [2:0] LED_2;
   output [8:0] time1;
   output [8:0] time2;
   input FE_PT1_LED_2_2_;

   // Internal wires
   wire FE_UNCONNECTED_0;
   wire [8:0] timer;
   wire [1:0] state;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_26;
   wire n_27;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_72;
   wire n_74;
   wire n_92;
   wire n_93;
   wire n_1072_BAR;

   assign time2[6] = 1'b0 ;
   assign time2[8] = 1'b0 ;
   assign time1[6] = 1'b0 ;
   assign time1[8] = 1'b0 ;
   assign LED_2[2] = 1'b0 ;

   OR3X1 g1553 (.Y(time1[5]),
	.C(n_65),
	.B(n_66),
	.A(n_57));
   OR3X1 g1554 (.Y(time2[5]),
	.C(n_63),
	.B(n_64),
	.A(n_57));
   OR2X2 g1555 (.Y(time2[7]),
	.B(n_64),
	.A(n_24));
   OR2X2 g1556 (.Y(time1[7]),
	.B(n_66),
	.A(n_24));
   AND2X1 g1557 (.Y(n_66),
	.B(n_62),
	.A(timer[5]));
   NOR2XL g1558 (.Y(n_65),
	.B(n_60),
	.A(timer[5]));
   AND2X1 g1559 (.Y(n_64),
	.B(n_61),
	.A(timer[5]));
   NOR2XL g1560 (.Y(n_63),
	.B(n_59),
	.A(timer[5]));
   OR2X1 g1561 (.Y(time2[4]),
	.B(n_58),
	.A(n_55));
   AO21X1 g1562 (.Y(time1[4]),
	.B0(n_56),
	.A1(n_52),
	.A0(LED_1[0]));
   OAI22XL g1563 (.Y(n_62),
	.B1(n_49),
	.B0(n_31),
	.A1(n_51),
	.A0(n_33));
   OAI22XL g1564 (.Y(n_61),
	.B1(n_49),
	.B0(n_33),
	.A1(n_51),
	.A0(n_31));
   AOI22X1 g1565 (.Y(n_60),
	.B1(n_49),
	.B0(n_32),
	.A1(n_51),
	.A0(LED_1[0]));
   AOI22X1 g1566 (.Y(n_59),
	.B1(n_49),
	.B0(LED_1[0]),
	.A1(n_51),
	.A0(n_32));
   AO22XL g1567 (.Y(n_58),
	.B1(n_50),
	.B0(LED_1[0]),
	.A1(n_52),
	.A0(n_32));
   OR2X1 g1568 (.Y(time2[3]),
	.B(n_53),
	.A(n_44));
   OR2X1 g1569 (.Y(time1[3]),
	.B(n_54),
	.A(n_44));
   OA21X1 g1570 (.Y(n_57),
	.B0(n_24),
	.A1(n_47),
	.A0(n_93));
   AO21X1 g1571 (.Y(n_56),
	.B0(n_55),
	.A1(n_50),
	.A0(n_32));
   AND2X1 g1572 (.Y(n_55),
	.B(n_48),
	.A(state[0]));
   OAI22XL g1573 (.Y(n_54),
	.B1(n_42),
	.B0(n_31),
	.A1(n_45),
	.A0(n_33));
   OAI22XL g1574 (.Y(n_53),
	.B1(n_42),
	.B0(n_33),
	.A1(n_45),
	.A0(n_31));
   ADDHXL g1575 (.S(n_52),
	.CO(n_51),
	.B(n_43),
	.A(n_67));
   ADDHXL g1576 (.S(n_50),
	.CO(n_49),
	.B(n_38),
	.A(n_67));
   ADDHXL g1577 (.S(n_48),
	.CO(n_47),
	.B(n_41),
	.A(n_67));
   AOI21X1 g1578 (.Y(n_24),
	.B0(n_72),
	.A1(n_41),
	.A0(n_68));
   AND2X1 g1579 (.Y(n_45),
	.B(n_43),
	.A(n_39));
   CLKMX2X2 g1580 (.Y(time1[2]),
	.S0(n_33),
	.B(n_34),
	.A(n_40));
   MX2XL g1581 (.Y(time2[2]),
	.S0(n_31),
	.B(n_34),
	.A(n_40));
   AND2X1 g1582 (.Y(n_44),
	.B(n_42),
	.A(state[0]));
   AO21X1 g1583 (.Y(n_43),
	.B0(n_92),
	.A1(n_37),
	.A0(n_26));
   ADDHXL g1584 (.S(n_42),
	.CO(n_41),
	.B(n_30),
	.A(n_92));
   XOR2X1 g1585 (.Y(time1[1]),
	.B(n_35),
	.A(timer[1]));
   XOR2X1 g1586 (.Y(time2[1]),
	.B(n_36),
	.A(timer[1]));
   XNOR2X1 g1587 (.Y(n_40),
	.B(n_37),
	.A(timer[2]));
   NAND2X1 g1588 (.Y(n_39),
	.B(n_37),
	.A(n_69));
   OR2X1 g1589 (.Y(n_38),
	.B(n_30),
	.A(n_92));
   AO21X1 g1590 (.Y(time2[0]),
	.B0(n_36),
	.A1(n_31),
	.A0(n_74));
   AO21X1 g1591 (.Y(time1[0]),
	.B0(n_35),
	.A1(n_33),
	.A0(n_74));
   ADDHXL g1592 (.S(n_70),
	.CO(n_37),
	.B(n_27),
	.A(n_74));
   AND2X1 g1593 (.Y(n_36),
	.B(n_32),
	.A(timer[0]));
   AND2X1 g1594 (.Y(n_35),
	.B(LED_1[0]),
	.A(timer[0]));
   AO21X1 g1595 (.Y(n_34),
	.B0(n_29),
	.A1(n_27),
	.A0(n_26));
   INVX1 g1596 (.Y(n_33),
	.A(LED_1[0]));
   AND2X6 g1597 (.Y(LED_1[0]),
	.B(n_72),
	.A(FE_PT1_LED_2_2_));
   AND2X6 g1598 (.Y(LED_2[1]),
	.B(state[0]),
	.A(LED_1[2]));
   NAND2X1 g1599 (.Y(n_1072_BAR),
	.B(timer[2]),
	.A(timer[3]));
   AND2X1 g1600 (.Y(n_69),
	.B(n_92),
	.A(n_26));
   AND2X1 g1601 (.Y(n_68),
	.B(n_67),
	.A(n_93));
   INVX1 g1602 (.Y(n_31),
	.A(n_32));
   AND2X1 g1603 (.Y(n_32),
	.B(n_72),
	.A(LED_1[2]));
   AND2X6 g1604 (.Y(LED_1[1]),
	.B(FE_PT1_LED_2_2_),
	.A(state[0]));
   INVX1 g1605 (.Y(n_30),
	.A(n_29));
   AND2X1 g1606 (.Y(n_29),
	.B(timer[1]),
	.A(timer[2]));
   BUFX6 drc1619 (.Y(LED_2[0]),
	.A(n_32));
   AND2X1 g651 (.Y(n_23),
	.B(n_16),
	.A(n_74));
   AND2X1 g652 (.Y(n_22),
	.B(n_16),
	.A(n_8));
   AND2X1 g653 (.Y(n_21),
	.B(n_16),
	.A(n_70));
   AND2X1 g654 (.Y(n_20),
	.B(n_16),
	.A(n_13));
   AND2X1 g655 (.Y(n_19),
	.B(n_16),
	.A(n_10));
   AND2X1 g656 (.Y(n_18),
	.B(n_16),
	.A(n_12));
   OAI21XL g657 (.Y(n_17),
	.B0(n_7),
	.A1(n_15),
	.A0(state[0]));
   CLKMX2X2 g658 (.Y(n_16),
	.S0(state[0]),
	.B(n_3),
	.A(n_15));
   OA21X1 g659 (.Y(n_15),
	.B0(n_14),
	.A1(n_67),
	.A0(n_93));
   OAI2BB1X1 g660 (.Y(n_14),
	.B0(timer[5]),
	.A1N(n_4),
	.A0N(n_92));
   XNOR2X1 g661 (.Y(n_13),
	.B(n_4),
	.A(timer[3]));
   DFFRHQX8 \state_reg[1]  (.RN(n_1),
	.Q(LED_1[2]),
	.D(n_11),
	.CK(clk));
   XNOR2X1 g663 (.Y(n_12),
	.B(n_9),
	.A(timer[5]));
   XNOR2X1 g664 (.Y(n_11),
	.B(n_6),
	.A(LED_1[2]));
   CLKXOR2X1 g665 (.Y(n_10),
	.B(n_5),
	.A(timer[4]));
   NAND2BX1 g666 (.Y(n_9),
	.B(n_5),
	.AN(n_67));
   XNOR2X1 g667 (.Y(n_8),
	.B(n_2),
	.A(timer[2]));
   NAND2X1 g668 (.Y(n_7),
	.B(n_3),
	.A(state[0]));
   OR2X1 g669 (.Y(n_6),
	.B(n_3),
	.A(n_72));
   NOR2X1 g670 (.Y(n_5),
	.B(n_2),
	.A(n_1072_BAR));
   NAND2BX1 g671 (.Y(n_4),
	.B(timer[2]),
	.AN(n_2));
   AND2X1 g672 (.Y(n_3),
	.B(n_69),
	.A(n_68));
   NAND2X1 g673 (.Y(n_2),
	.B(timer[0]),
	.A(timer[1]));
   INVX2 g674 (.Y(n_1),
	.A(rst));
   DFFRX2 \timer_reg[4]  (.RN(n_1),
	.QN(n_67),
	.Q(timer[4]),
	.D(n_19),
	.CK(clk));
   DFFRX2 \state_reg[0]  (.RN(n_1),
	.QN(n_72),
	.Q(state[0]),
	.D(n_17),
	.CK(clk));
   DFFRX2 \timer_reg[0]  (.RN(n_1),
	.QN(n_74),
	.Q(timer[0]),
	.D(n_23),
	.CK(clk));
   DFFRX2 \timer_reg[1]  (.RN(n_1),
	.QN(n_27),
	.Q(timer[1]),
	.D(n_21),
	.CK(clk));
   DFFRX2 \timer_reg[2]  (.RN(n_1),
	.QN(n_26),
	.Q(timer[2]),
	.D(n_22),
	.CK(clk));
   DFFRX2 \timer_reg[5]  (.RN(n_1),
	.QN(n_93),
	.Q(timer[5]),
	.D(n_18),
	.CK(clk));
   DFFRX2 \timer_reg[3]  (.RN(n_1),
	.QN(n_92),
	.Q(timer[3]),
	.D(n_20),
	.CK(clk));
endmodule

module top_module (
	clk_50mhz, 
	rst, 
	LED_1, 
	LED_2, 
	seg1_ch, 
	seg1_dv, 
	seg2_ch, 
	seg2_dv);
   input clk_50mhz;
   input rst;
   output [2:0] LED_1;
   output [2:0] LED_2;
   output [6:0] seg1_ch;
   output [6:0] seg1_dv;
   output [6:0] seg2_ch;
   output [6:0] seg2_dv;

   // Internal wires
   wire clk_50mhz__L2_N0;
   wire clk_50mhz__L1_N0;
   wire [8:0] time1;
   wire [8:0] time2;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire clk_1hz;

   INVX20 clk_50mhz__L2_I0 (.Y(clk_50mhz__L2_N0),
	.A(clk_50mhz__L1_N0));
   INVX20 clk_50mhz__L1_I0 (.Y(clk_50mhz__L1_N0),
	.A(clk_50mhz));
   clk_1hz u_clk (.clk_50mhz(clk_50mhz__L2_N0),
	.rst(rst),
	.clk_1hz(clk_1hz));
   display_2digit_cross u_disp (.in_A({ 1'b0,
		time1[7],
		time1[5],
		time1[4],
		time1[3],
		time1[2],
		time1[1],
		time1[0] }),
	.in_B({ 1'b0,
		time2[7],
		time2[5],
		time2[4],
		time2[3],
		time2[2],
		time2[1],
		time2[0] }),
	.seg_ch_A(seg1_ch),
	.seg_dv_A(seg1_dv),
	.seg_ch_B(seg2_ch),
	.seg_dv_B(seg2_dv));
   fsm u_fsm (.clk(clk_1hz),
	.rst(rst),
	.LED_1(LED_1),
	.LED_2({ UNCONNECTED4,
		LED_2[1],
		LED_2[0] }),
	.time1({ UNCONNECTED5,
		time1[7],
		UNCONNECTED6,
		time1[5],
		time1[4],
		time1[3],
		time1[2],
		time1[1],
		time1[0] }),
	.time2({ UNCONNECTED7,
		time2[7],
		UNCONNECTED8,
		time2[5],
		time2[4],
		time2[3],
		time2[2],
		time2[1],
		time2[0] }),
	.FE_PT1_LED_2_2_(LED_2[2]));
   INVX6 g2 (.Y(LED_2[2]),
	.A(LED_1[2]));
endmodule

