###############################################################
#  Generated by:      Cadence Encounter 13.10-p003_1
#  OS:                Linux i686(Host ID cadence)
#  Generated on:      Fri Sep  4 09:03:41 2026
#  Design:            top_module
#  Command:           saveIoFile -locations ouput/ouput_final/top_module_loc...
###############################################################

(globals
    version = 3
    io_order = default
)
(iopin
    (left
	(pin name="clk_50mhz"	offset=28.9750 layer=3 width=0.2000 depth=2.0000 )
	(pin name="rst"	offset=37.5250 layer=3 width=0.2000 depth=2.0000 )
    )
    (right
	(pin name="seg1_ch[0]"	offset=2.1850 layer=3 width=0.2000 depth=2.0000 )
	(pin name="LED_2[2]"	offset=3.5150 layer=3 width=0.2000 depth=2.0000 )
	(pin name="LED_2[1]"	offset=5.0350 layer=3 width=0.2000 depth=2.0000 )
	(pin name="LED_2[0]"	offset=6.5550 layer=3 width=0.2000 depth=2.0000 )
	(pin name="LED_1[2]"	offset=7.8850 layer=3 width=0.2000 depth=2.0000 )
	(pin name="LED_1[1]"	offset=9.4050 layer=3 width=0.2000 depth=2.0000 )
	(pin name="LED_1[0]"	offset=10.7350 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_dv[6]"	offset=18.1450 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_dv[5]"	offset=19.2850 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_dv[4]"	offset=20.4250 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_dv[3]"	offset=21.5650 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_dv[2]"	offset=22.8950 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_dv[1]"	offset=24.2250 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_dv[0]"	offset=25.5550 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_ch[6]"	offset=26.8850 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_ch[5]"	offset=28.2150 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_ch[4]"	offset=29.5450 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_ch[3]"	offset=30.8750 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_ch[2]"	offset=32.2050 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_ch[1]"	offset=33.5350 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_ch[0]"	offset=34.8650 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_dv[6]"	offset=36.1950 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_dv[5]"	offset=37.5250 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_dv[4]"	offset=38.6650 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_dv[3]"	offset=40.1850 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_dv[2]"	offset=41.7050 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_dv[1]"	offset=43.0350 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_dv[0]"	offset=44.5550 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_ch[6]"	offset=45.8850 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_ch[5]"	offset=47.4050 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_ch[4]"	offset=48.9250 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_ch[3]"	offset=50.4450 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_ch[2]"	offset=51.7750 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_ch[1]"	offset=53.2950 layer=3 width=0.2000 depth=2.0000 )
    )
)
