###############################################################
#  Generated by:      Cadence Encounter 13.10-p003_1
#  OS:                Linux i686(Host ID cadence)
#  Generated on:      Fri Sep  4 09:26:29 2026
#  Design:            top_module
#  Command:           saveFPlan ouput/ouput_final/top_module.fp
###############################################################

Version: 8

Head Box: 0.0000 0.0000 61.9000 59.4000
IO Box: 0.0000 0.0000 61.9000 59.4000
Core Box: 10.0000 10.0700 51.9000 49.4000
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: CoreSite 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 CoreSite 10.0000 10.0700 FS 209 1 0.2000 0.0000
DefRow: ROW_1 CoreSite 10.0000 11.7800 N 209 1 0.2000 0.0000
DefRow: ROW_2 CoreSite 10.0000 13.4900 FS 209 1 0.2000 0.0000
DefRow: ROW_3 CoreSite 10.0000 15.2000 N 209 1 0.2000 0.0000
DefRow: ROW_4 CoreSite 10.0000 16.9100 FS 209 1 0.2000 0.0000
DefRow: ROW_5 CoreSite 10.0000 18.6200 N 209 1 0.2000 0.0000
DefRow: ROW_6 CoreSite 10.0000 20.3300 FS 209 1 0.2000 0.0000
DefRow: ROW_7 CoreSite 10.0000 22.0400 N 209 1 0.2000 0.0000
DefRow: ROW_8 CoreSite 10.0000 23.7500 FS 209 1 0.2000 0.0000
DefRow: ROW_9 CoreSite 10.0000 25.4600 N 209 1 0.2000 0.0000
DefRow: ROW_10 CoreSite 10.0000 27.1700 FS 209 1 0.2000 0.0000
DefRow: ROW_11 CoreSite 10.0000 28.8800 N 209 1 0.2000 0.0000
DefRow: ROW_12 CoreSite 10.0000 30.5900 FS 209 1 0.2000 0.0000
DefRow: ROW_13 CoreSite 10.0000 32.3000 N 209 1 0.2000 0.0000
DefRow: ROW_14 CoreSite 10.0000 34.0100 FS 209 1 0.2000 0.0000
DefRow: ROW_15 CoreSite 10.0000 35.7200 N 209 1 0.2000 0.0000
DefRow: ROW_16 CoreSite 10.0000 37.4300 FS 209 1 0.2000 0.0000
DefRow: ROW_17 CoreSite 10.0000 39.1400 N 209 1 0.2000 0.0000
DefRow: ROW_18 CoreSite 10.0000 40.8500 FS 209 1 0.2000 0.0000
DefRow: ROW_19 CoreSite 10.0000 42.5600 N 209 1 0.2000 0.0000
DefRow: ROW_20 CoreSite 10.0000 44.2700 FS 209 1 0.2000 0.0000
DefRow: ROW_21 CoreSite 10.0000 45.9800 N 209 1 0.2000 0.0000
DefRow: ROW_22 CoreSite 10.0000 47.6900 FS 209 1 0.2000 0.0000

######################################################
#  Track: dir start number space layer_num layer1 ...#
######################################################
Track: X 0.1000 309 0.2000 1 9
Track: Y 0.4750 156 0.3800 1 9
Track: Y 0.3800 208 0.2850 1 8
Track: X 0.1000 309 0.2000 1 8
Track: X 0.1000 309 0.2000 1 7
Track: Y 0.3800 208 0.2850 1 7
Track: Y 0.0950 313 0.1900 1 6
Track: X 0.1000 309 0.2000 1 6
Track: X 0.1000 309 0.2000 1 5
Track: Y 0.0950 313 0.1900 1 5
Track: Y 0.0950 313 0.1900 1 4
Track: X 0.1000 309 0.2000 1 4
Track: X 0.1000 309 0.2000 1 3
Track: Y 0.0950 313 0.1900 1 3
Track: Y 0.0950 313 0.1900 1 2
Track: X 0.1000 309 0.2000 1 2
Track: X 0.1000 309 0.2000 1 1
Track: Y 0.0950 313 0.1900 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X -0.0050 2 3.0050
GCellGrid: X 6.0000 19 3.0000
GCellGrid: X 61.9050 1 1.9050
GCellGrid: Y -0.0050 20 3.0000
GCellGrid: Y 59.4050 1 2.4100

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: VDD -pwr
PhysicalNet: VSS -gnd

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################
PhysicalInstance: top_module_FILL_impl0_1 FILL4 MX 10.0000 10.0700
PhysicalInstance: top_module_FILL_impl0_2 FILL4 MX 15.8000 10.0700
PhysicalInstance: top_module_FILL_impl0_3 FILL4 MX 23.2000 10.0700
PhysicalInstance: top_module_FILL_impl0_4 FILL1 MX 24.0000 10.0700
PhysicalInstance: top_module_FILL_impl0_5 FILL1 MX 26.0000 10.0700
PhysicalInstance: top_module_FILL_impl0_6 FILL2 MX 29.0000 10.0700
PhysicalInstance: top_module_FILL_impl0_7 FILL2 MX 30.4000 10.0700
PhysicalInstance: top_module_FILL_impl0_8 FILL1 MX 30.8000 10.0700
PhysicalInstance: top_module_FILL_impl0_9 FILL4 MX 32.4000 10.0700
PhysicalInstance: top_module_FILL_impl0_10 FILL1 MX 33.2000 10.0700
PhysicalInstance: top_module_FILL_impl0_11 FILL4 MX 35.0000 10.0700
PhysicalInstance: top_module_FILL_impl0_12 FILL2 MX 36.8000 10.0700
PhysicalInstance: top_module_FILL_impl0_13 FILL4 MX 38.2000 10.0700
PhysicalInstance: top_module_FILL_impl0_14 FILL2 MX 39.0000 10.0700
PhysicalInstance: top_module_FILL_impl0_15 FILL8 MX 41.6000 10.0700
PhysicalInstance: top_module_FILL_impl0_16 FILL4 MX 43.2000 10.0700
PhysicalInstance: top_module_FILL_impl0_17 FILL2 MX 44.0000 10.0700
PhysicalInstance: top_module_FILL_impl0_18 FILL1 MX 44.4000 10.0700
PhysicalInstance: top_module_FILL_impl0_19 FILL2 MX 46.0000 10.0700
PhysicalInstance: top_module_FILL_impl0_20 FILL2 MX 48.6000 10.0700
PhysicalInstance: top_module_FILL_impl0_21 FILL2 MX 51.2000 10.0700
PhysicalInstance: top_module_FILL_impl0_22 FILL1 MX 51.6000 10.0700
PhysicalInstance: top_module_FILL_impl0_23 FILL8 R0 10.0000 11.7800
PhysicalInstance: top_module_FILL_impl0_24 FILL4 R0 11.6000 11.7800
PhysicalInstance: top_module_FILL_impl0_25 FILL2 R0 12.4000 11.7800
PhysicalInstance: top_module_FILL_impl0_26 FILL1 R0 12.8000 11.7800
PhysicalInstance: top_module_FILL_impl0_27 FILL2 R0 14.0000 11.7800
PhysicalInstance: top_module_FILL_impl0_28 FILL2 R0 16.2000 11.7800
PhysicalInstance: top_module_FILL_impl0_29 FILL1 R0 16.6000 11.7800
PhysicalInstance: top_module_FILL_impl0_30 FILL8 R0 21.8000 11.7800
PhysicalInstance: top_module_FILL_impl0_31 FILL2 R0 23.4000 11.7800
PhysicalInstance: top_module_FILL_impl0_32 FILL1 R0 23.8000 11.7800
PhysicalInstance: top_module_FILL_impl0_33 FILL4 R0 25.0000 11.7800
PhysicalInstance: top_module_FILL_impl0_34 FILL1 R0 25.8000 11.7800
PhysicalInstance: top_module_FILL_impl0_35 FILL8 R0 27.2000 11.7800
PhysicalInstance: top_module_FILL_impl0_36 FILL2 R0 28.8000 11.7800
PhysicalInstance: top_module_FILL_impl0_37 FILL1 R0 29.2000 11.7800
PhysicalInstance: top_module_FILL_impl0_38 FILL4 R0 32.2000 11.7800
PhysicalInstance: top_module_FILL_impl0_39 FILL16 R0 34.4000 11.7800
PhysicalInstance: top_module_FILL_impl0_40 FILL4 R0 37.6000 11.7800
PhysicalInstance: top_module_FILL_impl0_41 FILL2 R0 38.4000 11.7800
PhysicalInstance: top_module_FILL_impl0_42 FILL16 R0 40.6000 11.7800
PhysicalInstance: top_module_FILL_impl0_43 FILL4 R0 43.8000 11.7800
PhysicalInstance: top_module_FILL_impl0_44 FILL8 R0 45.2000 11.7800
PhysicalInstance: top_module_FILL_impl0_45 FILL2 R0 46.8000 11.7800
PhysicalInstance: top_module_FILL_impl0_46 FILL1 R0 48.8000 11.7800
PhysicalInstance: top_module_FILL_impl0_47 FILL2 R0 51.4000 11.7800
PhysicalInstance: top_module_FILL_impl0_48 FILL2 MX 10.0000 13.4900
PhysicalInstance: top_module_FILL_impl0_49 FILL8 MX 15.4000 13.4900
PhysicalInstance: top_module_FILL_impl0_50 FILL2 MX 17.0000 13.4900
PhysicalInstance: top_module_FILL_impl0_51 FILL4 MX 18.8000 13.4900
PhysicalInstance: top_module_FILL_impl0_52 FILL2 MX 19.6000 13.4900
PhysicalInstance: top_module_FILL_impl0_53 FILL4 MX 21.0000 13.4900
PhysicalInstance: top_module_FILL_impl0_54 FILL2 MX 21.8000 13.4900
PhysicalInstance: top_module_FILL_impl0_55 FILL2 MX 23.0000 13.4900
PhysicalInstance: top_module_FILL_impl0_56 FILL2 MX 24.4000 13.4900
PhysicalInstance: top_module_FILL_impl0_57 FILL1 MX 24.8000 13.4900
PhysicalInstance: top_module_FILL_impl0_58 FILL2 MX 26.4000 13.4900
PhysicalInstance: top_module_FILL_impl0_59 FILL1 MX 26.8000 13.4900
PhysicalInstance: top_module_FILL_impl0_60 FILL4 MX 29.8000 13.4900
PhysicalInstance: top_module_FILL_impl0_61 FILL4 MX 32.0000 13.4900
PhysicalInstance: top_module_FILL_impl0_62 FILL2 MX 32.8000 13.4900
PhysicalInstance: top_module_FILL_impl0_63 FILL1 MX 33.2000 13.4900
PhysicalInstance: top_module_FILL_impl0_64 FILL4 MX 34.0000 13.4900
PhysicalInstance: top_module_FILL_impl0_65 FILL16 MX 36.0000 13.4900
PhysicalInstance: top_module_FILL_impl0_66 FILL4 MX 39.2000 13.4900
PhysicalInstance: top_module_FILL_impl0_67 FILL2 MX 40.0000 13.4900
PhysicalInstance: top_module_FILL_impl0_68 FILL4 MX 41.2000 13.4900
PhysicalInstance: top_module_FILL_impl0_69 FILL1 MX 42.0000 13.4900
PhysicalInstance: top_module_FILL_impl0_70 FILL16 MX 43.8000 13.4900
PhysicalInstance: top_module_FILL_impl0_71 FILL2 MX 48.0000 13.4900
PhysicalInstance: top_module_FILL_impl0_72 FILL8 MX 49.8000 13.4900
PhysicalInstance: top_module_FILL_impl0_73 FILL2 MX 51.4000 13.4900
PhysicalInstance: top_module_FILL_impl0_74 FILL4 R0 10.0000 15.2000
PhysicalInstance: top_module_FILL_impl0_75 FILL2 R0 14.0000 15.2000
PhysicalInstance: top_module_FILL_impl0_76 FILL1 R0 14.4000 15.2000
PhysicalInstance: top_module_FILL_impl0_77 FILL2 R0 16.4000 15.2000
PhysicalInstance: top_module_FILL_impl0_78 FILL1 R0 16.8000 15.2000
PhysicalInstance: top_module_FILL_impl0_79 FILL8 R0 19.2000 15.2000
PhysicalInstance: top_module_FILL_impl0_80 FILL2 R0 20.8000 15.2000
PhysicalInstance: top_module_FILL_impl0_81 FILL8 R0 23.0000 15.2000
PhysicalInstance: top_module_FILL_impl0_82 FILL2 R0 24.6000 15.2000
PhysicalInstance: top_module_FILL_impl0_83 FILL1 R0 25.0000 15.2000
PhysicalInstance: top_module_FILL_impl0_84 FILL2 R0 26.2000 15.2000
PhysicalInstance: top_module_FILL_impl0_85 FILL1 R0 26.6000 15.2000
PhysicalInstance: top_module_FILL_impl0_86 FILL2 R0 27.8000 15.2000
PhysicalInstance: top_module_FILL_impl0_87 FILL1 R0 28.2000 15.2000
PhysicalInstance: top_module_FILL_impl0_88 FILL4 R0 29.6000 15.2000
PhysicalInstance: top_module_FILL_impl0_89 FILL2 R0 30.4000 15.2000
PhysicalInstance: top_module_FILL_impl0_90 FILL1 R0 30.8000 15.2000
PhysicalInstance: top_module_FILL_impl0_91 FILL4 R0 32.4000 15.2000
PhysicalInstance: top_module_FILL_impl0_92 FILL4 R0 34.2000 15.2000
PhysicalInstance: top_module_FILL_impl0_93 FILL1 R0 35.0000 15.2000
PhysicalInstance: top_module_FILL_impl0_94 FILL4 R0 36.4000 15.2000
PhysicalInstance: top_module_FILL_impl0_95 FILL4 R0 38.2000 15.2000
PhysicalInstance: top_module_FILL_impl0_96 FILL2 R0 39.0000 15.2000
PhysicalInstance: top_module_FILL_impl0_97 FILL1 R0 41.6000 15.2000
PhysicalInstance: top_module_FILL_impl0_98 FILL8 R0 44.4000 15.2000
PhysicalInstance: top_module_FILL_impl0_99 FILL2 R0 46.0000 15.2000
PhysicalInstance: top_module_FILL_impl0_100 FILL2 R0 49.0000 15.2000
PhysicalInstance: top_module_FILL_impl0_101 FILL1 R0 49.4000 15.2000
PhysicalInstance: top_module_FILL_impl0_102 FILL2 R0 51.4000 15.2000
PhysicalInstance: top_module_FILL_impl0_103 FILL8 MX 10.0000 16.9100
PhysicalInstance: top_module_FILL_impl0_104 FILL2 MX 11.6000 16.9100
PhysicalInstance: top_module_FILL_impl0_105 FILL4 MX 17.0000 16.9100
PhysicalInstance: top_module_FILL_impl0_106 FILL1 MX 17.8000 16.9100
PhysicalInstance: top_module_FILL_impl0_107 FILL4 MX 23.0000 16.9100
PhysicalInstance: top_module_FILL_impl0_108 FILL4 MX 29.0000 16.9100
PhysicalInstance: top_module_FILL_impl0_109 FILL4 MX 31.0000 16.9100
PhysicalInstance: top_module_FILL_impl0_110 FILL1 MX 32.4000 16.9100
PhysicalInstance: top_module_FILL_impl0_111 FILL4 MX 33.2000 16.9100
PhysicalInstance: top_module_FILL_impl0_112 FILL2 MX 34.0000 16.9100
PhysicalInstance: top_module_FILL_impl0_113 FILL1 MX 34.4000 16.9100
PhysicalInstance: top_module_FILL_impl0_114 FILL4 MX 35.6000 16.9100
PhysicalInstance: top_module_FILL_impl0_115 FILL1 MX 37.6000 16.9100
PhysicalInstance: top_module_FILL_impl0_116 FILL1 MX 38.8000 16.9100
PhysicalInstance: top_module_FILL_impl0_117 FILL4 MX 40.4000 16.9100
PhysicalInstance: top_module_FILL_impl0_118 FILL2 MX 41.2000 16.9100
PhysicalInstance: top_module_FILL_impl0_119 FILL1 MX 41.6000 16.9100
PhysicalInstance: top_module_FILL_impl0_120 FILL2 MX 44.4000 16.9100
PhysicalInstance: top_module_FILL_impl0_121 FILL2 MX 46.2000 16.9100
PhysicalInstance: top_module_FILL_impl0_122 FILL4 MX 47.2000 16.9100
PhysicalInstance: top_module_FILL_impl0_123 FILL4 MX 50.8000 16.9100
PhysicalInstance: top_module_FILL_impl0_124 FILL1 MX 51.6000 16.9100
PhysicalInstance: top_module_FILL_impl0_125 FILL2 R0 10.0000 18.6200
PhysicalInstance: top_module_FILL_impl0_126 FILL4 R0 15.8000 18.6200
PhysicalInstance: top_module_FILL_impl0_127 FILL2 R0 16.6000 18.6200
PhysicalInstance: top_module_FILL_impl0_128 FILL1 R0 17.0000 18.6200
PhysicalInstance: top_module_FILL_impl0_129 FILL1 R0 18.2000 18.6200
PhysicalInstance: top_module_FILL_impl0_130 FILL2 R0 19.4000 18.6200
PhysicalInstance: top_module_FILL_impl0_131 FILL1 R0 19.8000 18.6200
PhysicalInstance: top_module_FILL_impl0_132 FILL8 R0 21.8000 18.6200
PhysicalInstance: top_module_FILL_impl0_133 FILL1 R0 23.4000 18.6200
PhysicalInstance: top_module_FILL_impl0_134 FILL4 R0 26.2000 18.6200
PhysicalInstance: top_module_FILL_impl0_135 FILL1 R0 27.0000 18.6200
PhysicalInstance: top_module_FILL_impl0_136 FILL2 R0 28.2000 18.6200
PhysicalInstance: top_module_FILL_impl0_137 FILL1 R0 28.6000 18.6200
PhysicalInstance: top_module_FILL_impl0_138 FILL4 R0 30.8000 18.6200
PhysicalInstance: top_module_FILL_impl0_139 FILL1 R0 33.0000 18.6200
PhysicalInstance: top_module_FILL_impl0_140 FILL4 R0 34.4000 18.6200
PhysicalInstance: top_module_FILL_impl0_141 FILL1 R0 35.2000 18.6200
PhysicalInstance: top_module_FILL_impl0_142 FILL2 R0 36.8000 18.6200
PhysicalInstance: top_module_FILL_impl0_143 FILL1 R0 37.2000 18.6200
PhysicalInstance: top_module_FILL_impl0_144 FILL1 R0 38.4000 18.6200
PhysicalInstance: top_module_FILL_impl0_145 FILL1 R0 39.8000 18.6200
PhysicalInstance: top_module_FILL_impl0_146 FILL2 R0 40.6000 18.6200
PhysicalInstance: top_module_FILL_impl0_147 FILL1 R0 41.0000 18.6200
PhysicalInstance: top_module_FILL_impl0_148 FILL1 R0 42.6000 18.6200
PhysicalInstance: top_module_FILL_impl0_149 FILL1 R0 44.0000 18.6200
PhysicalInstance: top_module_FILL_impl0_150 FILL1 R0 45.2000 18.6200
PhysicalInstance: top_module_FILL_impl0_151 FILL4 R0 46.4000 18.6200
PhysicalInstance: top_module_FILL_impl0_152 FILL1 R0 47.2000 18.6200
PhysicalInstance: top_module_FILL_impl0_153 FILL2 R0 48.2000 18.6200
PhysicalInstance: top_module_FILL_impl0_154 FILL1 R0 49.2000 18.6200
PhysicalInstance: top_module_FILL_impl0_155 FILL4 R0 50.8000 18.6200
PhysicalInstance: top_module_FILL_impl0_156 FILL1 R0 51.6000 18.6200
PhysicalInstance: top_module_FILL_impl0_157 FILL1 MX 10.0000 20.3300
PhysicalInstance: top_module_FILL_impl0_158 FILL2 MX 16.6000 20.3300
PhysicalInstance: top_module_FILL_impl0_159 FILL2 MX 17.8000 20.3300
PhysicalInstance: top_module_FILL_impl0_160 FILL4 MX 19.0000 20.3300
PhysicalInstance: top_module_FILL_impl0_161 FILL2 MX 20.8000 20.3300
PhysicalInstance: top_module_FILL_impl0_162 FILL2 MX 22.2000 20.3300
PhysicalInstance: top_module_FILL_impl0_163 FILL4 MX 23.4000 20.3300
PhysicalInstance: top_module_FILL_impl0_164 FILL2 MX 24.2000 20.3300
PhysicalInstance: top_module_FILL_impl0_165 FILL1 MX 24.6000 20.3300
PhysicalInstance: top_module_FILL_impl0_166 FILL2 MX 25.8000 20.3300
PhysicalInstance: top_module_FILL_impl0_167 FILL1 MX 26.2000 20.3300
PhysicalInstance: top_module_FILL_impl0_168 FILL4 MX 27.0000 20.3300
PhysicalInstance: top_module_FILL_impl0_169 FILL1 MX 27.8000 20.3300
PhysicalInstance: top_module_FILL_impl0_170 FILL4 MX 29.2000 20.3300
PhysicalInstance: top_module_FILL_impl0_171 FILL2 MX 30.0000 20.3300
PhysicalInstance: top_module_FILL_impl0_172 FILL2 MX 31.4000 20.3300
PhysicalInstance: top_module_FILL_impl0_173 FILL4 MX 34.0000 20.3300
PhysicalInstance: top_module_FILL_impl0_174 FILL2 MX 34.8000 20.3300
PhysicalInstance: top_module_FILL_impl0_175 FILL4 MX 35.8000 20.3300
PhysicalInstance: top_module_FILL_impl0_176 FILL1 MX 36.6000 20.3300
PhysicalInstance: top_module_FILL_impl0_177 FILL2 MX 39.0000 20.3300
PhysicalInstance: top_module_FILL_impl0_178 FILL1 MX 40.0000 20.3300
PhysicalInstance: top_module_FILL_impl0_179 FILL16 MX 42.4000 20.3300
PhysicalInstance: top_module_FILL_impl0_180 FILL2 MX 46.4000 20.3300
PhysicalInstance: top_module_FILL_impl0_181 FILL2 MX 48.4000 20.3300
PhysicalInstance: top_module_FILL_impl0_182 FILL1 MX 48.8000 20.3300
PhysicalInstance: top_module_FILL_impl0_183 FILL2 MX 51.4000 20.3300
PhysicalInstance: top_module_FILL_impl0_184 FILL4 R0 10.0000 22.0400
PhysicalInstance: top_module_FILL_impl0_185 FILL2 R0 10.8000 22.0400
PhysicalInstance: top_module_FILL_impl0_186 FILL1 R0 11.2000 22.0400
PhysicalInstance: top_module_FILL_impl0_187 FILL4 R0 16.0000 22.0400
PhysicalInstance: top_module_FILL_impl0_188 FILL2 R0 16.8000 22.0400
PhysicalInstance: top_module_FILL_impl0_189 FILL1 R0 22.2000 22.0400
PhysicalInstance: top_module_FILL_impl0_190 FILL4 R0 25.2000 22.0400
PhysicalInstance: top_module_FILL_impl0_191 FILL4 R0 27.4000 22.0400
PhysicalInstance: top_module_FILL_impl0_192 FILL4 R0 29.4000 22.0400
PhysicalInstance: top_module_FILL_impl0_193 FILL2 R0 30.2000 22.0400
PhysicalInstance: top_module_FILL_impl0_194 FILL1 R0 30.6000 22.0400
PhysicalInstance: top_module_FILL_impl0_195 FILL4 R0 31.8000 22.0400
PhysicalInstance: top_module_FILL_impl0_196 FILL4 R0 35.2000 22.0400
PhysicalInstance: top_module_FILL_impl0_197 FILL2 R0 36.0000 22.0400
PhysicalInstance: top_module_FILL_impl0_198 FILL4 R0 37.6000 22.0400
PhysicalInstance: top_module_FILL_impl0_199 FILL1 R0 38.4000 22.0400
PhysicalInstance: top_module_FILL_impl0_200 FILL1 R0 40.2000 22.0400
PhysicalInstance: top_module_FILL_impl0_201 FILL1 R0 43.4000 22.0400
PhysicalInstance: top_module_FILL_impl0_202 FILL2 R0 45.6000 22.0400
PhysicalInstance: top_module_FILL_impl0_203 FILL1 R0 46.0000 22.0400
PhysicalInstance: top_module_FILL_impl0_204 FILL2 R0 48.6000 22.0400
PhysicalInstance: top_module_FILL_impl0_205 FILL2 R0 51.4000 22.0400
PhysicalInstance: top_module_FILL_impl0_206 FILL1 MX 10.0000 23.7500
PhysicalInstance: top_module_FILL_impl0_207 FILL1 MX 11.0000 23.7500
PhysicalInstance: top_module_FILL_impl0_208 FILL2 MX 12.2000 23.7500
PhysicalInstance: top_module_FILL_impl0_209 FILL1 MX 12.6000 23.7500
PhysicalInstance: top_module_FILL_impl0_210 FILL1 MX 13.8000 23.7500
PhysicalInstance: top_module_FILL_impl0_211 FILL1 MX 19.6000 23.7500
PhysicalInstance: top_module_FILL_impl0_212 FILL8 MX 24.8000 23.7500
PhysicalInstance: top_module_FILL_impl0_213 FILL2 MX 26.4000 23.7500
PhysicalInstance: top_module_FILL_impl0_214 FILL2 MX 28.4000 23.7500
PhysicalInstance: top_module_FILL_impl0_215 FILL1 MX 28.8000 23.7500
PhysicalInstance: top_module_FILL_impl0_216 FILL4 MX 30.8000 23.7500
PhysicalInstance: top_module_FILL_impl0_217 FILL2 MX 32.2000 23.7500
PhysicalInstance: top_module_FILL_impl0_218 FILL1 MX 35.0000 23.7500
PhysicalInstance: top_module_FILL_impl0_219 FILL2 MX 37.0000 23.7500
PhysicalInstance: top_module_FILL_impl0_220 FILL1 MX 39.0000 23.7500
PhysicalInstance: top_module_FILL_impl0_221 FILL1 MX 40.2000 23.7500
PhysicalInstance: top_module_FILL_impl0_222 FILL1 MX 44.0000 23.7500
PhysicalInstance: top_module_FILL_impl0_223 FILL16 MX 44.8000 23.7500
PhysicalInstance: top_module_FILL_impl0_224 FILL4 MX 48.0000 23.7500
PhysicalInstance: top_module_FILL_impl0_225 FILL1 MX 48.8000 23.7500
PhysicalInstance: top_module_FILL_impl0_226 FILL2 MX 51.4000 23.7500
PhysicalInstance: top_module_FILL_impl0_227 FILL2 R0 23.6000 25.4600
PhysicalInstance: top_module_FILL_impl0_228 FILL2 R0 28.6000 25.4600
PhysicalInstance: top_module_FILL_impl0_229 FILL1 R0 29.0000 25.4600
PhysicalInstance: top_module_FILL_impl0_230 FILL8 R0 33.4000 25.4600
PhysicalInstance: top_module_FILL_impl0_231 FILL4 R0 35.0000 25.4600
PhysicalInstance: top_module_FILL_impl0_232 FILL2 R0 35.8000 25.4600
PhysicalInstance: top_module_FILL_impl0_233 FILL1 R0 36.2000 25.4600
PhysicalInstance: top_module_FILL_impl0_234 FILL1 R0 38.0000 25.4600
PhysicalInstance: top_module_FILL_impl0_235 FILL4 R0 39.6000 25.4600
PhysicalInstance: top_module_FILL_impl0_236 FILL1 R0 41.8000 25.4600
PhysicalInstance: top_module_FILL_impl0_237 FILL8 R0 43.0000 25.4600
PhysicalInstance: top_module_FILL_impl0_238 FILL4 R0 44.6000 25.4600
PhysicalInstance: top_module_FILL_impl0_239 FILL2 R0 45.4000 25.4600
PhysicalInstance: top_module_FILL_impl0_240 FILL1 R0 45.8000 25.4600
PhysicalInstance: top_module_FILL_impl0_241 FILL2 R0 47.6000 25.4600
PhysicalInstance: top_module_FILL_impl0_242 FILL4 R0 50.4000 25.4600
PhysicalInstance: top_module_FILL_impl0_243 FILL2 R0 51.2000 25.4600
PhysicalInstance: top_module_FILL_impl0_244 FILL1 R0 51.6000 25.4600
PhysicalInstance: top_module_FILL_impl0_245 FILL1 MX 10.0000 27.1700
PhysicalInstance: top_module_FILL_impl0_246 FILL1 MX 13.4000 27.1700
PhysicalInstance: top_module_FILL_impl0_247 FILL4 MX 14.6000 27.1700
PhysicalInstance: top_module_FILL_impl0_248 FILL2 MX 15.4000 27.1700
PhysicalInstance: top_module_FILL_impl0_249 FILL2 MX 17.6000 27.1700
PhysicalInstance: top_module_FILL_impl0_250 FILL1 MX 20.8000 27.1700
PhysicalInstance: top_module_FILL_impl0_251 FILL2 MX 23.8000 27.1700
PhysicalInstance: top_module_FILL_impl0_252 FILL1 MX 24.2000 27.1700
PhysicalInstance: top_module_FILL_impl0_253 FILL4 MX 25.4000 27.1700
PhysicalInstance: top_module_FILL_impl0_254 FILL8 MX 33.0000 27.1700
PhysicalInstance: top_module_FILL_impl0_255 FILL8 MX 35.4000 27.1700
PhysicalInstance: top_module_FILL_impl0_256 FILL1 MX 37.0000 27.1700
PhysicalInstance: top_module_FILL_impl0_257 FILL2 MX 38.8000 27.1700
PhysicalInstance: top_module_FILL_impl0_258 FILL1 MX 40.4000 27.1700
PhysicalInstance: top_module_FILL_impl0_259 FILL8 MX 42.2000 27.1700
PhysicalInstance: top_module_FILL_impl0_260 FILL1 MX 43.8000 27.1700
PhysicalInstance: top_module_FILL_impl0_261 FILL4 MX 44.6000 27.1700
PhysicalInstance: top_module_FILL_impl0_262 FILL1 MX 45.4000 27.1700
PhysicalInstance: top_module_FILL_impl0_263 FILL4 MX 47.2000 27.1700
PhysicalInstance: top_module_FILL_impl0_264 FILL2 MX 49.4000 27.1700
PhysicalInstance: top_module_FILL_impl0_265 FILL1 MX 49.8000 27.1700
PhysicalInstance: top_module_FILL_impl0_266 FILL4 R0 13.8000 28.8800
PhysicalInstance: top_module_FILL_impl0_267 FILL1 R0 14.6000 28.8800
PhysicalInstance: top_module_FILL_impl0_268 FILL8 R0 15.8000 28.8800
PhysicalInstance: top_module_FILL_impl0_269 FILL1 R0 17.4000 28.8800
PhysicalInstance: top_module_FILL_impl0_270 FILL1 R0 26.0000 28.8800
PhysicalInstance: top_module_FILL_impl0_271 FILL4 R0 32.6000 28.8800
PhysicalInstance: top_module_FILL_impl0_272 FILL2 R0 34.6000 28.8800
PhysicalInstance: top_module_FILL_impl0_273 FILL1 R0 35.0000 28.8800
PhysicalInstance: top_module_FILL_impl0_274 FILL2 R0 35.8000 28.8800
PhysicalInstance: top_module_FILL_impl0_275 FILL1 R0 36.2000 28.8800
PhysicalInstance: top_module_FILL_impl0_276 FILL16 R0 37.0000 28.8800
PhysicalInstance: top_module_FILL_impl0_277 FILL8 R0 40.2000 28.8800
PhysicalInstance: top_module_FILL_impl0_278 FILL4 R0 41.8000 28.8800
PhysicalInstance: top_module_FILL_impl0_279 FILL2 R0 42.6000 28.8800
PhysicalInstance: top_module_FILL_impl0_280 FILL1 R0 44.0000 28.8800
PhysicalInstance: top_module_FILL_impl0_281 FILL4 R0 44.8000 28.8800
PhysicalInstance: top_module_FILL_impl0_282 FILL1 R0 46.6000 28.8800
PhysicalInstance: top_module_FILL_impl0_283 FILL2 R0 48.2000 28.8800
PhysicalInstance: top_module_FILL_impl0_284 FILL2 R0 51.4000 28.8800
PhysicalInstance: top_module_FILL_impl0_285 FILL2 MX 27.8000 30.5900
PhysicalInstance: top_module_FILL_impl0_286 FILL1 MX 28.2000 30.5900
PhysicalInstance: top_module_FILL_impl0_287 FILL2 MX 32.6000 30.5900
PhysicalInstance: top_module_FILL_impl0_288 FILL1 MX 33.0000 30.5900
PhysicalInstance: top_module_FILL_impl0_289 FILL2 MX 34.2000 30.5900
PhysicalInstance: top_module_FILL_impl0_290 FILL1 MX 34.6000 30.5900
PhysicalInstance: top_module_FILL_impl0_291 FILL8 MX 40.6000 30.5900
PhysicalInstance: top_module_FILL_impl0_292 FILL2 MX 42.2000 30.5900
PhysicalInstance: top_module_FILL_impl0_293 FILL1 MX 42.6000 30.5900
PhysicalInstance: top_module_FILL_impl0_294 FILL2 MX 43.6000 30.5900
PhysicalInstance: top_module_FILL_impl0_295 FILL1 MX 44.0000 30.5900
PhysicalInstance: top_module_FILL_impl0_296 FILL2 MX 45.0000 30.5900
PhysicalInstance: top_module_FILL_impl0_297 FILL2 MX 46.4000 30.5900
PhysicalInstance: top_module_FILL_impl0_298 FILL1 MX 46.8000 30.5900
PhysicalInstance: top_module_FILL_impl0_299 FILL2 MX 48.4000 30.5900
PhysicalInstance: top_module_FILL_impl0_300 FILL1 MX 48.8000 30.5900
PhysicalInstance: top_module_FILL_impl0_301 FILL2 MX 51.4000 30.5900
PhysicalInstance: top_module_FILL_impl0_302 FILL8 R0 10.0000 32.3000
PhysicalInstance: top_module_FILL_impl0_303 FILL1 R0 12.2000 32.3000
PhysicalInstance: top_module_FILL_impl0_304 FILL2 R0 28.2000 32.3000
PhysicalInstance: top_module_FILL_impl0_305 FILL4 R0 34.6000 32.3000
PhysicalInstance: top_module_FILL_impl0_306 FILL2 R0 36.4000 32.3000
PhysicalInstance: top_module_FILL_impl0_307 FILL1 R0 38.0000 32.3000
PhysicalInstance: top_module_FILL_impl0_308 FILL4 R0 38.8000 32.3000
PhysicalInstance: top_module_FILL_impl0_309 FILL1 R0 39.6000 32.3000
PhysicalInstance: top_module_FILL_impl0_310 FILL2 R0 41.8000 32.3000
PhysicalInstance: top_module_FILL_impl0_311 FILL1 R0 42.2000 32.3000
PhysicalInstance: top_module_FILL_impl0_312 FILL16 R0 44.0000 32.3000
PhysicalInstance: top_module_FILL_impl0_313 FILL2 R0 47.2000 32.3000
PhysicalInstance: top_module_FILL_impl0_314 FILL2 R0 48.2000 32.3000
PhysicalInstance: top_module_FILL_impl0_315 FILL1 R0 48.6000 32.3000
PhysicalInstance: top_module_FILL_impl0_316 FILL2 R0 51.2000 32.3000
PhysicalInstance: top_module_FILL_impl0_317 FILL1 R0 51.6000 32.3000
PhysicalInstance: top_module_FILL_impl0_318 FILL2 MX 15.0000 34.0100
PhysicalInstance: top_module_FILL_impl0_319 FILL2 MX 16.4000 34.0100
PhysicalInstance: top_module_FILL_impl0_320 FILL1 MX 25.8000 34.0100
PhysicalInstance: top_module_FILL_impl0_321 FILL1 MX 32.8000 34.0100
PhysicalInstance: top_module_FILL_impl0_322 FILL4 MX 36.0000 34.0100
PhysicalInstance: top_module_FILL_impl0_323 FILL2 MX 36.8000 34.0100
PhysicalInstance: top_module_FILL_impl0_324 FILL32 MX 39.8000 34.0100
PhysicalInstance: top_module_FILL_impl0_325 FILL2 MX 48.6000 34.0100
PhysicalInstance: top_module_FILL_impl0_326 FILL2 MX 51.4000 34.0100
PhysicalInstance: top_module_FILL_impl0_327 FILL1 R0 10.0000 35.7200
PhysicalInstance: top_module_FILL_impl0_328 FILL2 R0 11.4000 35.7200
PhysicalInstance: top_module_FILL_impl0_329 FILL1 R0 11.8000 35.7200
PhysicalInstance: top_module_FILL_impl0_330 FILL1 R0 16.6000 35.7200
PhysicalInstance: top_module_FILL_impl0_331 FILL1 R0 20.6000 35.7200
PhysicalInstance: top_module_FILL_impl0_332 FILL1 R0 24.0000 35.7200
PhysicalInstance: top_module_FILL_impl0_333 FILL2 R0 31.4000 35.7200
PhysicalInstance: top_module_FILL_impl0_334 FILL1 R0 31.8000 35.7200
PhysicalInstance: top_module_FILL_impl0_335 FILL4 R0 35.0000 35.7200
PhysicalInstance: top_module_FILL_impl0_336 FILL2 R0 35.8000 35.7200
PhysicalInstance: top_module_FILL_impl0_337 FILL2 R0 38.0000 35.7200
PhysicalInstance: top_module_FILL_impl0_338 FILL8 R0 40.2000 35.7200
PhysicalInstance: top_module_FILL_impl0_339 FILL2 R0 41.8000 35.7200
PhysicalInstance: top_module_FILL_impl0_340 FILL2 R0 42.8000 35.7200
PhysicalInstance: top_module_FILL_impl0_341 FILL1 R0 43.2000 35.7200
PhysicalInstance: top_module_FILL_impl0_342 FILL2 R0 44.8000 35.7200
PhysicalInstance: top_module_FILL_impl0_343 FILL2 R0 46.8000 35.7200
PhysicalInstance: top_module_FILL_impl0_344 FILL2 R0 49.6000 35.7200
PhysicalInstance: top_module_FILL_impl0_345 FILL1 MX 12.8000 37.4300
PhysicalInstance: top_module_FILL_impl0_346 FILL1 MX 15.8000 37.4300
PhysicalInstance: top_module_FILL_impl0_347 FILL2 MX 17.2000 37.4300
PhysicalInstance: top_module_FILL_impl0_348 FILL1 MX 17.6000 37.4300
PhysicalInstance: top_module_FILL_impl0_349 FILL2 MX 26.6000 37.4300
PhysicalInstance: top_module_FILL_impl0_350 FILL1 MX 27.0000 37.4300
PhysicalInstance: top_module_FILL_impl0_351 FILL2 MX 31.0000 37.4300
PhysicalInstance: top_module_FILL_impl0_352 FILL1 MX 31.4000 37.4300
PhysicalInstance: top_module_FILL_impl0_353 FILL2 MX 32.6000 37.4300
PhysicalInstance: top_module_FILL_impl0_354 FILL2 MX 36.2000 37.4300
PhysicalInstance: top_module_FILL_impl0_355 FILL1 MX 36.6000 37.4300
PhysicalInstance: top_module_FILL_impl0_356 FILL1 MX 37.4000 37.4300
PhysicalInstance: top_module_FILL_impl0_357 FILL2 MX 39.0000 37.4300
PhysicalInstance: top_module_FILL_impl0_358 FILL2 MX 40.4000 37.4300
PhysicalInstance: top_module_FILL_impl0_359 FILL1 MX 40.8000 37.4300
PhysicalInstance: top_module_FILL_impl0_360 FILL2 MX 42.2000 37.4300
PhysicalInstance: top_module_FILL_impl0_361 FILL1 MX 42.6000 37.4300
PhysicalInstance: top_module_FILL_impl0_362 FILL2 MX 45.4000 37.4300
PhysicalInstance: top_module_FILL_impl0_363 FILL4 MX 47.2000 37.4300
PhysicalInstance: top_module_FILL_impl0_364 FILL2 MX 48.0000 37.4300
PhysicalInstance: top_module_FILL_impl0_365 FILL1 MX 48.4000 37.4300
PhysicalInstance: top_module_FILL_impl0_366 FILL2 MX 51.4000 37.4300
PhysicalInstance: top_module_FILL_impl0_367 FILL1 R0 12.8000 39.1400
PhysicalInstance: top_module_FILL_impl0_368 FILL4 R0 20.8000 39.1400
PhysicalInstance: top_module_FILL_impl0_369 FILL2 R0 31.8000 39.1400
PhysicalInstance: top_module_FILL_impl0_370 FILL1 R0 33.4000 39.1400
PhysicalInstance: top_module_FILL_impl0_371 FILL1 R0 35.0000 39.1400
PhysicalInstance: top_module_FILL_impl0_372 FILL2 R0 35.8000 39.1400
PhysicalInstance: top_module_FILL_impl0_373 FILL8 R0 36.8000 39.1400
PhysicalInstance: top_module_FILL_impl0_374 FILL8 R0 39.4000 39.1400
PhysicalInstance: top_module_FILL_impl0_375 FILL1 R0 41.0000 39.1400
PhysicalInstance: top_module_FILL_impl0_376 FILL2 R0 42.0000 39.1400
PhysicalInstance: top_module_FILL_impl0_377 FILL1 R0 42.4000 39.1400
PhysicalInstance: top_module_FILL_impl0_378 FILL2 R0 43.6000 39.1400
PhysicalInstance: top_module_FILL_impl0_379 FILL1 R0 44.0000 39.1400
PhysicalInstance: top_module_FILL_impl0_380 FILL1 R0 44.8000 39.1400
PhysicalInstance: top_module_FILL_impl0_381 FILL4 R0 46.0000 39.1400
PhysicalInstance: top_module_FILL_impl0_382 FILL2 R0 46.8000 39.1400
PhysicalInstance: top_module_FILL_impl0_383 FILL1 R0 47.2000 39.1400
PhysicalInstance: top_module_FILL_impl0_384 FILL1 R0 48.8000 39.1400
PhysicalInstance: top_module_FILL_impl0_385 FILL2 R0 51.4000 39.1400
PhysicalInstance: top_module_FILL_impl0_386 FILL2 MX 13.8000 40.8500
PhysicalInstance: top_module_FILL_impl0_387 FILL1 MX 14.2000 40.8500
PhysicalInstance: top_module_FILL_impl0_388 FILL1 MX 24.2000 40.8500
PhysicalInstance: top_module_FILL_impl0_389 FILL8 MX 35.4000 40.8500
PhysicalInstance: top_module_FILL_impl0_390 FILL4 MX 37.8000 40.8500
PhysicalInstance: top_module_FILL_impl0_391 FILL8 MX 42.0000 40.8500
PhysicalInstance: top_module_FILL_impl0_392 FILL2 MX 44.4000 40.8500
PhysicalInstance: top_module_FILL_impl0_393 FILL4 MX 45.4000 40.8500
PhysicalInstance: top_module_FILL_impl0_394 FILL2 MX 48.6000 40.8500
PhysicalInstance: top_module_FILL_impl0_395 FILL2 MX 51.4000 40.8500
PhysicalInstance: top_module_FILL_impl0_396 FILL1 R0 10.0000 42.5600
PhysicalInstance: top_module_FILL_impl0_397 FILL2 R0 17.0000 42.5600
PhysicalInstance: top_module_FILL_impl0_398 FILL2 R0 22.0000 42.5600
PhysicalInstance: top_module_FILL_impl0_399 FILL2 R0 26.4000 42.5600
PhysicalInstance: top_module_FILL_impl0_400 FILL1 R0 26.8000 42.5600
PhysicalInstance: top_module_FILL_impl0_401 FILL4 R0 32.6000 42.5600
PhysicalInstance: top_module_FILL_impl0_402 FILL4 R0 35.4000 42.5600
PhysicalInstance: top_module_FILL_impl0_403 FILL2 R0 36.2000 42.5600
PhysicalInstance: top_module_FILL_impl0_404 FILL1 R0 38.0000 42.5600
PhysicalInstance: top_module_FILL_impl0_405 FILL1 R0 39.4000 42.5600
PhysicalInstance: top_module_FILL_impl0_406 FILL8 R0 40.6000 42.5600
PhysicalInstance: top_module_FILL_impl0_407 FILL8 R0 46.0000 42.5600
PhysicalInstance: top_module_FILL_impl0_408 FILL4 R0 47.6000 42.5600
PhysicalInstance: top_module_FILL_impl0_409 FILL2 R0 48.4000 42.5600
PhysicalInstance: top_module_FILL_impl0_410 FILL1 R0 48.8000 42.5600
PhysicalInstance: top_module_FILL_impl0_411 FILL2 R0 51.4000 42.5600
PhysicalInstance: top_module_FILL_impl0_412 FILL1 MX 10.0000 44.2700
PhysicalInstance: top_module_FILL_impl0_413 FILL1 MX 14.4000 44.2700
PhysicalInstance: top_module_FILL_impl0_414 FILL4 MX 21.0000 44.2700
PhysicalInstance: top_module_FILL_impl0_415 FILL1 MX 21.8000 44.2700
PhysicalInstance: top_module_FILL_impl0_416 FILL4 MX 22.6000 44.2700
PhysicalInstance: top_module_FILL_impl0_417 FILL2 MX 24.6000 44.2700
PhysicalInstance: top_module_FILL_impl0_418 FILL2 MX 27.8000 44.2700
PhysicalInstance: top_module_FILL_impl0_419 FILL1 MX 28.2000 44.2700
PhysicalInstance: top_module_FILL_impl0_420 FILL4 MX 36.6000 44.2700
PhysicalInstance: top_module_FILL_impl0_421 FILL2 MX 38.0000 44.2700
PhysicalInstance: top_module_FILL_impl0_422 FILL1 MX 38.4000 44.2700
PhysicalInstance: top_module_FILL_impl0_423 FILL2 MX 40.6000 44.2700
PhysicalInstance: top_module_FILL_impl0_424 FILL2 MX 42.0000 44.2700
PhysicalInstance: top_module_FILL_impl0_425 FILL4 MX 43.0000 44.2700
PhysicalInstance: top_module_FILL_impl0_426 FILL1 MX 43.8000 44.2700
PhysicalInstance: top_module_FILL_impl0_427 FILL1 MX 45.4000 44.2700
PhysicalInstance: top_module_FILL_impl0_428 FILL2 MX 48.4000 44.2700
PhysicalInstance: top_module_FILL_impl0_429 FILL1 MX 48.8000 44.2700
PhysicalInstance: top_module_FILL_impl0_430 FILL2 MX 51.4000 44.2700
PhysicalInstance: top_module_FILL_impl0_431 FILL4 R0 10.0000 45.9800
PhysicalInstance: top_module_FILL_impl0_432 FILL2 R0 16.4000 45.9800
PhysicalInstance: top_module_FILL_impl0_433 FILL1 R0 16.8000 45.9800
PhysicalInstance: top_module_FILL_impl0_434 FILL1 R0 24.8000 45.9800
PhysicalInstance: top_module_FILL_impl0_435 FILL1 R0 29.6000 45.9800
PhysicalInstance: top_module_FILL_impl0_436 FILL8 R0 34.4000 45.9800
PhysicalInstance: top_module_FILL_impl0_437 FILL4 R0 36.6000 45.9800
PhysicalInstance: top_module_FILL_impl0_438 FILL2 R0 37.4000 45.9800
PhysicalInstance: top_module_FILL_impl0_439 FILL1 R0 37.8000 45.9800
PhysicalInstance: top_module_FILL_impl0_440 FILL4 R0 39.6000 45.9800
PhysicalInstance: top_module_FILL_impl0_441 FILL1 R0 40.4000 45.9800
PhysicalInstance: top_module_FILL_impl0_442 FILL4 R0 42.0000 45.9800
PhysicalInstance: top_module_FILL_impl0_443 FILL2 R0 43.4000 45.9800
PhysicalInstance: top_module_FILL_impl0_444 FILL4 R0 45.6000 45.9800
PhysicalInstance: top_module_FILL_impl0_445 FILL2 R0 47.4000 45.9800
PhysicalInstance: top_module_FILL_impl0_446 FILL2 R0 49.6000 45.9800
PhysicalInstance: top_module_FILL_impl0_447 FILL2 MX 10.0000 47.6900
PhysicalInstance: top_module_FILL_impl0_448 FILL2 MX 13.2000 47.6900
PhysicalInstance: top_module_FILL_impl0_449 FILL1 MX 17.4000 47.6900
PhysicalInstance: top_module_FILL_impl0_450 FILL2 MX 20.4000 47.6900
PhysicalInstance: top_module_FILL_impl0_451 FILL2 MX 23.6000 47.6900
PhysicalInstance: top_module_FILL_impl0_452 FILL2 MX 25.0000 47.6900
PhysicalInstance: top_module_FILL_impl0_453 FILL1 MX 25.4000 47.6900
PhysicalInstance: top_module_FILL_impl0_454 FILL2 MX 28.4000 47.6900
PhysicalInstance: top_module_FILL_impl0_455 FILL1 MX 28.8000 47.6900
PhysicalInstance: top_module_FILL_impl0_456 FILL8 MX 32.2000 47.6900
PhysicalInstance: top_module_FILL_impl0_457 FILL1 MX 33.8000 47.6900
PhysicalInstance: top_module_FILL_impl0_458 FILL2 MX 35.6000 47.6900
PhysicalInstance: top_module_FILL_impl0_459 FILL2 MX 38.4000 47.6900
PhysicalInstance: top_module_FILL_impl0_460 FILL2 MX 40.2000 47.6900
PhysicalInstance: top_module_FILL_impl0_461 FILL1 MX 40.6000 47.6900
PhysicalInstance: top_module_FILL_impl0_462 FILL2 MX 41.6000 47.6900
PhysicalInstance: top_module_FILL_impl0_463 FILL1 MX 42.0000 47.6900
PhysicalInstance: top_module_FILL_impl0_464 FILL4 MX 43.8000 47.6900
PhysicalInstance: top_module_FILL_impl0_465 FILL2 MX 44.6000 47.6900
PhysicalInstance: top_module_FILL_impl0_466 FILL1 MX 46.0000 47.6900
PhysicalInstance: top_module_FILL_impl0_467 FILL2 MX 48.6000 47.6900
PhysicalInstance: top_module_FILL_impl0_468 FILL2 MX 51.4000 47.6900

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val     #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val >#
#         <Net name="net_name" /> ...                                     #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d />               #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge edgeNumber=val />                                   #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr            #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val >#
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="top_module" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x1ff >
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes Metal8=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes Metal8=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################
Instance: clk_50mhz__L2_I0 R0 21.6000 32.3000
Instance: clk_50mhz__L1_I0 R0 10.0000 28.8800
Instance: u_clk/clk_1hz_reg MX 14.0000 23.7500
Instance: u_clk/cnt_reg[10] R0 26.2000 39.1400
Instance: u_clk/cnt_reg[5] R0 21.4000 28.8800
Instance: u_clk/cnt_reg[6] MX 26.2000 27.1700
Instance: u_clk/cnt_reg[7] R0 26.2000 28.8800
Instance: u_clk/cnt_reg[8] R0 25.2000 35.7200
Instance: u_clk/cnt_reg[9] R0 21.6000 39.1400
Instance: u_clk/cnt_reg[11] R0 28.0000 42.5600
Instance: u_clk/cnt_reg[12] MX 24.4000 40.8500
Instance: u_clk/cnt_reg[13] R0 29.8000 45.9800
Instance: u_clk/cnt_reg[14] R0 25.0000 45.9800
Instance: u_clk/cnt_reg[15] R0 20.2000 45.9800
Instance: u_clk/cnt_reg[16] R0 17.4000 42.5600
Instance: u_clk/cnt_reg[17] MX 14.6000 44.2700
Instance: u_clk/cnt_reg[18] R0 11.8000 45.9800
Instance: u_clk/cnt_reg[19] R0 10.2000 42.5600
Instance: u_clk/cnt_reg[1] MX 17.8000 40.8500
Instance: u_clk/cnt_reg[20] R0 14.0000 39.1400
Instance: u_clk/cnt_reg[21] R0 12.0000 35.7200
Instance: u_clk/cnt_reg[22] R0 12.4000 32.3000
Instance: u_clk/cnt_reg[23] MX 12.8000 30.5900
Instance: u_clk/cnt_reg[24] MX 10.2000 20.3300
Instance: u_clk/cnt_reg[25] R0 11.4000 22.0400
Instance: u_clk/cnt_reg[2] MX 18.6000 34.0100
Instance: u_clk/cnt_reg[3] R0 17.0000 32.3000
Instance: u_clk/cnt_reg[4] R0 12.8000 25.4600
Instance: u_clk/cnt_reg[0] MX 21.6000 37.4300

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

#################################################################
#  <PlacementBlockages>                                         #
#     <Blockage name="blk_name" type="hard|soft|partial">       #
#       <Attr density=1.2 inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </PlacementBlockages>                                        #
#################################################################
<PlacementBlockages>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=0.0000 lly=0.0000 urx=2.0000 ury=59.4700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=8.4000 lly=49.4000 urx=52.2000 ury=59.4700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=19.0000 lly=0.0000 urx=62.0000 ury=0.7600 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=11.0000 lly=0.0000 urx=20.2000 ury=0.7600 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=10.0000 lly=0.0000 urx=11.6000 ury=0.5700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=10.0000 lly=0.1900 urx=11.2000 ury=0.5700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=0.2000 lly=0.1900 urx=62.0000 ury=10.0700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=10.0000 lly=0.1900 urx=62.0000 ury=0.5700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=10.0000 lly=0.9500 urx=11.2000 ury=10.0700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=61.6000 lly=0.1900 urx=62.0000 ury=8.5500 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=52.0000 lly=8.3600 urx=62.0000 ury=59.4700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=10.2000 lly=0.1900 urx=61.8000 ury=10.0700 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=0.0000 lly=0.0000 urx=10.2000 ury=0.9500 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=10.0000 lly=0.1900 urx=12.8000 ury=0.9500 />
    </Blockage>
    <Blockage name="defScreenName" type="hard" >
	<Box llx=0.2000 lly=0.1900 urx=10.0000 ury=59.4700 />
    </Blockage>
</PlacementBlockages>

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

###########################################################################
#  <RouteBlockages>                                                       #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">   #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes />   #
#       <Layer type="route|cut|masterslice" id=layerNo />                 #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                       #
#     </Blockage>                                                         #
#  </RouteBlockages>                                                      #
###########################################################################
<RouteBlockages>
    <Blockage type="User">
	<Layer type="route" id=3 />
	<Box llx=0.0000 lly=57.6900 urx=61.9000 ury=59.4000 />
    </Blockage>
    <Blockage type="User">
	<Layer type="route" id=3 />
	<Box llx=60.5600 lly=0.0000 urx=61.9000 ury=59.4000 />
    </Blockage>
    <Blockage type="User">
	<Layer type="route" id=3 />
	<Box llx=0.0000 lly=0.0000 urx=61.9000 ury=1.4750 />
    </Blockage>
    <Blockage type="User">
	<Layer type="route" id=3 />
	<Box llx=0.0000 lly=0.0000 urx=1.5500 ury=36.6700 />
    </Blockage>
    <Blockage type="User">
	<Layer type="route" id=3 />
	<Box llx=0.0000 lly=36.6700 urx=1.5500 ury=59.4000 />
    </Blockage>
</RouteBlockages>

######################################################
#  PrerouteAsObstruct: <layer_treated_as_obstruct>   #
######################################################
PrerouteAsObstruct: 0x3

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: top_module.fp.spr

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 />...                                  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="clk_50mhz" status="fixed" >
    <Port>
      <Pref x=0.0000 y=28.9750 side=W width=0.2000 depth=2.0000 orientation=R270 />
      <Layer id=3 >
        <Box llx=0.0000 lly=28.8750 urx=2.0000 ury=29.0750 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="rst" status="fixed" >
    <Port>
      <Pref x=0.0000 y=37.5250 side=W width=0.2000 depth=2.0000 orientation=R270 />
      <Layer id=3 >
        <Box llx=0.0000 lly=37.4250 urx=2.0000 ury=37.6250 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="LED_1[2]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=7.8850 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=7.7850 urx=61.9000 ury=7.9850 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="LED_1[1]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=9.4050 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=9.3050 urx=61.9000 ury=9.5050 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="LED_1[0]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=10.7350 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=10.6350 urx=61.9000 ury=10.8350 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="LED_2[2]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=3.5150 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=3.4150 urx=61.9000 ury=3.6150 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="LED_2[1]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=5.0350 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=4.9350 urx=61.9000 ury=5.1350 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="LED_2[0]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=6.5550 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=6.4550 urx=61.9000 ury=6.6550 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_ch[6]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=45.8850 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=45.7850 urx=61.9000 ury=45.9850 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_ch[5]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=47.4050 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=47.3050 urx=61.9000 ury=47.5050 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_ch[4]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=48.9250 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=48.8250 urx=61.9000 ury=49.0250 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_ch[3]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=50.4450 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=50.3450 urx=61.9000 ury=50.5450 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_ch[2]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=51.7750 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=51.6750 urx=61.9000 ury=51.8750 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_ch[1]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=53.2950 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=53.1950 urx=61.9000 ury=53.3950 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_ch[0]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=2.1850 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=2.0850 urx=61.9000 ury=2.2850 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_dv[6]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=36.1950 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=36.0950 urx=61.9000 ury=36.2950 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_dv[5]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=37.5250 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=37.4250 urx=61.9000 ury=37.6250 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_dv[4]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=38.6650 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=38.5650 urx=61.9000 ury=38.7650 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_dv[3]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=40.1850 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=40.0850 urx=61.9000 ury=40.2850 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_dv[2]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=41.7050 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=41.6050 urx=61.9000 ury=41.8050 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_dv[1]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=43.0350 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=42.9350 urx=61.9000 ury=43.1350 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg1_dv[0]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=44.5550 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=44.4550 urx=61.9000 ury=44.6550 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_ch[6]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=26.8850 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=26.7850 urx=61.9000 ury=26.9850 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_ch[5]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=28.2150 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=28.1150 urx=61.9000 ury=28.3150 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_ch[4]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=29.5450 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=29.4450 urx=61.9000 ury=29.6450 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_ch[3]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=30.8750 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=30.7750 urx=61.9000 ury=30.9750 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_ch[2]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=32.2050 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=32.1050 urx=61.9000 ury=32.3050 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_ch[1]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=33.5350 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=33.4350 urx=61.9000 ury=33.6350 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_ch[0]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=34.8650 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=34.7650 urx=61.9000 ury=34.9650 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_dv[6]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=18.1450 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=18.0450 urx=61.9000 ury=18.2450 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_dv[5]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=19.2850 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=19.1850 urx=61.9000 ury=19.3850 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_dv[4]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=20.4250 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=20.3250 urx=61.9000 ury=20.5250 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_dv[3]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=21.5650 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=21.4650 urx=61.9000 ury=21.6650 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_dv[2]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=22.8950 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=22.7950 urx=61.9000 ury=22.9950 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_dv[1]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=24.2250 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=24.1250 urx=61.9000 ury=24.3250 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="seg2_dv[0]" status="fixed" >
    <Port>
      <Pref x=61.9000 y=25.5550 side=E width=0.2000 depth=2.0000 orientation=R90 />
      <Layer id=3 >
        <Box llx=59.9000 lly=25.4550 urx=61.9000 ury=25.6550 />
      </Layer>
    </Port>
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="top_module">
	<prop name="TDRCAppName" type=String value="OPT_LA:1 GPS_LA:2 NRImport:3 NRTD:4 prLA:5 " />
	<prop name="optimization_trialRoute_guide_flow" type=Int value=1 />
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
