###############################################################
#  Generated by:      Cadence Encounter 13.10-p003_1
#  OS:                Linux i686(Host ID cadence)
#  Generated on:      Fri Sep  4 09:27:07 2026
#  Design:            top_module
#  Command:           saveIoFile -byOrder ouput/ouput_final/topp_module_sequ...
###############################################################

(globals
    version = 3
    io_order = default
)
(iopin
    (left
	(pin name="clk_50mhz"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="rst"	 layer=3 width=0.2000 depth=2.0000 )
    )
    (right
	(pin name="seg1_ch[0]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="LED_2[2]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="LED_2[1]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="LED_2[0]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="LED_1[2]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="LED_1[1]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="LED_1[0]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_dv[6]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_dv[5]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_dv[4]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_dv[3]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_dv[2]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_dv[1]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_dv[0]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_ch[6]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_ch[5]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_ch[4]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_ch[3]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_ch[2]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_ch[1]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg2_ch[0]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_dv[6]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_dv[5]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_dv[4]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_dv[3]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_dv[2]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_dv[1]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_dv[0]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_ch[6]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_ch[5]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_ch[4]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_ch[3]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_ch[2]"	 layer=3 width=0.2000 depth=2.0000 )
	(pin name="seg1_ch[1]"	 layer=3 width=0.2000 depth=2.0000 )
    )
)
