
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/top_module 

module increment_unsigned(A, CI, Z);
  input [25:0] A;
  input CI;
  output [25:0] Z;
  wire [25:0] A;
  wire CI;
  wire [25:0] Z;
  wire n_23, n_25, n_27, n_29, n_31, n_33, n_35, n_37;
  wire n_39, n_41, n_43, n_45, n_47, n_49, n_51, n_53;
  wire n_55, n_57, n_59, n_61, n_63, n_65, n_67, n_69;
  assign Z[0] = 1'b0;
  CLKXOR2X1 g175(.A (A[25]), .B (n_69), .Y (Z[25]));
  ADDHXL g176(.A (A[24]), .B (n_67), .CO (n_69), .S (Z[24]));
  ADDHXL g177(.A (A[23]), .B (n_65), .CO (n_67), .S (Z[23]));
  ADDHXL g178(.A (A[22]), .B (n_63), .CO (n_65), .S (Z[22]));
  ADDHXL g179(.A (A[21]), .B (n_61), .CO (n_63), .S (Z[21]));
  ADDHXL g180(.A (A[20]), .B (n_59), .CO (n_61), .S (Z[20]));
  ADDHXL g181(.A (A[19]), .B (n_57), .CO (n_59), .S (Z[19]));
  ADDHXL g182(.A (A[18]), .B (n_55), .CO (n_57), .S (Z[18]));
  ADDHXL g183(.A (A[17]), .B (n_53), .CO (n_55), .S (Z[17]));
  ADDHXL g184(.A (A[16]), .B (n_51), .CO (n_53), .S (Z[16]));
  ADDHXL g185(.A (A[15]), .B (n_49), .CO (n_51), .S (Z[15]));
  ADDHXL g186(.A (A[14]), .B (n_47), .CO (n_49), .S (Z[14]));
  ADDHXL g187(.A (A[13]), .B (n_45), .CO (n_47), .S (Z[13]));
  ADDHXL g188(.A (A[12]), .B (n_43), .CO (n_45), .S (Z[12]));
  ADDHXL g189(.A (A[11]), .B (n_41), .CO (n_43), .S (Z[11]));
  ADDHXL g190(.A (A[10]), .B (n_39), .CO (n_41), .S (Z[10]));
  ADDHXL g191(.A (A[9]), .B (n_37), .CO (n_39), .S (Z[9]));
  ADDHXL g192(.A (A[8]), .B (n_35), .CO (n_37), .S (Z[8]));
  ADDHXL g193(.A (A[7]), .B (n_33), .CO (n_35), .S (Z[7]));
  ADDHXL g194(.A (A[6]), .B (n_31), .CO (n_33), .S (Z[6]));
  ADDHXL g195(.A (A[5]), .B (n_29), .CO (n_31), .S (Z[5]));
  ADDHXL g196(.A (A[4]), .B (n_27), .CO (n_29), .S (Z[4]));
  ADDHXL g197(.A (A[3]), .B (n_25), .CO (n_27), .S (Z[3]));
  ADDHXL g198(.A (A[2]), .B (n_23), .CO (n_25), .S (Z[2]));
  ADDHXL g199(.A (A[0]), .B (A[1]), .CO (n_23), .S (Z[1]));
endmodule

module clk_1hz(clk_50mhz, rst, clk_1hz);
  input clk_50mhz, rst;
  output clk_1hz;
  wire clk_50mhz, rst;
  wire clk_1hz;
  wire [25:0] cnt;
  wire UNCONNECTED, n_0, n_1, n_2, n_5, n_6, n_7, n_8;
  wire n_9, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_78, n_79;
  increment_unsigned inc_add_27_24_1(.A (cnt), .CI (1'b1), .Z ({n_50,
       n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60,
       n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70,
       n_71, n_72, n_73, n_74, UNCONNECTED}));
  INVX1 g72(.A (rst), .Y (n_46));
  SDFFRHQX1 clk_1hz_reg(.RN (n_46), .CK (clk_50mhz), .D (n_18), .SE
       (clk_1hz), .SI (n_0), .Q (clk_1hz));
  DFFRHQX2 \cnt_reg[10] (.RN (n_46), .CK (clk_50mhz), .D (n_41), .Q
       (cnt[10]));
  DFFRHQX2 \cnt_reg[5] (.RN (n_46), .CK (clk_50mhz), .D (n_33), .Q
       (cnt[5]));
  DFFRHQX2 \cnt_reg[6] (.RN (n_46), .CK (clk_50mhz), .D (n_42), .Q
       (cnt[6]));
  DFFRHQX2 \cnt_reg[7] (.RN (n_46), .CK (clk_50mhz), .D (n_44), .Q
       (cnt[7]));
  DFFRHQX2 \cnt_reg[8] (.RN (n_46), .CK (clk_50mhz), .D (n_43), .Q
       (cnt[8]));
  DFFRHQX2 \cnt_reg[9] (.RN (n_46), .CK (clk_50mhz), .D (n_45), .Q
       (cnt[9]));
  DFFRHQX2 \cnt_reg[11] (.RN (n_46), .CK (clk_50mhz), .D (n_40), .Q
       (cnt[11]));
  DFFRHQX2 \cnt_reg[12] (.RN (n_46), .CK (clk_50mhz), .D (n_38), .Q
       (cnt[12]));
  DFFRHQX2 \cnt_reg[13] (.RN (n_46), .CK (clk_50mhz), .D (n_37), .Q
       (cnt[13]));
  DFFRHQX2 \cnt_reg[14] (.RN (n_46), .CK (clk_50mhz), .D (n_36), .Q
       (cnt[14]));
  DFFRHQX2 \cnt_reg[15] (.RN (n_46), .CK (clk_50mhz), .D (n_35), .Q
       (cnt[15]));
  DFFRHQX2 \cnt_reg[16] (.RN (n_46), .CK (clk_50mhz), .D (n_34), .Q
       (cnt[16]));
  DFFRHQX2 \cnt_reg[17] (.RN (n_46), .CK (clk_50mhz), .D (n_32), .Q
       (cnt[17]));
  DFFRHQX2 \cnt_reg[18] (.RN (n_46), .CK (clk_50mhz), .D (n_39), .Q
       (cnt[18]));
  DFFRHQX2 \cnt_reg[19] (.RN (n_46), .CK (clk_50mhz), .D (n_31), .Q
       (cnt[19]));
  DFFRHQX2 \cnt_reg[1] (.RN (n_46), .CK (clk_50mhz), .D (n_30), .Q
       (cnt[1]));
  DFFRHQX2 \cnt_reg[20] (.RN (n_46), .CK (clk_50mhz), .D (n_28), .Q
       (cnt[20]));
  DFFRHQX2 \cnt_reg[21] (.RN (n_46), .CK (clk_50mhz), .D (n_27), .Q
       (cnt[21]));
  DFFRHQX2 \cnt_reg[22] (.RN (n_46), .CK (clk_50mhz), .D (n_26), .Q
       (cnt[22]));
  DFFRHQX2 \cnt_reg[23] (.RN (n_46), .CK (clk_50mhz), .D (n_25), .Q
       (cnt[23]));
  DFFRHQX2 \cnt_reg[24] (.RN (n_46), .CK (clk_50mhz), .D (n_24), .Q
       (cnt[24]));
  DFFRHQX2 \cnt_reg[25] (.RN (n_46), .CK (clk_50mhz), .D (n_23), .Q
       (cnt[25]));
  DFFRHQX2 \cnt_reg[2] (.RN (n_46), .CK (clk_50mhz), .D (n_22), .Q
       (cnt[2]));
  DFFRHQX2 \cnt_reg[3] (.RN (n_46), .CK (clk_50mhz), .D (n_29), .Q
       (cnt[3]));
  DFFRHQX2 \cnt_reg[4] (.RN (n_46), .CK (clk_50mhz), .D (n_21), .Q
       (cnt[4]));
  NOR2BX1 g1045(.AN (n_66), .B (n_18), .Y (n_45));
  NOR2BX1 g1046(.AN (n_68), .B (n_18), .Y (n_44));
  NOR2BX1 g1047(.AN (n_67), .B (n_18), .Y (n_43));
  NOR2BX1 g1048(.AN (n_69), .B (n_18), .Y (n_42));
  NOR2BX1 g1049(.AN (n_65), .B (n_18), .Y (n_41));
  AND2X1 g1050(.A (n_64), .B (n_0), .Y (n_40));
  AND2X1 g1051(.A (n_0), .B (n_57), .Y (n_39));
  AND2X1 g1052(.A (n_63), .B (n_19), .Y (n_38));
  AND2X1 g1053(.A (n_0), .B (n_62), .Y (n_37));
  AND2X1 g1054(.A (n_19), .B (n_61), .Y (n_36));
  AND2X1 g1055(.A (n_0), .B (n_60), .Y (n_35));
  AND2X1 g1056(.A (n_19), .B (n_59), .Y (n_34));
  NOR2BX1 g1057(.AN (n_70), .B (n_18), .Y (n_33));
  AND2X1 g1058(.A (n_0), .B (n_58), .Y (n_32));
  AND2X1 g1059(.A (n_19), .B (n_56), .Y (n_31));
  NOR2BX1 g1060(.AN (n_74), .B (n_18), .Y (n_30));
  NOR2BX1 g1061(.AN (n_72), .B (n_18), .Y (n_29));
  AND2X1 g1062(.A (n_0), .B (n_55), .Y (n_28));
  AND2X1 g1063(.A (n_19), .B (n_54), .Y (n_27));
  AND2X1 g1064(.A (n_0), .B (n_53), .Y (n_26));
  AND2X1 g1065(.A (n_19), .B (n_52), .Y (n_25));
  AND2X1 g1066(.A (n_0), .B (n_51), .Y (n_24));
  AND2X1 g1067(.A (n_19), .B (n_50), .Y (n_23));
  NOR2BX1 g1068(.AN (n_73), .B (n_18), .Y (n_22));
  NOR2BX1 g1069(.AN (n_71), .B (n_18), .Y (n_21));
  OR3X4 g1072(.A (n_1), .B (cnt[9]), .C (n_17), .Y (n_19));
  OR4X1 g1073(.A (cnt[6]), .B (cnt[7]), .C (cnt[8]), .D (n_16), .Y
       (n_17));
  NAND2X1 g1074(.A (cnt[5]), .B (n_15), .Y (n_16));
  AND4XL g1075(.A (cnt[2]), .B (cnt[3]), .C (cnt[4]), .D (n_14), .Y
       (n_15));
  NOR2X1 g1076(.A (cnt[25]), .B (n_13), .Y (n_14));
  NAND2X1 g1077(.A (cnt[24]), .B (n_12), .Y (n_13));
  NOR2X1 g1078(.A (cnt[23]), .B (n_78), .Y (n_12));
  NAND2X1 g1081(.A (cnt[20]), .B (n_8), .Y (n_9));
  AND4XL g1082(.A (cnt[1]), .B (cnt[18]), .C (cnt[19]), .D (n_7), .Y
       (n_8));
  NOR2X1 g1083(.A (cnt[17]), .B (n_6), .Y (n_7));
  NAND2X1 g1084(.A (cnt[16]), .B (n_5), .Y (n_6));
  NOR2X1 g1085(.A (cnt[15]), .B (n_79), .Y (n_5));
  NAND3BX2 g1088(.AN (cnt[10]), .B (cnt[11]), .C (cnt[12]), .Y (n_2));
  INVX3 drc1090(.A (n_18), .Y (n_0));
  INVX4 drc1091(.A (n_19), .Y (n_18));
  DFFRX2 \cnt_reg[0] (.RN (n_46), .CK (clk_50mhz), .D (n_1), .Q
       (cnt[0]), .QN (n_1));
  NAND3BX2 g2(.AN (n_9), .B (cnt[21]), .C (cnt[22]), .Y (n_78));
  NAND3BX2 g1099(.AN (n_2), .B (cnt[13]), .C (cnt[14]), .Y (n_79));
endmodule

module seg7dec(in, out_hex);
  input [3:0] in;
  output [6:0] out_hex;
  wire [3:0] in;
  wire [6:0] out_hex;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_17, n_18;
  OR2X6 g201(.A (n_10), .B (out_hex[0]), .Y (out_hex[3]));
  OR2X6 g202(.A (n_9), .B (n_17), .Y (out_hex[0]));
  OR2X6 g203(.A (n_9), .B (n_13), .Y (out_hex[1]));
  OR3X6 g204(.A (n_12), .B (n_9), .C (n_10), .Y (out_hex[6]));
  AO21X1 g205(.A0 (in[1]), .A1 (n_4), .B0 (n_14), .Y (n_18));
  AO21X1 g206(.A0 (n_12), .A1 (in[0]), .B0 (n_11), .Y (n_17));
  OR2X6 g207(.A (n_7), .B (in[0]), .Y (out_hex[4]));
  OR2X6 g208(.A (n_9), .B (n_8), .Y (out_hex[2]));
  AO22XL g209(.A0 (n_6), .A1 (in[0]), .B0 (in[3]), .B1 (in[2]), .Y
       (n_14));
  MXI2X2 g210(.A (n_5), .B (n_4), .S0 (in[1]), .Y (n_13));
  AND2X1 g211(.A (n_6), .B (n_3), .Y (n_12));
  NOR2X1 g212(.A (in[1]), .B (n_4), .Y (n_11));
  NOR2X2 g213(.A (n_3), .B (n_5), .Y (n_10));
  OA21X2 g214(.A0 (in[2]), .A1 (in[1]), .B0 (in[3]), .Y (n_9));
  NOR3X2 g215(.A (in[2]), .B (n_3), .C (in[0]), .Y (n_8));
  MX2XL g216(.A (n_0), .B (in[3]), .S0 (in[1]), .Y (n_7));
  NOR2X2 g217(.A (in[3]), .B (n_0), .Y (n_6));
  NAND2X2 g218(.A (n_0), .B (in[0]), .Y (n_5));
  NAND2BX2 g219(.AN (in[0]), .B (in[2]), .Y (n_4));
  INVX2 g220(.A (in[1]), .Y (n_3));
  BUFX6 drc(.A (n_18), .Y (out_hex[5]));
  INVX2 drc222(.A (n_1), .Y (n_0));
  INVX1 drc223(.A (in[2]), .Y (n_1));
endmodule

module seg7dec_31(in, out_hex);
  input [3:0] in;
  output [6:0] out_hex;
  wire [3:0] in;
  wire [6:0] out_hex;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_15, n_16;
  OR2X6 g201(.A (n_8), .B (out_hex[0]), .Y (out_hex[3]));
  OR2X6 g202(.A (n_7), .B (n_15), .Y (out_hex[0]));
  OR2X6 g203(.A (n_7), .B (n_11), .Y (out_hex[1]));
  OR3X6 g204(.A (n_8), .B (n_7), .C (n_10), .Y (out_hex[6]));
  AO21X1 g205(.A0 (in[1]), .A1 (n_2), .B0 (n_12), .Y (n_16));
  AO21X1 g206(.A0 (in[0]), .A1 (n_10), .B0 (n_9), .Y (n_15));
  OR2X6 g207(.A (in[0]), .B (n_5), .Y (out_hex[4]));
  OR2X6 g208(.A (n_6), .B (n_7), .Y (out_hex[2]));
  AO22XL g209(.A0 (in[0]), .A1 (n_4), .B0 (in[3]), .B1 (in[2]), .Y
       (n_12));
  MXI2X2 g210(.A (n_3), .B (n_2), .S0 (in[1]), .Y (n_11));
  AND2X1 g211(.A (n_1), .B (n_4), .Y (n_10));
  NOR2X1 g212(.A (in[1]), .B (n_2), .Y (n_9));
  NOR2X2 g213(.A (n_1), .B (n_3), .Y (n_8));
  OA21X2 g214(.A0 (in[2]), .A1 (in[1]), .B0 (in[3]), .Y (n_7));
  NOR3X2 g215(.A (in[0]), .B (in[2]), .C (n_1), .Y (n_6));
  MX2XL g216(.A (in[2]), .B (in[3]), .S0 (in[1]), .Y (n_5));
  NOR2X2 g217(.A (in[3]), .B (in[2]), .Y (n_4));
  NAND2X2 g218(.A (in[0]), .B (in[2]), .Y (n_3));
  NAND2BX2 g219(.AN (in[0]), .B (in[2]), .Y (n_2));
  INVX1 g220(.A (in[1]), .Y (n_1));
  BUFX6 drc(.A (n_16), .Y (out_hex[5]));
endmodule

module sep2(in, ch, dv);
  input [7:0] in;
  output [3:0] ch, dv;
  wire [7:0] in;
  wire [3:0] ch, dv;
  wire n_0, n_1, n_3, n_4, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_50, n_51;
  wire n_52, n_53, n_54, n_57;
  assign dv[0] = 1'b0;
  assign ch[3] = 1'b0;
  OR2X1 g1153(.A (n_7), .B (n_6), .Y (n_57));
  OR3X4 g1154(.A (n_44), .B (n_45), .C (n_54), .Y (dv[2]));
  OR2X2 g1155(.A (n_53), .B (n_48), .Y (dv[3]));
  OAI22X1 g1156(.A0 (in[1]), .A1 (n_52), .B0 (n_29), .B1 (n_30), .Y
       (n_7));
  AO22XL g1157(.A0 (n_8), .A1 (n_51), .B0 (n_22), .B1 (in[6]), .Y
       (n_54));
  OAI2BB1X1 g1159(.A0N (n_33), .A1N (in[6]), .B0 (n_50), .Y (n_53));
  NOR2X2 g1161(.A (in[6]), .B (n_46), .Y (n_52));
  NAND2BX1 g1162(.AN (n_47), .B (n_34), .Y (n_51));
  AOI22X2 g1163(.A0 (n_20), .A1 (n_42), .B0 (n_22), .B1 (n_36), .Y
       (n_50));
  AO21X2 g1164(.A0 (n_15), .A1 (n_35), .B0 (n_37), .Y (ch[1]));
  AND4XL g1165(.A (n_8), .B (n_15), .C (n_3), .D (n_32), .Y (n_6));
  OAI22X2 g1166(.A0 (n_29), .A1 (n_38), .B0 (n_8), .B1 (n_1), .Y
       (n_48));
  AO22XL g1167(.A0 (n_13), .A1 (n_37), .B0 (n_25), .B1 (n_20), .Y
       (n_47));
  AO21X1 g1168(.A0 (n_3), .A1 (n_20), .B0 (n_41), .Y (n_46));
  AOI21X1 g1169(.A0 (n_28), .A1 (n_30), .B0 (n_3), .Y (n_45));
  AND4XL g1170(.A (n_14), .B (n_15), .C (n_19), .D (n_18), .Y (n_44));
  OAI22X1 g1171(.A0 (n_14), .A1 (n_27), .B0 (n_9), .B1 (n_29), .Y
       (n_43));
  AO22XL g1172(.A0 (n_15), .A1 (n_31), .B0 (in[1]), .B1 (n_19), .Y
       (n_42));
  AO22XL g1173(.A0 (n_4), .A1 (n_32), .B0 (n_19), .B1 (n_17), .Y
       (n_41));
  NAND2BX1 g1174(.AN (n_30), .B (n_25), .Y (n_40));
  AND2X2 g1175(.A (n_15), .B (n_26), .Y (ch[2]));
  AOI2BB1X1 g1176(.A0N (in[6]), .A1N (n_23), .B0 (n_24), .Y (n_38));
  AND3X1 g1177(.A (n_12), .B (n_15), .C (n_20), .Y (n_37));
  AO22XL g1178(.A0 (n_12), .A1 (n_17), .B0 (n_9), .B1 (in[6]), .Y
       (n_36));
  AO22XL g1179(.A0 (n_25), .A1 (n_21), .B0 (in[4]), .B1 (n_17), .Y
       (n_35));
  AOI22X2 g1180(.A0 (n_19), .A1 (n_21), .B0 (in[2]), .B1 (in[6]), .Y
       (n_34));
  NOR2X1 g1181(.A (n_22), .B (n_9), .Y (n_33));
  NAND2BX2 g1182(.AN (n_24), .B (n_23), .Y (n_32));
  NOR2X1 g1183(.A (n_8), .B (n_3), .Y (n_31));
  OR2X1 g1184(.A (in[6]), .B (n_18), .Y (n_30));
  OR2X1 g1185(.A (n_14), .B (n_16), .Y (n_29));
  NAND2X1 g1186(.A (n_14), .B (n_21), .Y (n_28));
  NAND2X1 g1187(.A (n_16), .B (n_17), .Y (n_27));
  OAI2BB1X1 g1188(.A0N (in[4]), .A1N (in[5]), .B0 (n_23), .Y (n_26));
  AND2X1 g1189(.A (in[2]), .B (in[4]), .Y (n_25));
  NOR2X2 g1190(.A (in[3]), .B (in[5]), .Y (n_24));
  NAND2X4 g1191(.A (n_9), .B (in[5]), .Y (n_23));
  AND2X1 g1192(.A (n_13), .B (n_14), .Y (n_22));
  INVX2 g1193(.A (n_21), .Y (n_20));
  OR2X2 g1194(.A (in[3]), .B (n_11), .Y (n_21));
  AND2X2 g1195(.A (in[2]), .B (n_12), .Y (n_19));
  NAND2X2 g1197(.A (in[3]), .B (n_11), .Y (n_18));
  OR2X1 g1199(.A (in[2]), .B (n_12), .Y (n_16));
  INVX2 g1200(.A (in[6]), .Y (n_15));
  INVX2 g1201(.A (in[1]), .Y (n_14));
  INVX1 g1202(.A (in[2]), .Y (n_13));
  INVX2 g1203(.A (in[4]), .Y (n_12));
  INVX1 g1204(.A (in[5]), .Y (n_11));
  INVX2 drc1205(.A (n_10), .Y (n_9));
  INVX1 drc1206(.A (in[3]), .Y (n_10));
  INVX2 drc1209(.A (n_14), .Y (n_8));
  INVX2 drc1218(.A (n_18), .Y (n_17));
  BUFX2 drc1228(.A (n_0), .Y (ch[0]));
  INVX2 drc1231(.A (n_4), .Y (n_3));
  INVX1 drc1232(.A (n_16), .Y (n_4));
  BUFX3 drc1234(.A (n_57), .Y (dv[1]));
  BUFX2 drc1236(.A (n_40), .Y (n_1));
  NAND2BX1 g2(.AN (n_43), .B (n_52), .Y (n_0));
endmodule

module display_2digit(in, seg_ch, seg_dv);
  input [7:0] in;
  output [6:0] seg_ch, seg_dv;
  wire [7:0] in;
  wire [6:0] seg_ch, seg_dv;
  wire [3:0] t_ch;
  wire [3:0] t_dv;
  wire UNCONNECTED0, UNCONNECTED1;
  seg7dec u_ch(.in ({in[6], t_ch[2:0]}), .out_hex (seg_ch));
  seg7dec_31 u_dv(.in ({t_dv[3:1], in[0]}), .out_hex (seg_dv));
  sep2 u_sep2(.in ({1'b0, in[6:1], 1'b0}), .ch ({UNCONNECTED0,
       t_ch[2:0]}), .dv ({t_dv[3:1], UNCONNECTED1}));
endmodule

module seg7dec_30(in, out_hex);
  input [3:0] in;
  output [6:0] out_hex;
  wire [3:0] in;
  wire [6:0] out_hex;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_17, n_18;
  OR2X6 g201(.A (n_10), .B (out_hex[0]), .Y (out_hex[3]));
  OR2X6 g202(.A (n_9), .B (n_17), .Y (out_hex[0]));
  OR2X6 g203(.A (n_9), .B (n_13), .Y (out_hex[1]));
  OR3X6 g204(.A (n_12), .B (n_9), .C (n_10), .Y (out_hex[6]));
  AO21X1 g205(.A0 (in[1]), .A1 (n_4), .B0 (n_14), .Y (n_18));
  AO21X1 g206(.A0 (n_12), .A1 (in[0]), .B0 (n_11), .Y (n_17));
  OR2X6 g207(.A (n_7), .B (in[0]), .Y (out_hex[4]));
  OR2X6 g208(.A (n_9), .B (n_8), .Y (out_hex[2]));
  AO22XL g209(.A0 (n_6), .A1 (in[0]), .B0 (in[3]), .B1 (in[2]), .Y
       (n_14));
  MXI2X2 g210(.A (n_5), .B (n_4), .S0 (in[1]), .Y (n_13));
  AND2X1 g211(.A (n_6), .B (n_3), .Y (n_12));
  NOR2X1 g212(.A (in[1]), .B (n_4), .Y (n_11));
  NOR2X2 g213(.A (n_3), .B (n_5), .Y (n_10));
  OA21X2 g214(.A0 (in[2]), .A1 (in[1]), .B0 (in[3]), .Y (n_9));
  NOR3X2 g215(.A (in[2]), .B (n_3), .C (in[0]), .Y (n_8));
  MX2XL g216(.A (n_0), .B (in[3]), .S0 (in[1]), .Y (n_7));
  NOR2X2 g217(.A (in[3]), .B (n_0), .Y (n_6));
  NAND2X2 g218(.A (n_0), .B (in[0]), .Y (n_5));
  NAND2BX2 g219(.AN (in[0]), .B (in[2]), .Y (n_4));
  INVX2 g220(.A (in[1]), .Y (n_3));
  BUFX6 drc(.A (n_18), .Y (out_hex[5]));
  INVX2 drc222(.A (n_1), .Y (n_0));
  INVX1 drc223(.A (in[2]), .Y (n_1));
endmodule

module seg7dec_29(in, out_hex);
  input [3:0] in;
  output [6:0] out_hex;
  wire [3:0] in;
  wire [6:0] out_hex;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_15, n_16;
  OR2X6 g201(.A (n_8), .B (out_hex[0]), .Y (out_hex[3]));
  OR2X6 g202(.A (n_7), .B (n_15), .Y (out_hex[0]));
  OR2X6 g203(.A (n_7), .B (n_11), .Y (out_hex[1]));
  OR3X6 g204(.A (n_8), .B (n_7), .C (n_10), .Y (out_hex[6]));
  AO21X1 g205(.A0 (in[1]), .A1 (n_2), .B0 (n_12), .Y (n_16));
  AO21X1 g206(.A0 (in[0]), .A1 (n_10), .B0 (n_9), .Y (n_15));
  OR2X6 g207(.A (in[0]), .B (n_5), .Y (out_hex[4]));
  OR2X6 g208(.A (n_6), .B (n_7), .Y (out_hex[2]));
  AO22XL g209(.A0 (in[0]), .A1 (n_4), .B0 (in[3]), .B1 (in[2]), .Y
       (n_12));
  MXI2X2 g210(.A (n_3), .B (n_2), .S0 (in[1]), .Y (n_11));
  AND2X1 g211(.A (n_1), .B (n_4), .Y (n_10));
  NOR2X1 g212(.A (in[1]), .B (n_2), .Y (n_9));
  NOR2X2 g213(.A (n_1), .B (n_3), .Y (n_8));
  OA21X2 g214(.A0 (in[2]), .A1 (in[1]), .B0 (in[3]), .Y (n_7));
  NOR3X2 g215(.A (in[0]), .B (in[2]), .C (n_1), .Y (n_6));
  MX2XL g216(.A (in[2]), .B (in[3]), .S0 (in[1]), .Y (n_5));
  NOR2X2 g217(.A (in[3]), .B (in[2]), .Y (n_4));
  NAND2X2 g218(.A (in[0]), .B (in[2]), .Y (n_3));
  NAND2BX2 g219(.AN (in[0]), .B (in[2]), .Y (n_2));
  INVX1 g220(.A (in[1]), .Y (n_1));
  BUFX6 drc(.A (n_16), .Y (out_hex[5]));
endmodule

module sep2_32(in, ch, dv);
  input [7:0] in;
  output [3:0] ch, dv;
  wire [7:0] in;
  wire [3:0] ch, dv;
  wire n_0, n_1, n_3, n_4, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_50, n_51;
  wire n_52, n_53, n_54, n_57;
  assign dv[0] = 1'b0;
  assign ch[3] = 1'b0;
  OR2X1 g1153(.A (n_7), .B (n_6), .Y (n_57));
  OR3X4 g1154(.A (n_44), .B (n_45), .C (n_54), .Y (dv[2]));
  OR2X2 g1155(.A (n_53), .B (n_48), .Y (dv[3]));
  OAI22X1 g1156(.A0 (in[1]), .A1 (n_52), .B0 (n_29), .B1 (n_30), .Y
       (n_7));
  AO22XL g1157(.A0 (n_8), .A1 (n_51), .B0 (n_22), .B1 (in[6]), .Y
       (n_54));
  OAI2BB1X1 g1159(.A0N (n_33), .A1N (in[6]), .B0 (n_50), .Y (n_53));
  NOR2X2 g1161(.A (in[6]), .B (n_46), .Y (n_52));
  NAND2BX1 g1162(.AN (n_47), .B (n_34), .Y (n_51));
  AOI22X2 g1163(.A0 (n_20), .A1 (n_42), .B0 (n_22), .B1 (n_36), .Y
       (n_50));
  AO21X2 g1164(.A0 (n_15), .A1 (n_35), .B0 (n_37), .Y (ch[1]));
  AND4XL g1165(.A (n_8), .B (n_15), .C (n_3), .D (n_32), .Y (n_6));
  OAI22X2 g1166(.A0 (n_29), .A1 (n_38), .B0 (n_8), .B1 (n_1), .Y
       (n_48));
  AO22XL g1167(.A0 (n_13), .A1 (n_37), .B0 (n_25), .B1 (n_20), .Y
       (n_47));
  AO21X1 g1168(.A0 (n_3), .A1 (n_20), .B0 (n_41), .Y (n_46));
  AOI21X1 g1169(.A0 (n_28), .A1 (n_30), .B0 (n_3), .Y (n_45));
  AND4XL g1170(.A (n_14), .B (n_15), .C (n_19), .D (n_18), .Y (n_44));
  OAI22X1 g1171(.A0 (n_14), .A1 (n_27), .B0 (n_9), .B1 (n_29), .Y
       (n_43));
  AO22XL g1172(.A0 (n_15), .A1 (n_31), .B0 (in[1]), .B1 (n_19), .Y
       (n_42));
  AO22XL g1173(.A0 (n_4), .A1 (n_32), .B0 (n_19), .B1 (n_17), .Y
       (n_41));
  NAND2BX1 g1174(.AN (n_30), .B (n_25), .Y (n_40));
  AND2X2 g1175(.A (n_15), .B (n_26), .Y (ch[2]));
  AOI2BB1X1 g1176(.A0N (in[6]), .A1N (n_23), .B0 (n_24), .Y (n_38));
  AND3X1 g1177(.A (n_12), .B (n_15), .C (n_20), .Y (n_37));
  AO22XL g1178(.A0 (n_12), .A1 (n_17), .B0 (n_9), .B1 (in[6]), .Y
       (n_36));
  AO22XL g1179(.A0 (n_25), .A1 (n_21), .B0 (in[4]), .B1 (n_17), .Y
       (n_35));
  AOI22X2 g1180(.A0 (n_19), .A1 (n_21), .B0 (in[2]), .B1 (in[6]), .Y
       (n_34));
  NOR2X1 g1181(.A (n_22), .B (n_9), .Y (n_33));
  NAND2BX2 g1182(.AN (n_24), .B (n_23), .Y (n_32));
  NOR2X1 g1183(.A (n_8), .B (n_3), .Y (n_31));
  OR2X1 g1184(.A (in[6]), .B (n_18), .Y (n_30));
  OR2X1 g1185(.A (n_14), .B (n_16), .Y (n_29));
  NAND2X1 g1186(.A (n_14), .B (n_21), .Y (n_28));
  NAND2X1 g1187(.A (n_16), .B (n_17), .Y (n_27));
  OAI2BB1X1 g1188(.A0N (in[4]), .A1N (in[5]), .B0 (n_23), .Y (n_26));
  AND2X1 g1189(.A (in[2]), .B (in[4]), .Y (n_25));
  NOR2X2 g1190(.A (in[3]), .B (in[5]), .Y (n_24));
  NAND2X4 g1191(.A (n_9), .B (in[5]), .Y (n_23));
  AND2X1 g1192(.A (n_13), .B (n_14), .Y (n_22));
  INVX2 g1193(.A (n_21), .Y (n_20));
  OR2X2 g1194(.A (in[3]), .B (n_11), .Y (n_21));
  AND2X2 g1195(.A (in[2]), .B (n_12), .Y (n_19));
  NAND2X2 g1197(.A (in[3]), .B (n_11), .Y (n_18));
  OR2X1 g1199(.A (in[2]), .B (n_12), .Y (n_16));
  INVX2 g1200(.A (in[6]), .Y (n_15));
  INVX2 g1201(.A (in[1]), .Y (n_14));
  INVX1 g1202(.A (in[2]), .Y (n_13));
  INVX2 g1203(.A (in[4]), .Y (n_12));
  INVX1 g1204(.A (in[5]), .Y (n_11));
  INVX2 drc1205(.A (n_10), .Y (n_9));
  INVX1 drc1206(.A (in[3]), .Y (n_10));
  INVX2 drc1209(.A (n_14), .Y (n_8));
  INVX2 drc1218(.A (n_18), .Y (n_17));
  BUFX2 drc1228(.A (n_0), .Y (ch[0]));
  INVX2 drc1231(.A (n_4), .Y (n_3));
  INVX1 drc1232(.A (n_16), .Y (n_4));
  BUFX3 drc1234(.A (n_57), .Y (dv[1]));
  BUFX2 drc1236(.A (n_40), .Y (n_1));
  NAND2BX1 g2(.AN (n_43), .B (n_52), .Y (n_0));
endmodule

module display_2digit_14(in, seg_ch, seg_dv);
  input [7:0] in;
  output [6:0] seg_ch, seg_dv;
  wire [7:0] in;
  wire [6:0] seg_ch, seg_dv;
  wire [3:0] t_ch;
  wire [3:0] t_dv;
  wire UNCONNECTED2, UNCONNECTED3;
  seg7dec_30 u_ch(.in ({in[6], t_ch[2:0]}), .out_hex (seg_ch));
  seg7dec_29 u_dv(.in ({t_dv[3:1], in[0]}), .out_hex (seg_dv));
  sep2_32 u_sep2(.in ({1'b0, in[6:1], 1'b0}), .ch ({UNCONNECTED2,
       t_ch[2:0]}), .dv ({t_dv[3:1], UNCONNECTED3}));
endmodule

module display_2digit_cross(in_A, in_B, seg_ch_A, seg_dv_A, seg_ch_B,
     seg_dv_B);
  input [7:0] in_A, in_B;
  output [6:0] seg_ch_A, seg_dv_A, seg_ch_B, seg_dv_B;
  wire [7:0] in_A, in_B;
  wire [6:0] seg_ch_A, seg_dv_A, seg_ch_B, seg_dv_B;
  display_2digit u_A(.in ({1'b0, in_A[6:0]}), .seg_ch (seg_ch_A),
       .seg_dv (seg_dv_A));
  display_2digit_14 u_B(.in ({1'b0, in_B[6:0]}), .seg_ch (seg_ch_B),
       .seg_dv (seg_dv_B));
endmodule

module fsm(clk, rst, LED_1, LED_2, time1, time2);
  input clk, rst;
  output [2:0] LED_1, LED_2;
  output [8:0] time1, time2;
  wire clk, rst;
  wire [2:0] LED_1, LED_2;
  wire [8:0] time1, time2;
  wire [8:0] timer;
  wire [1:0] state;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_72, n_74, n_92, n_93;
  wire n_1072_BAR;
  assign time2[6] = 1'b0;
  assign time2[8] = 1'b0;
  assign time1[6] = 1'b0;
  assign time1[8] = 1'b0;
  assign LED_2[2] = 1'b0;
  OR3X2 g1553(.A (n_57), .B (n_66), .C (n_65), .Y (time1[5]));
  OR3X2 g1554(.A (n_57), .B (n_64), .C (n_63), .Y (time2[5]));
  OR2X4 g1555(.A (n_24), .B (n_64), .Y (time2[7]));
  OR2X4 g1556(.A (n_24), .B (n_66), .Y (time1[7]));
  AND2X1 g1557(.A (timer[5]), .B (n_62), .Y (n_66));
  NOR2X1 g1558(.A (timer[5]), .B (n_60), .Y (n_65));
  AND2X1 g1559(.A (timer[5]), .B (n_61), .Y (n_64));
  NOR2X1 g1560(.A (timer[5]), .B (n_59), .Y (n_63));
  OR2X2 g1561(.A (n_55), .B (n_58), .Y (time2[4]));
  AO21X2 g1562(.A0 (LED_1[0]), .A1 (n_52), .B0 (n_56), .Y (time1[4]));
  OAI22X2 g1563(.A0 (n_33), .A1 (n_51), .B0 (n_31), .B1 (n_49), .Y
       (n_62));
  OAI22X2 g1564(.A0 (n_31), .A1 (n_51), .B0 (n_33), .B1 (n_49), .Y
       (n_61));
  AOI22X2 g1565(.A0 (LED_1[0]), .A1 (n_51), .B0 (n_32), .B1 (n_49), .Y
       (n_60));
  AOI22X2 g1566(.A0 (n_32), .A1 (n_51), .B0 (LED_1[0]), .B1 (n_49), .Y
       (n_59));
  AO22XL g1567(.A0 (n_32), .A1 (n_52), .B0 (LED_1[0]), .B1 (n_50), .Y
       (n_58));
  OR2X2 g1568(.A (n_44), .B (n_53), .Y (time2[3]));
  OR2X2 g1569(.A (n_44), .B (n_54), .Y (time1[3]));
  OA21X1 g1570(.A0 (n_93), .A1 (n_47), .B0 (n_24), .Y (n_57));
  AO21X1 g1571(.A0 (n_32), .A1 (n_50), .B0 (n_55), .Y (n_56));
  AND2X1 g1572(.A (state[0]), .B (n_48), .Y (n_55));
  OAI22X2 g1573(.A0 (n_33), .A1 (n_45), .B0 (n_31), .B1 (n_42), .Y
       (n_54));
  OAI22X1 g1574(.A0 (n_31), .A1 (n_45), .B0 (n_33), .B1 (n_42), .Y
       (n_53));
  ADDHX2 g1575(.A (n_67), .B (n_43), .CO (n_51), .S (n_52));
  ADDHX2 g1576(.A (n_67), .B (n_38), .CO (n_49), .S (n_50));
  ADDHXL g1577(.A (n_67), .B (n_41), .CO (n_47), .S (n_48));
  AOI21X4 g1578(.A0 (n_68), .A1 (n_41), .B0 (n_72), .Y (n_24));
  AND2X1 g1579(.A (n_39), .B (n_43), .Y (n_45));
  CLKMX2X2 g1580(.A (n_40), .B (n_34), .S0 (n_33), .Y (time1[2]));
  CLKMX2X2 g1581(.A (n_40), .B (n_34), .S0 (n_31), .Y (time2[2]));
  AND2X1 g1582(.A (state[0]), .B (n_42), .Y (n_44));
  AO21X1 g1583(.A0 (n_26), .A1 (n_37), .B0 (n_92), .Y (n_43));
  ADDHX1 g1584(.A (n_92), .B (n_30), .CO (n_41), .S (n_42));
  CLKXOR2X1 g1585(.A (timer[1]), .B (n_35), .Y (time1[1]));
  CLKXOR2X1 g1586(.A (timer[1]), .B (n_36), .Y (time2[1]));
  XNOR2X1 g1587(.A (timer[2]), .B (n_37), .Y (n_40));
  NAND2X1 g1588(.A (n_69), .B (n_37), .Y (n_39));
  OR2X1 g1589(.A (n_92), .B (n_30), .Y (n_38));
  AO21X2 g1590(.A0 (n_74), .A1 (n_31), .B0 (n_36), .Y (time2[0]));
  AO21X2 g1591(.A0 (n_74), .A1 (n_33), .B0 (n_35), .Y (time1[0]));
  ADDHX1 g1592(.A (n_74), .B (n_27), .CO (n_37), .S (n_70));
  AND2X1 g1593(.A (timer[0]), .B (n_32), .Y (n_36));
  AND2X1 g1594(.A (timer[0]), .B (LED_1[0]), .Y (n_35));
  AO21X1 g1595(.A0 (n_26), .A1 (n_27), .B0 (n_29), .Y (n_34));
  INVX3 g1596(.A (LED_1[0]), .Y (n_33));
  AND2X8 g1597(.A (n_28), .B (n_72), .Y (LED_1[0]));
  AND2X6 g1598(.A (LED_1[2]), .B (state[0]), .Y (LED_2[1]));
  NAND2X2 g1599(.A (timer[3]), .B (timer[2]), .Y (n_1072_BAR));
  AND2X1 g1600(.A (n_26), .B (n_92), .Y (n_69));
  AND2X1 g1601(.A (n_93), .B (n_67), .Y (n_68));
  INVX2 g1602(.A (n_32), .Y (n_31));
  AND2X6 g1603(.A (LED_1[2]), .B (n_72), .Y (n_32));
  AND2X6 g1604(.A (state[0]), .B (n_28), .Y (LED_1[1]));
  INVX1 g1605(.A (n_29), .Y (n_30));
  AND2X1 g1606(.A (timer[2]), .B (timer[1]), .Y (n_29));
  INVX1 g1607(.A (LED_1[2]), .Y (n_28));
  BUFX6 drc1619(.A (n_32), .Y (LED_2[0]));
  AND2X1 g651(.A (n_74), .B (n_16), .Y (n_23));
  AND2X1 g652(.A (n_8), .B (n_16), .Y (n_22));
  AND2X1 g653(.A (n_70), .B (n_16), .Y (n_21));
  AND2X1 g654(.A (n_13), .B (n_16), .Y (n_20));
  AND2X1 g655(.A (n_10), .B (n_16), .Y (n_19));
  AND2X1 g656(.A (n_12), .B (n_16), .Y (n_18));
  OAI21X1 g657(.A0 (state[0]), .A1 (n_15), .B0 (n_7), .Y (n_17));
  CLKMX2X2 g658(.A (n_15), .B (n_3), .S0 (state[0]), .Y (n_16));
  OA21X1 g659(.A0 (n_93), .A1 (n_67), .B0 (n_14), .Y (n_15));
  OAI2BB1X1 g660(.A0N (n_92), .A1N (n_4), .B0 (timer[5]), .Y (n_14));
  XNOR2X1 g661(.A (timer[3]), .B (n_4), .Y (n_13));
  DFFRHQX8 \state_reg[1] (.RN (n_1), .CK (clk), .D (n_11), .Q
       (LED_1[2]));
  XNOR2X1 g663(.A (timer[5]), .B (n_9), .Y (n_12));
  XNOR2X1 g664(.A (LED_1[2]), .B (n_6), .Y (n_11));
  CLKXOR2X1 g665(.A (timer[4]), .B (n_5), .Y (n_10));
  NAND2BX1 g666(.AN (n_67), .B (n_5), .Y (n_9));
  XNOR2X1 g667(.A (timer[2]), .B (n_2), .Y (n_8));
  NAND2X1 g668(.A (state[0]), .B (n_3), .Y (n_7));
  OR2X1 g669(.A (n_72), .B (n_3), .Y (n_6));
  NOR2X2 g670(.A (n_1072_BAR), .B (n_2), .Y (n_5));
  NAND2BX2 g671(.AN (n_2), .B (timer[2]), .Y (n_4));
  AND2X1 g672(.A (n_68), .B (n_69), .Y (n_3));
  NAND2X4 g673(.A (timer[1]), .B (timer[0]), .Y (n_2));
  INVX1 g674(.A (rst), .Y (n_1));
  DFFRX2 \timer_reg[4] (.RN (n_1), .CK (clk), .D (n_19), .Q (timer[4]),
       .QN (n_67));
  DFFRX4 \state_reg[0] (.RN (n_1), .CK (clk), .D (n_17), .Q (state[0]),
       .QN (n_72));
  DFFRX2 \timer_reg[0] (.RN (n_1), .CK (clk), .D (n_23), .Q (timer[0]),
       .QN (n_74));
  DFFRX2 \timer_reg[1] (.RN (n_1), .CK (clk), .D (n_21), .Q (timer[1]),
       .QN (n_27));
  DFFRX2 \timer_reg[2] (.RN (n_1), .CK (clk), .D (n_22), .Q (timer[2]),
       .QN (n_26));
  DFFRX2 \timer_reg[5] (.RN (n_1), .CK (clk), .D (n_18), .Q (timer[5]),
       .QN (n_93));
  DFFRX2 \timer_reg[3] (.RN (n_1), .CK (clk), .D (n_20), .Q (timer[3]),
       .QN (n_92));
endmodule

module top_module(clk_50mhz, rst, LED_1, LED_2, seg1_ch, seg1_dv,
     seg2_ch, seg2_dv);
  input clk_50mhz, rst;
  output [2:0] LED_1, LED_2;
  output [6:0] seg1_ch, seg1_dv, seg2_ch, seg2_dv;
  wire clk_50mhz, rst;
  wire [2:0] LED_1, LED_2;
  wire [6:0] seg1_ch, seg1_dv, seg2_ch, seg2_dv;
  wire [8:0] time1;
  wire [8:0] time2;
  wire UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7,
       UNCONNECTED8, clk_1hz;
  clk_1hz u_clk(.clk_50mhz (clk_50mhz), .rst (rst), .clk_1hz (clk_1hz));
  display_2digit_cross u_disp(.in_A ({1'b0, time1[7], time1[5:0]}),
       .in_B ({1'b0, time2[7], time2[5:0]}), .seg_ch_A (seg1_ch),
       .seg_dv_A (seg1_dv), .seg_ch_B (seg2_ch), .seg_dv_B (seg2_dv));
  fsm u_fsm(.clk (clk_1hz), .rst (rst), .LED_1 (LED_1), .LED_2
       ({UNCONNECTED4, LED_2[1:0]}), .time1 ({UNCONNECTED5, time1[7],
       UNCONNECTED6, time1[5:0]}), .time2 ({UNCONNECTED7, time2[7],
       UNCONNECTED8, time2[5:0]}));
  INVX6 g2(.A (LED_1[2]), .Y (LED_2[2]));
endmodule

