
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/top_module 

module increment_unsigned(A, CI, Z);
  input [25:0] A;
  input CI;
  output [25:0] Z;
  wire [25:0] A;
  wire CI;
  wire [25:0] Z;
  wire n_0, n_2, n_4, n_6, n_8, n_10, n_12, n_14;
  wire n_16, n_18, n_20, n_22, n_24, n_26, n_28, n_30;
  wire n_32, n_34, n_36, n_38, n_40, n_42, n_44, n_46;
  assign Z[0] = 1'b0;
  XNOR2X1 g175(.A (A[25]), .B (n_46), .Y (Z[25]));
  XNOR2X1 g176(.A (A[24]), .B (n_44), .Y (Z[24]));
  NAND2BX1 g177(.AN (n_44), .B (A[24]), .Y (n_46));
  XNOR2X1 g178(.A (A[23]), .B (n_42), .Y (Z[23]));
  NAND2BX1 g179(.AN (n_42), .B (A[23]), .Y (n_44));
  XNOR2X1 g180(.A (A[22]), .B (n_40), .Y (Z[22]));
  NAND2BX1 g181(.AN (n_40), .B (A[22]), .Y (n_42));
  XNOR2X1 g182(.A (A[21]), .B (n_38), .Y (Z[21]));
  NAND2BX1 g183(.AN (n_38), .B (A[21]), .Y (n_40));
  XNOR2X1 g184(.A (A[20]), .B (n_36), .Y (Z[20]));
  NAND2BX1 g185(.AN (n_36), .B (A[20]), .Y (n_38));
  XNOR2X1 g186(.A (A[19]), .B (n_34), .Y (Z[19]));
  NAND2BX1 g187(.AN (n_34), .B (A[19]), .Y (n_36));
  XNOR2X1 g188(.A (A[18]), .B (n_32), .Y (Z[18]));
  NAND2BX1 g189(.AN (n_32), .B (A[18]), .Y (n_34));
  XNOR2X1 g190(.A (A[17]), .B (n_30), .Y (Z[17]));
  NAND2BX1 g191(.AN (n_30), .B (A[17]), .Y (n_32));
  XNOR2X1 g192(.A (A[16]), .B (n_28), .Y (Z[16]));
  NAND2BX1 g193(.AN (n_28), .B (A[16]), .Y (n_30));
  XNOR2X1 g194(.A (A[15]), .B (n_26), .Y (Z[15]));
  NAND2BX1 g195(.AN (n_26), .B (A[15]), .Y (n_28));
  XNOR2X1 g196(.A (A[14]), .B (n_24), .Y (Z[14]));
  NAND2BX1 g197(.AN (n_24), .B (A[14]), .Y (n_26));
  XNOR2X1 g198(.A (A[13]), .B (n_22), .Y (Z[13]));
  NAND2BX1 g199(.AN (n_22), .B (A[13]), .Y (n_24));
  XNOR2X1 g200(.A (A[12]), .B (n_20), .Y (Z[12]));
  NAND2BX1 g201(.AN (n_20), .B (A[12]), .Y (n_22));
  XNOR2X1 g202(.A (A[11]), .B (n_18), .Y (Z[11]));
  NAND2BX1 g203(.AN (n_18), .B (A[11]), .Y (n_20));
  XNOR2X1 g204(.A (A[10]), .B (n_16), .Y (Z[10]));
  NAND2BX1 g205(.AN (n_16), .B (A[10]), .Y (n_18));
  XNOR2X1 g206(.A (A[9]), .B (n_14), .Y (Z[9]));
  NAND2BX1 g207(.AN (n_14), .B (A[9]), .Y (n_16));
  XNOR2X1 g208(.A (A[8]), .B (n_12), .Y (Z[8]));
  NAND2BX1 g209(.AN (n_12), .B (A[8]), .Y (n_14));
  XNOR2X1 g210(.A (A[7]), .B (n_10), .Y (Z[7]));
  NAND2BX1 g211(.AN (n_10), .B (A[7]), .Y (n_12));
  XNOR2X1 g212(.A (A[6]), .B (n_8), .Y (Z[6]));
  NAND2BX1 g213(.AN (n_8), .B (A[6]), .Y (n_10));
  XNOR2X1 g214(.A (A[5]), .B (n_6), .Y (Z[5]));
  NAND2BX1 g215(.AN (n_6), .B (A[5]), .Y (n_8));
  XNOR2X1 g216(.A (A[4]), .B (n_4), .Y (Z[4]));
  NAND2BX1 g217(.AN (n_4), .B (A[4]), .Y (n_6));
  XNOR2X1 g218(.A (A[3]), .B (n_2), .Y (Z[3]));
  NAND2BX1 g219(.AN (n_2), .B (A[3]), .Y (n_4));
  XNOR2X1 g220(.A (A[2]), .B (n_0), .Y (Z[2]));
  NAND2BX1 g221(.AN (n_0), .B (A[2]), .Y (n_2));
  XOR2XL g222(.A (A[1]), .B (A[0]), .Y (Z[1]));
  NAND2X1 g223(.A (A[0]), .B (A[1]), .Y (n_0));
endmodule

module clk_1hz(clk_50mhz, rst, clk_1hz);
  input clk_50mhz, rst;
  output clk_1hz;
  wire clk_50mhz, rst;
  wire clk_1hz;
  wire [25:0] cnt;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_33, n_34, n_35, n_36, n_37, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_69;
  increment_unsigned inc_add_27_24_1(.A (cnt), .CI (1'b1), .Z ({n_41,
       n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51,
       n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61,
       n_62, n_63, n_64, n_65, UNCONNECTED}));
  INVXL g72(.A (rst), .Y (n_37));
  SDFFRHQX1 clk_1hz_reg(.RN (n_37), .CK (clk_50mhz), .D (n_10), .SI
       (n_9), .SE (clk_1hz), .Q (clk_1hz));
  DFFRX1 \cnt_reg[0] (.RN (n_37), .CK (clk_50mhz), .D (n_69), .Q
       (cnt[0]), .QN (n_69));
  NOR2BX1 g1043(.AN (n_57), .B (n_10), .Y (n_36));
  NOR2BX1 g1044(.AN (n_59), .B (n_10), .Y (n_35));
  NOR2BX1 g1045(.AN (n_58), .B (n_10), .Y (n_34));
  NOR2BX1 g1046(.AN (n_60), .B (n_10), .Y (n_33));
  NOR2BX1 g1048(.AN (n_48), .B (n_10), .Y (n_31));
  NOR2BX1 g1049(.AN (n_56), .B (n_10), .Y (n_30));
  NOR2BX1 g1050(.AN (n_55), .B (n_10), .Y (n_29));
  NOR2BX1 g1051(.AN (n_54), .B (n_10), .Y (n_28));
  NOR2BX1 g1052(.AN (n_53), .B (n_10), .Y (n_27));
  NOR2BX1 g1053(.AN (n_52), .B (n_10), .Y (n_26));
  NOR2BX1 g1054(.AN (n_51), .B (n_10), .Y (n_25));
  NOR2BX1 g1055(.AN (n_50), .B (n_10), .Y (n_24));
  NOR2BX1 g1056(.AN (n_61), .B (n_10), .Y (n_23));
  NOR2BX1 g1057(.AN (n_49), .B (n_10), .Y (n_22));
  NOR2BX1 g1058(.AN (n_47), .B (n_10), .Y (n_21));
  NOR2BX1 g1059(.AN (n_65), .B (n_10), .Y (n_20));
  NOR2BX1 g1060(.AN (n_63), .B (n_10), .Y (n_19));
  NOR2BX1 g1061(.AN (n_46), .B (n_10), .Y (n_18));
  NOR2BX1 g1062(.AN (n_45), .B (n_10), .Y (n_17));
  NOR2BX1 g1063(.AN (n_44), .B (n_10), .Y (n_16));
  NOR2BX1 g1064(.AN (n_43), .B (n_10), .Y (n_15));
  NOR2BX1 g1065(.AN (n_42), .B (n_10), .Y (n_14));
  NOR2BX1 g1066(.AN (n_41), .B (n_10), .Y (n_13));
  NOR2BX1 g1067(.AN (n_64), .B (n_10), .Y (n_12));
  NOR2BX1 g1068(.AN (n_62), .B (n_10), .Y (n_11));
  INVX1 g1069(.A (n_10), .Y (n_9));
  AND2X1 g1070(.A (n_8), .B (cnt[0]), .Y (n_10));
  NOR4X1 g1071(.A (cnt[8]), .B (cnt[7]), .C (cnt[9]), .D (n_7), .Y
       (n_8));
  NAND3BXL g1072(.AN (cnt[6]), .B (cnt[5]), .C (n_6), .Y (n_7));
  AND4XL g1073(.A (cnt[3]), .B (cnt[2]), .C (cnt[4]), .D (n_5), .Y
       (n_6));
  NOR4BX1 g1074(.AN (cnt[24]), .B (cnt[23]), .C (cnt[25]), .D (n_4), .Y
       (n_5));
  NAND4BX1 g1075(.AN (n_3), .B (cnt[20]), .C (cnt[21]), .D (cnt[22]),
       .Y (n_4));
  NAND4XL g1076(.A (cnt[18]), .B (cnt[19]), .C (cnt[1]), .D (n_2), .Y
       (n_3));
  NOR4BX1 g1077(.AN (cnt[16]), .B (cnt[15]), .C (cnt[17]), .D (n_1), .Y
       (n_2));
  NAND4XL g1078(.A (cnt[12]), .B (cnt[13]), .C (n_0), .D (cnt[14]), .Y
       (n_1));
  NOR2BX1 g1079(.AN (cnt[11]), .B (cnt[10]), .Y (n_0));
  DFFRHQX1 \cnt_reg[8] (.RN (n_37), .CK (clk_50mhz), .D (n_34), .Q
       (cnt[8]));
  DFFRHQX1 \cnt_reg[7] (.RN (n_37), .CK (clk_50mhz), .D (n_35), .Q
       (cnt[7]));
  DFFRHQX1 \cnt_reg[9] (.RN (n_37), .CK (clk_50mhz), .D (n_36), .Q
       (cnt[9]));
  DFFRHQX1 \cnt_reg[6] (.RN (n_37), .CK (clk_50mhz), .D (n_33), .Q
       (cnt[6]));
  DFFRHQX1 \cnt_reg[5] (.RN (n_37), .CK (clk_50mhz), .D (n_23), .Q
       (cnt[5]));
  DFFRHQX1 \cnt_reg[3] (.RN (n_37), .CK (clk_50mhz), .D (n_19), .Q
       (cnt[3]));
  DFFRHQX1 \cnt_reg[2] (.RN (n_37), .CK (clk_50mhz), .D (n_12), .Q
       (cnt[2]));
  DFFRHQX1 \cnt_reg[4] (.RN (n_37), .CK (clk_50mhz), .D (n_11), .Q
       (cnt[4]));
  DFFRHQX1 \cnt_reg[24] (.RN (n_37), .CK (clk_50mhz), .D (n_14), .Q
       (cnt[24]));
  DFFRHQX1 \cnt_reg[23] (.RN (n_37), .CK (clk_50mhz), .D (n_15), .Q
       (cnt[23]));
  DFFRHQX1 \cnt_reg[25] (.RN (n_37), .CK (clk_50mhz), .D (n_13), .Q
       (cnt[25]));
  DFFRHQX1 \cnt_reg[18] (.RN (n_37), .CK (clk_50mhz), .D (n_31), .Q
       (cnt[18]));
  DFFRHQX1 \cnt_reg[19] (.RN (n_37), .CK (clk_50mhz), .D (n_21), .Q
       (cnt[19]));
  DFFRHQX1 \cnt_reg[1] (.RN (n_37), .CK (clk_50mhz), .D (n_20), .Q
       (cnt[1]));
  DFFRHQX1 \cnt_reg[16] (.RN (n_37), .CK (clk_50mhz), .D (n_24), .Q
       (cnt[16]));
  DFFRHQX1 \cnt_reg[15] (.RN (n_37), .CK (clk_50mhz), .D (n_25), .Q
       (cnt[15]));
  DFFRHQX1 \cnt_reg[17] (.RN (n_37), .CK (clk_50mhz), .D (n_22), .Q
       (cnt[17]));
  DFFRHQX1 \cnt_reg[12] (.RN (n_37), .CK (clk_50mhz), .D (n_28), .Q
       (cnt[12]));
  DFFRHQX1 \cnt_reg[13] (.RN (n_37), .CK (clk_50mhz), .D (n_27), .Q
       (cnt[13]));
  DFFRHQX1 \cnt_reg[11] (.RN (n_37), .CK (clk_50mhz), .D (n_29), .Q
       (cnt[11]));
  DFFRHQX1 \cnt_reg[10] (.RN (n_37), .CK (clk_50mhz), .D (n_30), .Q
       (cnt[10]));
  DFFRHQX1 \cnt_reg[14] (.RN (n_37), .CK (clk_50mhz), .D (n_26), .Q
       (cnt[14]));
  DFFRHQX1 \cnt_reg[20] (.RN (n_37), .CK (clk_50mhz), .D (n_18), .Q
       (cnt[20]));
  DFFRHQX1 \cnt_reg[21] (.RN (n_37), .CK (clk_50mhz), .D (n_17), .Q
       (cnt[21]));
  DFFRHQX1 \cnt_reg[22] (.RN (n_37), .CK (clk_50mhz), .D (n_16), .Q
       (cnt[22]));
endmodule

module seg7dec(in, out_hex);
  input [3:0] in;
  output [6:0] out_hex;
  wire [3:0] in;
  wire [6:0] out_hex;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10;
  OR2XL g201(.A (n_9), .B (out_hex[0]), .Y (out_hex[3]));
  OAI221X1 g202(.A0 (n_8), .A1 (n_0), .B0 (in[1]), .B1 (n_3), .C0
       (n_7), .Y (out_hex[0]));
  NAND3BXL g203(.AN (n_9), .B (n_8), .C (n_7), .Y (out_hex[6]));
  OAI221X1 g204(.A0 (n_2), .A1 (n_3), .B0 (in[1]), .B1 (n_6), .C0
       (n_7), .Y (out_hex[1]));
  OAI2BB1X1 g205(.A0N (in[1]), .A1N (n_3), .B0 (n_10), .Y (out_hex[5]));
  OAI211X1 g206(.A0 (n_1), .A1 (in[1]), .B0 (n_5), .C0 (n_0), .Y
       (out_hex[4]));
  OAI31X1 g207(.A0 (in[2]), .A1 (n_2), .A2 (in[0]), .B0 (n_7), .Y
       (out_hex[2]));
  AOI22XL g208(.A0 (n_4), .A1 (in[0]), .B0 (in[3]), .B1 (in[2]), .Y
       (n_10));
  NOR2XL g209(.A (n_2), .B (n_6), .Y (n_9));
  NAND2XL g210(.A (n_4), .B (n_2), .Y (n_8));
  OAI21XL g211(.A0 (in[2]), .A1 (in[1]), .B0 (in[3]), .Y (n_7));
  NAND2XL g212(.A (in[2]), .B (in[0]), .Y (n_6));
  NAND2XL g213(.A (in[3]), .B (in[1]), .Y (n_5));
  NOR2XL g214(.A (in[3]), .B (in[2]), .Y (n_4));
  NAND2XL g215(.A (in[2]), .B (n_0), .Y (n_3));
  INVX1 g216(.A (in[1]), .Y (n_2));
  INVX1 g217(.A (in[2]), .Y (n_1));
  INVX1 g218(.A (in[0]), .Y (n_0));
endmodule

module seg7dec_31(in, out_hex);
  input [3:0] in;
  output [6:0] out_hex;
  wire [3:0] in;
  wire [6:0] out_hex;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11;
  OR2XL g201(.A (n_10), .B (out_hex[0]), .Y (out_hex[3]));
  OAI221X1 g202(.A0 (n_1), .A1 (n_9), .B0 (n_0), .B1 (n_4), .C0 (n_8),
       .Y (out_hex[0]));
  NAND3BXL g203(.AN (n_10), .B (n_8), .C (n_9), .Y (out_hex[6]));
  OAI221X1 g204(.A0 (n_3), .A1 (n_4), .B0 (n_0), .B1 (n_7), .C0 (n_8),
       .Y (out_hex[1]));
  OAI2BB1X1 g205(.A0N (in[1]), .A1N (n_4), .B0 (n_11), .Y (out_hex[5]));
  OAI211X1 g206(.A0 (n_2), .A1 (in[1]), .B0 (n_1), .C0 (n_6), .Y
       (out_hex[4]));
  OAI31X1 g207(.A0 (in[0]), .A1 (in[2]), .A2 (n_3), .B0 (n_8), .Y
       (out_hex[2]));
  AOI22XL g208(.A0 (in[0]), .A1 (n_5), .B0 (in[3]), .B1 (in[2]), .Y
       (n_11));
  NOR2XL g209(.A (n_3), .B (n_7), .Y (n_10));
  NAND2XL g210(.A (n_3), .B (n_5), .Y (n_9));
  OAI21XL g211(.A0 (in[2]), .A1 (in[1]), .B0 (in[3]), .Y (n_8));
  NAND2XL g212(.A (in[0]), .B (in[2]), .Y (n_7));
  NAND2XL g213(.A (in[3]), .B (n_0), .Y (n_6));
  NOR2XL g214(.A (in[3]), .B (in[2]), .Y (n_5));
  NAND2XL g215(.A (n_1), .B (in[2]), .Y (n_4));
  INVX1 g217(.A (in[2]), .Y (n_2));
  INVX1 g218(.A (in[0]), .Y (n_1));
  INVX1 drc219(.A (n_3), .Y (n_0));
  INVX1 drc220(.A (in[1]), .Y (n_3));
endmodule

module sep2(in, ch, dv);
  input [7:0] in;
  output [3:0] ch, dv;
  wire [7:0] in;
  wire [3:0] ch, dv;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_29, n_30, n_31, n_32;
  wire n_33, n_35, n_36, n_37, n_39;
  assign dv[0] = 1'b0;
  assign ch[3] = 1'b0;
  OAI221X1 g1153(.A0 (in[1]), .A1 (n_36), .B0 (n_18), .B1 (n_17), .C0
       (n_32), .Y (dv[1]));
  OAI211X1 g1154(.A0 (n_6), .A1 (n_24), .B0 (n_30), .C0 (n_39), .Y
       (dv[2]));
  OAI211X1 g1155(.A0 (n_18), .A1 (n_27), .B0 (n_31), .C0 (n_37), .Y
       (dv[3]));
  AOI22XL g1156(.A0 (in[1]), .A1 (n_35), .B0 (n_16), .B1 (in[6]), .Y
       (n_39));
  OAI211X1 g1157(.A0 (in[3]), .A1 (n_18), .B0 (n_26), .C0 (n_36), .Y
       (ch[0]));
  AOI222X1 g1158(.A0 (n_10), .A1 (n_29), .B0 (n_16), .B1 (n_22), .C0
       (in[6]), .C1 (n_19), .Y (n_37));
  NOR2XL g1159(.A (in[6]), .B (n_33), .Y (n_36));
  OAI221X1 g1160(.A0 (in[2]), .A1 (n_25), .B0 (n_8), .B1 (n_11), .C0
       (n_23), .Y (n_35));
  OAI21XL g1161(.A0 (in[6]), .A1 (n_21), .B0 (n_25), .Y (ch[1]));
  OAI222XL g1162(.A0 (n_11), .A1 (n_7), .B0 (n_6), .B1 (n_20), .C0
       (n_5), .C1 (n_14), .Y (n_33));
  OR4X1 g1163(.A (n_2), .B (in[6]), .C (n_7), .D (n_20), .Y (n_32));
  OR3X1 g1164(.A (in[1]), .B (n_8), .C (n_17), .Y (n_31));
  OR4X1 g1165(.A (in[1]), .B (in[6]), .C (n_5), .D (n_15), .Y (n_30));
  OAI32X1 g1166(.A0 (in[1]), .A1 (in[6]), .A2 (n_6), .B0 (n_2), .B1
       (n_5), .Y (n_29));
  AOI21XL g1167(.A0 (n_13), .A1 (n_12), .B0 (in[6]), .Y (ch[2]));
  AOI2BB1XL g1168(.A0N (in[6]), .A1N (n_13), .B0 (n_9), .Y (n_27));
  NAND3XL g1169(.A (in[1]), .B (n_6), .C (n_15), .Y (n_26));
  NAND3BXL g1170(.AN (in[4]), .B (n_0), .C (n_10), .Y (n_25));
  OA21X1 g1171(.A0 (in[1]), .A1 (n_10), .B0 (n_17), .Y (n_24));
  OA22X1 g1172(.A0 (n_5), .A1 (n_10), .B0 (n_3), .B1 (n_0), .Y (n_23));
  OAI22XL g1173(.A0 (in[4]), .A1 (n_14), .B0 (n_4), .B1 (n_0), .Y
       (n_22));
  OA22X1 g1174(.A0 (n_8), .A1 (n_10), .B0 (n_1), .B1 (n_14), .Y (n_21));
  NOR2BX1 g1175(.AN (n_13), .B (n_9), .Y (n_20));
  NOR2XL g1176(.A (n_16), .B (in[3]), .Y (n_19));
  NAND2XL g1177(.A (in[1]), .B (n_7), .Y (n_18));
  NAND2XL g1178(.A (n_0), .B (n_15), .Y (n_17));
  NOR2XL g1179(.A (in[2]), .B (in[1]), .Y (n_16));
  INVX1 g1180(.A (n_15), .Y (n_14));
  NOR2XL g1181(.A (n_4), .B (in[5]), .Y (n_15));
  NAND2XL g1182(.A (in[3]), .B (in[5]), .Y (n_13));
  NAND2XL g1183(.A (in[4]), .B (in[5]), .Y (n_12));
  INVX1 g1184(.A (n_11), .Y (n_10));
  NAND2XL g1185(.A (n_4), .B (in[5]), .Y (n_11));
  NOR2XL g1186(.A (in[3]), .B (in[5]), .Y (n_9));
  NAND2XL g1187(.A (in[2]), .B (in[4]), .Y (n_8));
  INVX1 g1188(.A (n_7), .Y (n_6));
  NOR2XL g1189(.A (in[2]), .B (n_1), .Y (n_7));
  NAND2XL g1190(.A (in[2]), .B (n_1), .Y (n_5));
  INVX1 g1191(.A (in[3]), .Y (n_4));
  INVX1 g1192(.A (in[2]), .Y (n_3));
  INVX1 g1193(.A (in[1]), .Y (n_2));
  INVX1 g1194(.A (in[4]), .Y (n_1));
  INVX1 g1195(.A (in[6]), .Y (n_0));
endmodule

module display_2digit(in, seg_ch, seg_dv);
  input [7:0] in;
  output [6:0] seg_ch, seg_dv;
  wire [7:0] in;
  wire [6:0] seg_ch, seg_dv;
  wire [3:0] t_ch;
  wire [3:0] t_dv;
  wire UNCONNECTED0, UNCONNECTED1;
  seg7dec u_ch(.in ({in[6], t_ch[2:0]}), .out_hex (seg_ch));
  seg7dec_31 u_dv(.in ({t_dv[3:1], in[0]}), .out_hex (seg_dv));
  sep2 u_sep2(.in ({1'b0, in[6:1], 1'b0}), .ch ({UNCONNECTED0,
       t_ch[2:0]}), .dv ({t_dv[3:1], UNCONNECTED1}));
endmodule

module seg7dec_30(in, out_hex);
  input [3:0] in;
  output [6:0] out_hex;
  wire [3:0] in;
  wire [6:0] out_hex;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10;
  OR2XL g201(.A (n_9), .B (out_hex[0]), .Y (out_hex[3]));
  OAI221X1 g202(.A0 (n_8), .A1 (n_0), .B0 (in[1]), .B1 (n_3), .C0
       (n_7), .Y (out_hex[0]));
  NAND3BXL g203(.AN (n_9), .B (n_8), .C (n_7), .Y (out_hex[6]));
  OAI221X1 g204(.A0 (n_2), .A1 (n_3), .B0 (in[1]), .B1 (n_6), .C0
       (n_7), .Y (out_hex[1]));
  OAI2BB1X1 g205(.A0N (in[1]), .A1N (n_3), .B0 (n_10), .Y (out_hex[5]));
  OAI211X1 g206(.A0 (n_1), .A1 (in[1]), .B0 (n_5), .C0 (n_0), .Y
       (out_hex[4]));
  OAI31X1 g207(.A0 (in[2]), .A1 (n_2), .A2 (in[0]), .B0 (n_7), .Y
       (out_hex[2]));
  AOI22XL g208(.A0 (n_4), .A1 (in[0]), .B0 (in[3]), .B1 (in[2]), .Y
       (n_10));
  NOR2XL g209(.A (n_2), .B (n_6), .Y (n_9));
  NAND2XL g210(.A (n_4), .B (n_2), .Y (n_8));
  OAI21XL g211(.A0 (in[2]), .A1 (in[1]), .B0 (in[3]), .Y (n_7));
  NAND2XL g212(.A (in[2]), .B (in[0]), .Y (n_6));
  NAND2XL g213(.A (in[3]), .B (in[1]), .Y (n_5));
  NOR2XL g214(.A (in[3]), .B (in[2]), .Y (n_4));
  NAND2XL g215(.A (in[2]), .B (n_0), .Y (n_3));
  INVX1 g216(.A (in[1]), .Y (n_2));
  INVX1 g217(.A (in[2]), .Y (n_1));
  INVX1 g218(.A (in[0]), .Y (n_0));
endmodule

module seg7dec_29(in, out_hex);
  input [3:0] in;
  output [6:0] out_hex;
  wire [3:0] in;
  wire [6:0] out_hex;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11;
  OR2XL g201(.A (n_10), .B (out_hex[0]), .Y (out_hex[3]));
  OAI221X1 g202(.A0 (n_1), .A1 (n_9), .B0 (n_0), .B1 (n_4), .C0 (n_8),
       .Y (out_hex[0]));
  NAND3BXL g203(.AN (n_10), .B (n_8), .C (n_9), .Y (out_hex[6]));
  OAI221X1 g204(.A0 (n_3), .A1 (n_4), .B0 (n_0), .B1 (n_7), .C0 (n_8),
       .Y (out_hex[1]));
  OAI2BB1X1 g205(.A0N (in[1]), .A1N (n_4), .B0 (n_11), .Y (out_hex[5]));
  OAI211X1 g206(.A0 (n_2), .A1 (in[1]), .B0 (n_1), .C0 (n_6), .Y
       (out_hex[4]));
  OAI31X1 g207(.A0 (in[0]), .A1 (in[2]), .A2 (n_3), .B0 (n_8), .Y
       (out_hex[2]));
  AOI22XL g208(.A0 (in[0]), .A1 (n_5), .B0 (in[3]), .B1 (in[2]), .Y
       (n_11));
  NOR2XL g209(.A (n_3), .B (n_7), .Y (n_10));
  NAND2XL g210(.A (n_3), .B (n_5), .Y (n_9));
  OAI21XL g211(.A0 (in[2]), .A1 (in[1]), .B0 (in[3]), .Y (n_8));
  NAND2XL g212(.A (in[0]), .B (in[2]), .Y (n_7));
  NAND2XL g213(.A (in[3]), .B (n_0), .Y (n_6));
  NOR2XL g214(.A (in[3]), .B (in[2]), .Y (n_5));
  NAND2XL g215(.A (n_1), .B (in[2]), .Y (n_4));
  INVX1 g217(.A (in[2]), .Y (n_2));
  INVX1 g218(.A (in[0]), .Y (n_1));
  INVX1 drc219(.A (n_3), .Y (n_0));
  INVX1 drc220(.A (in[1]), .Y (n_3));
endmodule

module sep2_32(in, ch, dv);
  input [7:0] in;
  output [3:0] ch, dv;
  wire [7:0] in;
  wire [3:0] ch, dv;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_29, n_30, n_31, n_32;
  wire n_33, n_35, n_36, n_37, n_39;
  assign dv[0] = 1'b0;
  assign ch[3] = 1'b0;
  OAI221X1 g1153(.A0 (in[1]), .A1 (n_36), .B0 (n_18), .B1 (n_17), .C0
       (n_32), .Y (dv[1]));
  OAI211X1 g1154(.A0 (n_6), .A1 (n_24), .B0 (n_30), .C0 (n_39), .Y
       (dv[2]));
  OAI211X1 g1155(.A0 (n_18), .A1 (n_27), .B0 (n_31), .C0 (n_37), .Y
       (dv[3]));
  AOI22XL g1156(.A0 (in[1]), .A1 (n_35), .B0 (n_16), .B1 (in[6]), .Y
       (n_39));
  OAI211X1 g1157(.A0 (in[3]), .A1 (n_18), .B0 (n_26), .C0 (n_36), .Y
       (ch[0]));
  AOI222X1 g1158(.A0 (n_10), .A1 (n_29), .B0 (n_16), .B1 (n_22), .C0
       (in[6]), .C1 (n_19), .Y (n_37));
  NOR2XL g1159(.A (in[6]), .B (n_33), .Y (n_36));
  OAI221X1 g1160(.A0 (in[2]), .A1 (n_25), .B0 (n_8), .B1 (n_11), .C0
       (n_23), .Y (n_35));
  OAI21XL g1161(.A0 (in[6]), .A1 (n_21), .B0 (n_25), .Y (ch[1]));
  OAI222XL g1162(.A0 (n_11), .A1 (n_7), .B0 (n_6), .B1 (n_20), .C0
       (n_5), .C1 (n_14), .Y (n_33));
  OR4X1 g1163(.A (n_2), .B (in[6]), .C (n_7), .D (n_20), .Y (n_32));
  OR3X1 g1164(.A (in[1]), .B (n_8), .C (n_17), .Y (n_31));
  OR4X1 g1165(.A (in[1]), .B (in[6]), .C (n_5), .D (n_15), .Y (n_30));
  OAI32X1 g1166(.A0 (in[1]), .A1 (in[6]), .A2 (n_6), .B0 (n_2), .B1
       (n_5), .Y (n_29));
  AOI21XL g1167(.A0 (n_13), .A1 (n_12), .B0 (in[6]), .Y (ch[2]));
  AOI2BB1XL g1168(.A0N (in[6]), .A1N (n_13), .B0 (n_9), .Y (n_27));
  NAND3XL g1169(.A (in[1]), .B (n_6), .C (n_15), .Y (n_26));
  NAND3BXL g1170(.AN (in[4]), .B (n_0), .C (n_10), .Y (n_25));
  OA21X1 g1171(.A0 (in[1]), .A1 (n_10), .B0 (n_17), .Y (n_24));
  OA22X1 g1172(.A0 (n_5), .A1 (n_10), .B0 (n_3), .B1 (n_0), .Y (n_23));
  OAI22XL g1173(.A0 (in[4]), .A1 (n_14), .B0 (n_4), .B1 (n_0), .Y
       (n_22));
  OA22X1 g1174(.A0 (n_8), .A1 (n_10), .B0 (n_1), .B1 (n_14), .Y (n_21));
  NOR2BX1 g1175(.AN (n_13), .B (n_9), .Y (n_20));
  NOR2XL g1176(.A (n_16), .B (in[3]), .Y (n_19));
  NAND2XL g1177(.A (in[1]), .B (n_7), .Y (n_18));
  NAND2XL g1178(.A (n_0), .B (n_15), .Y (n_17));
  NOR2XL g1179(.A (in[2]), .B (in[1]), .Y (n_16));
  INVX1 g1180(.A (n_15), .Y (n_14));
  NOR2XL g1181(.A (n_4), .B (in[5]), .Y (n_15));
  NAND2XL g1182(.A (in[3]), .B (in[5]), .Y (n_13));
  NAND2XL g1183(.A (in[4]), .B (in[5]), .Y (n_12));
  INVX1 g1184(.A (n_11), .Y (n_10));
  NAND2XL g1185(.A (n_4), .B (in[5]), .Y (n_11));
  NOR2XL g1186(.A (in[3]), .B (in[5]), .Y (n_9));
  NAND2XL g1187(.A (in[2]), .B (in[4]), .Y (n_8));
  INVX1 g1188(.A (n_7), .Y (n_6));
  NOR2XL g1189(.A (in[2]), .B (n_1), .Y (n_7));
  NAND2XL g1190(.A (in[2]), .B (n_1), .Y (n_5));
  INVX1 g1191(.A (in[3]), .Y (n_4));
  INVX1 g1192(.A (in[2]), .Y (n_3));
  INVX1 g1193(.A (in[1]), .Y (n_2));
  INVX1 g1194(.A (in[4]), .Y (n_1));
  INVX1 g1195(.A (in[6]), .Y (n_0));
endmodule

module display_2digit_14(in, seg_ch, seg_dv);
  input [7:0] in;
  output [6:0] seg_ch, seg_dv;
  wire [7:0] in;
  wire [6:0] seg_ch, seg_dv;
  wire [3:0] t_ch;
  wire [3:0] t_dv;
  wire UNCONNECTED2, UNCONNECTED3;
  seg7dec_30 u_ch(.in ({in[6], t_ch[2:0]}), .out_hex (seg_ch));
  seg7dec_29 u_dv(.in ({t_dv[3:1], in[0]}), .out_hex (seg_dv));
  sep2_32 u_sep2(.in ({1'b0, in[6:1], 1'b0}), .ch ({UNCONNECTED2,
       t_ch[2:0]}), .dv ({t_dv[3:1], UNCONNECTED3}));
endmodule

module display_2digit_cross(in_A, in_B, seg_ch_A, seg_dv_A, seg_ch_B,
     seg_dv_B);
  input [7:0] in_A, in_B;
  output [6:0] seg_ch_A, seg_dv_A, seg_ch_B, seg_dv_B;
  wire [7:0] in_A, in_B;
  wire [6:0] seg_ch_A, seg_dv_A, seg_ch_B, seg_dv_B;
  display_2digit u_A(.in ({1'b0, in_A[6:0]}), .seg_ch (seg_ch_A),
       .seg_dv (seg_dv_A));
  display_2digit_14 u_B(.in ({1'b0, in_B[6:0]}), .seg_ch (seg_ch_B),
       .seg_dv (seg_dv_B));
endmodule

module fsm(clk, rst, LED_1, LED_2, time1, time2);
  input clk, rst;
  output [2:0] LED_1, LED_2;
  output [8:0] time1, time2;
  wire clk, rst;
  wire [2:0] LED_1, LED_2;
  wire [8:0] time1, time2;
  wire [8:0] timer;
  wire [1:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_22, n_23, n_24;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_60, n_80, n_84, n_85, n_86, n_87, n_1072_BAR;
  assign time2[6] = 1'b0;
  assign time2[8] = 1'b0;
  assign time1[6] = 1'b0;
  assign time1[8] = 1'b0;
  assign LED_2[2] = 1'b0;
  OAI211X1 g1566(.A0 (timer[5]), .A1 (n_50), .B0 (n_49), .C0 (n_55), .Y
       (time1[5]));
  OAI211X1 g1567(.A0 (timer[5]), .A1 (n_52), .B0 (n_49), .C0 (n_54), .Y
       (time2[5]));
  NAND2X1 g1568(.A (n_43), .B (n_54), .Y (time2[7]));
  NAND2X1 g1569(.A (n_43), .B (n_55), .Y (time1[7]));
  NAND2XL g1570(.A (timer[5]), .B (n_53), .Y (n_55));
  NAND2XL g1571(.A (timer[5]), .B (n_51), .Y (n_54));
  OAI221X1 g1572(.A0 (n_26), .A1 (n_46), .B0 (n_29), .B1 (n_41), .C0
       (n_48), .Y (time2[4]));
  OAI22XL g1573(.A0 (n_29), .A1 (n_45), .B0 (n_26), .B1 (n_39), .Y
       (n_53));
  AOI22XL g1574(.A0 (LED_2[0]), .A1 (n_45), .B0 (LED_1[0]), .B1 (n_39),
       .Y (n_52));
  OAI22XL g1575(.A0 (n_26), .A1 (n_45), .B0 (n_29), .B1 (n_39), .Y
       (n_51));
  AOI22XL g1576(.A0 (LED_1[0]), .A1 (n_45), .B0 (LED_2[0]), .B1 (n_39),
       .Y (n_50));
  OAI221X1 g1577(.A0 (n_29), .A1 (n_46), .B0 (n_26), .B1 (n_41), .C0
       (n_48), .Y (time1[4]));
  NAND2BXL g1578(.AN (n_43), .B (n_47), .Y (n_49));
  OAI221X1 g1579(.A0 (n_26), .A1 (n_44), .B0 (n_29), .B1 (n_36), .C0
       (n_40), .Y (time2[3]));
  OAI221X1 g1580(.A0 (n_29), .A1 (n_44), .B0 (n_26), .B1 (n_36), .C0
       (n_40), .Y (time1[3]));
  NAND2XL g1581(.A (state[0]), .B (n_42), .Y (n_48));
  OAI2BB1X1 g1582(.A0N (n_56), .A1N (n_35), .B0 (timer[5]), .Y (n_47));
  XNOR2X1 g1583(.A (n_56), .B (n_38), .Y (n_46));
  AND2X1 g1584(.A (n_38), .B (n_56), .Y (n_45));
  AOI21XL g1585(.A0 (n_58), .A1 (n_28), .B0 (n_37), .Y (n_44));
  OAI2BB1X1 g1586(.A0N (n_57), .A1N (n_35), .B0 (state[0]), .Y (n_43));
  XNOR2X1 g1587(.A (timer[4]), .B (n_35), .Y (n_42));
  XNOR2X1 g1588(.A (n_56), .B (n_33), .Y (n_41));
  MX2X1 g1589(.A (n_34), .B (n_30), .S0 (n_26), .Y (time2[2]));
  MX2X1 g1590(.A (n_34), .B (n_30), .S0 (n_29), .Y (time1[2]));
  NAND2XL g1591(.A (state[0]), .B (n_36), .Y (n_40));
  AND2X1 g1592(.A (n_33), .B (n_56), .Y (n_39));
  INVX1 g1593(.A (n_37), .Y (n_38));
  AOI21XL g1594(.A0 (n_84), .A1 (n_28), .B0 (n_80), .Y (n_37));
  XNOR2X1 g1595(.A (timer[1]), .B (n_32), .Y (time1[1]));
  XNOR2X1 g1596(.A (timer[1]), .B (n_31), .Y (time2[1]));
  ADDHX1 g1597(.A (n_80), .B (n_27), .CO (n_35), .S (n_36));
  XNOR2X1 g1598(.A (timer[2]), .B (n_28), .Y (n_34));
  OR2X1 g1599(.A (n_80), .B (n_27), .Y (n_33));
  OAI21XL g1600(.A0 (timer[0]), .A1 (LED_2[0]), .B0 (n_31), .Y
       (time2[0]));
  OAI21XL g1601(.A0 (timer[0]), .A1 (LED_1[0]), .B0 (n_32), .Y
       (time1[0]));
  NAND2XL g1602(.A (timer[0]), .B (LED_1[0]), .Y (n_32));
  NAND2XL g1603(.A (timer[0]), .B (LED_2[0]), .Y (n_31));
  OAI21XL g1604(.A0 (timer[1]), .A1 (timer[2]), .B0 (n_27), .Y (n_30));
  INVX1 g1606(.A (LED_1[0]), .Y (n_29));
  NOR2XL g1607(.A (LED_1[2]), .B (state[0]), .Y (LED_1[0]));
  NAND2XL g1608(.A (timer[3]), .B (timer[2]), .Y (n_1072_BAR));
  NOR2XL g1610(.A (timer[1]), .B (timer[0]), .Y (n_28));
  NAND2XL g1611(.A (timer[1]), .B (timer[2]), .Y (n_27));
  NOR2XL g1612(.A (LED_1[2]), .B (n_60), .Y (LED_1[1]));
  INVX1 g1613(.A (n_26), .Y (LED_2[0]));
  NAND2X1 g1614(.A (LED_1[2]), .B (n_60), .Y (n_26));
  AND2XL g1615(.A (LED_1[2]), .B (state[0]), .Y (LED_2[1]));
  NOR2XL g1616(.A (timer[5]), .B (timer[4]), .Y (n_57));
  NOR2XL g1617(.A (timer[2]), .B (timer[3]), .Y (n_58));
  DFFRHQX1 \timer_reg[1] (.RN (n_0), .CK (clk), .D (n_87), .Q
       (timer[1]));
  AND2X1 g651(.A (n_18), .B (n_85), .Y (n_24));
  AND2X1 g652(.A (n_18), .B (n_7), .Y (n_23));
  NOR2XL g653(.A (n_9), .B (n_17), .Y (n_22));
  NOR2XL g655(.A (n_12), .B (n_17), .Y (n_20));
  NOR2XL g656(.A (n_11), .B (n_17), .Y (n_19));
  INVX1 g657(.A (n_18), .Y (n_17));
  OAI21XL g658(.A0 (state[0]), .A1 (n_14), .B0 (n_5), .Y (n_18));
  OAI21XL g659(.A0 (state[0]), .A1 (n_15), .B0 (n_5), .Y (n_16));
  INVX1 g660(.A (n_14), .Y (n_15));
  OAI21XL g661(.A0 (n_86), .A1 (n_56), .B0 (n_13), .Y (n_14));
  OAI2BB1X1 g662(.A0N (n_80), .A1N (n_4), .B0 (timer[5]), .Y (n_13));
  CLKXOR2X1 g663(.A (timer[3]), .B (n_4), .Y (n_12));
  DFFRHQX1 \state_reg[1] (.RN (n_0), .CK (clk), .D (n_10), .Q
       (LED_1[2]));
  XNOR2X1 g665(.A (timer[5]), .B (n_8), .Y (n_11));
  XNOR2X1 g666(.A (LED_1[2]), .B (n_6), .Y (n_10));
  XNOR2X1 g667(.A (timer[4]), .B (n_3), .Y (n_9));
  NOR2BX1 g668(.AN (n_3), .B (n_56), .Y (n_8));
  XNOR2X1 g669(.A (timer[2]), .B (n_1), .Y (n_7));
  NAND2BXL g670(.AN (n_60), .B (n_2), .Y (n_6));
  NAND2BXL g671(.AN (n_2), .B (state[0]), .Y (n_5));
  NAND2BXL g672(.AN (n_1), .B (timer[2]), .Y (n_4));
  NOR2XL g673(.A (n_1072_BAR), .B (n_1), .Y (n_3));
  NAND2XL g674(.A (n_58), .B (n_57), .Y (n_2));
  NAND2XL g675(.A (timer[1]), .B (timer[0]), .Y (n_1));
  INVX1 g676(.A (rst), .Y (n_0));
  DFFRX1 \timer_reg[2] (.RN (n_0), .CK (clk), .D (n_23), .Q (timer[2]),
       .QN (n_84));
  DFFRX1 \timer_reg[4] (.RN (n_0), .CK (clk), .D (n_22), .Q (timer[4]),
       .QN (n_56));
  DFFRX1 \timer_reg[0] (.RN (n_0), .CK (clk), .D (n_24), .Q (timer[0]),
       .QN (n_85));
  DFFRX1 \state_reg[0] (.RN (n_0), .CK (clk), .D (n_16), .Q (state[0]),
       .QN (n_60));
  DFFRX1 \timer_reg[5] (.RN (n_0), .CK (clk), .D (n_19), .Q (timer[5]),
       .QN (n_86));
  DFFRX1 \timer_reg[3] (.RN (n_0), .CK (clk), .D (n_20), .Q (timer[3]),
       .QN (n_80));
  AOI211XL g1636(.A0 (timer[0]), .A1 (timer[1]), .B0 (n_28), .C0
       (n_17), .Y (n_87));
endmodule

module top_module(clk_50mhz, rst, LED_1, LED_2, seg1_ch, seg1_dv,
     seg2_ch, seg2_dv);
  input clk_50mhz, rst;
  output [2:0] LED_1, LED_2;
  output [6:0] seg1_ch, seg1_dv, seg2_ch, seg2_dv;
  wire clk_50mhz, rst;
  wire [2:0] LED_1, LED_2;
  wire [6:0] seg1_ch, seg1_dv, seg2_ch, seg2_dv;
  wire [8:0] time1;
  wire [8:0] time2;
  wire UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7,
       UNCONNECTED8, clk_1hz;
  clk_1hz u_clk(.clk_50mhz (clk_50mhz), .rst (rst), .clk_1hz (clk_1hz));
  display_2digit_cross u_disp(.in_A ({1'b0, time1[7], time1[5:0]}),
       .in_B ({1'b0, time2[7], time2[5:0]}), .seg_ch_A (seg1_ch),
       .seg_dv_A (seg1_dv), .seg_ch_B (seg2_ch), .seg_dv_B (seg2_dv));
  fsm u_fsm(.clk (clk_1hz), .rst (rst), .LED_1 (LED_1), .LED_2
       ({UNCONNECTED4, LED_2[1:0]}), .time1 ({UNCONNECTED5, time1[7],
       UNCONNECTED6, time1[5:0]}), .time2 ({UNCONNECTED7, time2[7],
       UNCONNECTED8, time2[5:0]}));
  INVXL g2(.A (LED_1[2]), .Y (LED_2[2]));
endmodule

